### ISSUE TITLE
Rebuild the preconditioner

### ISSUE THREAD

**Issue by mo7ammedmostafa** [ddemidov/amgcl#101]
Hello,

Right now I am using the following code to solve Ax=rhs, the code works perfectly without a problem but I want to know if it is possible to rebuild the preconditioner using a new matrix with nearly identical non-zero structure but different values without having to do it completely from scratch every time step

`

typedef
        amgcl::amg<
            Backend,
            amgcl::coarsening::smoothed_aggregation,
            amgcl::relaxation::spai0
            >
        Precond;

    typedef
        amgcl::solver::cg< Backend >
        Solver;

    std::vector<ptrdiff_t> ptr, col;
    std::vector<double>    val_d;
    std::vector<double>    rhs;
    // copy matrix data and rhs  from  petsc format here
    Backend::params bprm;
 
    
    auto A_d = std::tie(n, ptr, col, val);
    
    std::vector<double> x(n, 0.0);

    prof.tic("setup");
    Solver S(n, Solver::params(), bprm);
    Precond P(A_d, Precond::params(), bprm);
    prof.toc("setup");

    std::cout << P << std::endl;

    int iters;
    double error;
    prof.tic("solve");
    std::tie(iters, error) = S(A_d, P, rhs, x);
    prof.toc("solve");`

Thank you very much

**Comment by ddemidov** [comment]
Hi,

It is currently impossible to partially reuse a preconditioner, see also #59.
I think PETSC uses CSR (they call it AIJ) format internally, so if there is a way to get pointers to the raw matrix data, then you could get rid of some memory copies by adapting PETSC matrix directly (see how it is done for ublas [here](https://github.com/ddemidov/amgcl/blob/bf3822602da988e37a5a7e16ad16d84472ec26fa/amgcl/adapter/ublas.hpp#L50-L71)).

**Comment by mo7ammedmostafa** [comment]
Hi,
Thanks for the quick reply.
With regards to copy issue, I do extract the raw pointers from AIJ matrix so I will take your advice and write no copy adapter similar to ublas although in my timings of the biggest matrix possible on my computing workstation shows that the copy only constitute 0.5% of total solve time.

As for the rebuild issue, is it possible to at least clear the memory of the instance. Precond P like a destructor. So that I can construct a new preconditioner based on the new matrix

Thanks

**Comment by ddemidov** [comment]
> As for the rebuild issue, is it possible to at least clear the memory of the instance. Precond P like a destructor. So that I can construct a new preconditioner based on the new matrix

You can use something `std::unique_pointer` to control lifetime of your preconditioner, see #100 for an example.

**Comment by mo7ammedmostafa** [comment]
Thanks, that really helps
