### ISSUE TITLE
Question about support for AMG for matrix-free CG

### ISSUE THREAD

**Issue by jaak-s** [ddemidov/amgcl#11]
I am trying to speed up CG for `(F'F + \lambda*\eye) x = b` by using preconditioning. Matrix `F` is large and sparse but computing `F'F` explicitly is too costly. Would it be possible to use your software to build AMG preconditioner in this situation? All ideas are welcome.

Just mention that the problem involves solving the same system for several RHSs, i.e. it is no problem if computing the preconditioner takes time.

Thank you.

**Comment by ddemidov** [comment]
Hi,

Unfortunately, the algebraic multigrid method requires the system matrix for setup. You could skip memory allocation for the entire matrix by using [crs_builder](https://github.com/ddemidov/amgcl/blob/master/amgcl/adapter/crs_builder.hpp) adapter, but you would still need to construct the matrix row by row.

The iterative methods implemented in amgcl may be adapted to be matrix-free though. You only need to provide a specialization for [amgcl::backend::spmv](https://github.com/ddemidov/amgcl/blob/15fe7e08d07e626140197177f377faa54919fdd5/amgcl/backend/interface.hpp#L139-L144). So if you could come up with another matrix `B`, that is different from `A = (F'F + \lambda \eye)`, but is easy to construct and `B^{-1}` is a good preconditioner for `A`, you could then use `B` to construct the AMG method and use `A` with an iterative method preconditioned by AMG.

**Comment by jaak-s** [comment]
Hi,

Thank you for the idea. I will look into this further. 

Maybe would be interesting research topic how to efficiently define AMG operators on `F'F + \lambda \eye` using `F`, because it is possible to identify connected (correlated) columns of `F` without computing full `F'F`.
