### ISSUE TITLE
Run examples

### ISSUE THREAD

**Issue by Tongdongq** [ddemidov/amgcl#111]
How do I install this library and run the examples?
I did `./setup.py build` and it produces `build/lib.xxx/pyamgcl/pyamgcl_ext.so`.
There is also a CMakeLists.txt in the root, but doing `cmake .. && make` in build does nothing.

**Comment by ddemidov** [comment]
The library is header only, so (the C++ part) does not require installation, you should just point your compiler to the library location. There is an arch linux package, which you can use as an example of system-wide installation:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=amgcl-git


Examples are meant to be compiled with cmake, something like:

```sh
cd amgcl
mkdir build
cd build
cmake -DAMGCL_BUILD_EXAMPLES=ON ..
make
./examples/solver --help
```

**Comment by Tongdongq** [comment]
I didn't see that flag, building now.
What role do the produced `.so` and `setup.py` have?

**Comment by ddemidov** [comment]
The .so is the python extension module for the python wrapper (a usage example is available in https://github.com/ddemidov/amgcl/blob/master/examples/pysolver.py)

**Comment by CebFu** [comment]
> The .so is the python extension module for the python wrapper (a usage example is available in https://github.com/ddemidov/amgcl/blob/master/examples/pysolver.py)

Hello, Denis. @ddemidov - How can I install Pyamgcl on Windows environment?

**Comment by ddemidov** [comment]
does `python setup.py install` work? you need to install pybind11 and numpy before that.

**Comment by CebFu** [comment]
@ddemidov - It does not work. Is my version of python wrong? I use python 3.11.

error log:

c1xx: fatal error C1083: cannot open source file: “C:\Users\ARTHUR~1.ZHU\AppData\Local\Temp\tmp_k4q7dck.cpp”: Permission denied
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Arthur.Zhuang\anaconda3\envs\py311\include -IC:\Users\Arthur.Zhuang\anaconda3\envs\py311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /TpC:\Users\ARTHUR~1.ZHU\AppData\Local\Temp\tmparl3bjjy.cpp /FoUsers\ARTHUR~1.ZHU\AppData\Local\Temp\tmparl3bjjy.obj -openmp
tmparl3bjjy.cpp
c1xx: fatal error C1083: cannot open source file: “C:\Users\ARTHUR~1.ZHU\AppData\Local\Temp\tmparl3bjjy.cpp”: Permission denied
building 'pyamgcl.pyamgcl_ext' extension
creating build\temp.win-amd64-cpython-311
creating build\temp.win-amd64-cpython-311\Release
creating build\temp.win-amd64-cpython-311\Release\pyamgcl
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I. -IC:\Users\Arthur.Zhuang\anaconda3\envs\py311\Lib\site-packages\pybind11\include -IC:\Users\Arthur.Zhuang\anaconda3\envs\py311\Lib\site-packages\pybind11\include -IC:\Users\Arthur.Zhuang\anaconda3\envs\py311\include -IC:\Users\Arthur.Zhuang\anaconda3\envs\py311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tppyamgcl/pyamgcl.cpp /Fobuild\temp.win-amd64-cpython-311\Release\pyamgcl/pyamgcl.obj /EHsc /DVERSION_INFO=\\\"0.0.1\\\"
pyamgcl.cpp
pyamgcl/pyamgcl.cpp(6): fatal error C1083: cannot open source file: “boost/range/iterator_range.hpp”: No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by CebFu** [comment]
@ddemidov - I installed boost as you asked, and add the folder [installation dir] as an environment variable called BOOST_ROOT. But the same error still occurs. I don't know what the problem is. Thanks very much for your guidance.

**Comment by CebFu** [comment]
@ddemidov -Thanks very much. It works now.  I add the boost path (BOOST_PATH = os.environ['BOOST_ROOT']
) inside the include_dirs in the setup.py.

**Comment by ddemidov** [comment]
pyamgcl uses the builtin (OpenMP) backend, and does not support CUDA or OpenCL. But it should be easy to modify the code to add the support if needed:

https://github.com/ddemidov/amgcl/blob/master/pyamgcl/pyamgcl.cpp

**Comment by CebFu** [comment]
Dear, Denis. Thank you for the feedback on my question. I have a large-scale linear system (approximately 1 million rows)  with multiple RHS, for which pyamgcl does not work efficiently. Only 25% of the CPU is utilized by the solver, and the solution is 3 times slower than Paradiso. I would appreciate it if you could provide cuda or MPI version of pyamgcl.

Best,
Ceb
