### ISSUE TITLE
unused parameter

### ISSUE THREAD

**Issue by zkoza** [ddemidov/amgcl#12]
Just a trivial comment. There's an unused parameter in skyline_lu.hpp:207 that generates a long, and hence nasty compiler warning:

[...]
../amgcl/amgcl/solver/skyline_lu.hpp:207:9: warning: unused parameter ‘prm’ [-Wunused-parameter]
         skyline_lu(const Matrix &A, const params &prm = params())

**Comment by ddemidov** [comment]
Thanks for reporting! This should be fixed in c237cbd.
