### ISSUE TITLE
MPI using nodes with multiple GPUs

### ISSUE THREAD

**Issue by davidherreroperez** [ddemidov/amgcl#121]
Hi Denis,

I'm running the example located at examples/mpi/mpi_amg.cpp in a host with five GPUs, and it seems all of them are used.

```
$mpirun -np 1 env OMP_NUM_THREADS=1 ./mpi_amg_vexcl_cl -n 256
World size: 1
1. GeForce GTX TITAN Black (NVIDIA CUDA)
2. GeForce GTX TITAN Z (NVIDIA CUDA)
3. GeForce GTX TITAN Z (NVIDIA CUDA)
4. GeForce GTX TITAN Z (NVIDIA CUDA)
5. GeForce GTX TITAN Z (NVIDIA CUDA)

Type:             BiCGStab
Unknowns:         16777216
Memory footprint: 896.00 M

Number of levels:    5
Operator complexity: 1.62
Grid complexity:     1.13

level     unknowns       nonzeros
---------------------------------
    0     16777216      117047296 (61.60%) [1]
    1      2029083       63746807 (33.55%) [1]
    2       118853        8809677 ( 4.64%) [1]
    3         5000         399400 ( 0.21%) [1]
    4          206          11272 ( 0.01%) [1]

Iterations: 14
Error:      9.2593e-09

[Profile:       33.924 s] (100.00%)
[ self:          1.846 s] (  5.44%)
[  assemble:     1.268 s] (  3.74%)
[  setup:       29.520 s] ( 87.02%)
[  solve:        1.290 s] (  3.80%)
```
Can I configure the device used by each mpi process related with the rank?

Thanks in advance!

**Comment by ddemidov** [comment]
The example [uses](https://github.com/ddemidov/amgcl/blob/1ed26b72e090d4cdacc1ac4f771f98fffa0f28d9/examples/mpi/mpi_amg.cpp#L273) `vex::Filter::Env` device filter, so you can use environment variables to select the device: https://vexcl.readthedocs.io/en/latest/initialize.html#common-filters.

For example, you could
```sh
export OCL_DEVICE=TITAN # to only select titans
export OCL_MAX_DEVICES=1 # to select just one
```

Also, you could modify the example to replace `vex::Filter::Env` with `vex::Filter::Exclusive(vex::Filter::Env && vex::Filter::Count(1))` to always select a single device unique across mpi processes on the node (you can still restrict the device to titans by exporting `OCL_DEVICE=Titan`).
