### ISSUE TITLE
switching AMG and using bicgstab alone

### ISSUE THREAD

**Issue by salahgaffar** [ddemidov/amgcl#123]
For my problem, AMG hurts my solution time when compared to bicgstab standalone, so how would you switch off the AMG cycles at the beginning and just use the bicgstab solver alone?

**Comment by ddemidov** [comment]
You could use the `dummy` preconditioner instead of `amg`:

https://github.com/ddemidov/amgcl/blob/master/amgcl/preconditioner/dummy.hpp

**Comment by salahgaffar** [comment]
Thank you, I will try that solution as soon as possible
.
