### ISSUE TITLE
Weird boost error with 1 MPI rank

### ISSUE THREAD

**Issue by DABH** [ddemidov/amgcl#129]
When doing a solve with AMGCL (MPI + VexCL/CUDA backend) with 1 MPI rank, I get a weird error from boost (seems to only happen when compiling in debug mode with e.g. `-O0 -g`):
```
myprog: /home/foo/boost_1_67_0/boost/range/iterator_range_core.hpp:390: boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::random_access_traversal_tag>::reference boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::random_access_traversal_tag>::operator[](boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::random_access_traversal_tag>::difference_type) const [with IteratorT = long int*; boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::random_access_traversal_tag>::reference = long int&; boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::random_access_traversal_tag>::difference_type = long int]: Assertion `static_cast<typename base_type::size_type>(at) < size()' failed.
```
The stack trace for this goes up to `amgcl/mpi/distributed_matrix.hpp` where AMGCL is trying to renumber and copy to backend the remote part of `A`.  However, for 1 MPI rank, there is no remote part of `A`; in particular it has zero columns, which ultimately causes the boost error.

I fixed this in my fork via https://github.com/DABH/amgcl/commit/b15d31fccc08419de955923eb1a058945ec75a94 -- let me know if you'd like a PR for this or if you have a better way to solve this issue.  With that commit, the boost error goes away, and all seems well (I get the same system solution with e.g. 1 vs. 2 MPI ranks).

**Comment by ddemidov** [comment]
Thank you for both the bug report and the solution. Yes, please open a PR (I've left a comment in the commit you referenced).

**Comment by DABH** [comment]
Thank you for the quick review and comments!  Here is a PR: https://github.com/ddemidov/amgcl/pull/130 .  Have a good weekend!
