### ISSUE TITLE
Reusing preconditioner

### ISSUE THREAD

**Issue by DABH** [ddemidov/amgcl#133]
Hi again,

Just a quick/basic question on usage / best practice.  (Did not find an exact answer in readthedocs or github issues.)

I have two types of problems I am solving with AMGCL:

1. `Ax = b` where `A` is always the same but `b` changes every timestep of my simulation
2. `Ax = b` where both `A` and `b` change each time

For case 2, is the best practice to just create a new `Solver` object every time I need to do a solve?  Or is it better to keep one `Solver` and update it with the new `A` somehow?

For case 1, if I keep the same `Solver` object around and just keep calling `std::tie(iters, error) = solve(b, x);` with different `b`s, does the preconditioner get rebuilt/recomputed each time, or is AMGCL smart enough to reuse the preconditioner it built the first time, and just do the solution phase? :)  My understanding is that AMGCL will reuse the preconditioner but just wanted to be sure.

Thanks in advance for your help!

**Comment by ddemidov** [comment]
Case 1: you can reuse the constructed preconditioner/solver with the different right-hand side vectors. That is the intended use case.

Case 2: in amgcl, there is no "fast-track" way to update an existing preconditioner for a slightly changed matrix, so you have to rebuild it for each matrix change. Another option is to keep the preconditioner for a number of time steps in hope it is still able to act as a decent preconditioner for the problem, and only send the updated matrix to the iterative solver (see [amgcl/make_solver.hpp](https://github.com/ddemidov/amgcl/blob/13532a40fdc83ba0a201dbc8473d0621a85cf917/amgcl/make_solver.hpp#L114-L133)). Something like this:
```cpp
auto solve = std::make_shared<amgcl::make_solver<...>>(A0, prm);

for(double t = 0; t < tmax; t+= dt) {
    A = assemble_fresh_matrix();

    // This will solve Ax=f with the current preconditioner:
    std::tie(iters, error) = (*solve)(A, f, x);

    if (iters > rebuild_limit) {
        // Too many iterations: time to update the preconditioner
        solve = std::make_shared<amgcl::make_solver<...>>(A, prm);
    }
}
```

**Comment by DABH** [comment]
Perfect, thank you so much for clarifying!
