### ISSUE TITLE
make

### ISSUE THREAD

**Issue by peteryim** [ddemidov/amgcl#134]
I have not been able to compile amgcl with make.  I cloned the repository with git to ubuntu 18.04.3.  I ran "cmake ." from the "~/amgcl/tests" directory and then ran "make test_solver_ns_builtin".   The make did not work.   The full error message is below.   This could easily be my lack of understanding of make/cmake but please let me know if there is an obvious fix.   I realize it is probably looking for a library file, but how is that library generated/found?

Scanning dependencies of target test_solver_ns_builtin
[ 50%] Building CXX object CMakeFiles/test_solver_ns_builtin.dir/test_solver_ns_builtin.o
[100%] Linking CXX executable test_solver_ns_builtin
/usr/bin/ld: cannot find -lamgcl
collect2: error: ld returned 1 exit status
CMakeFiles/test_solver_ns_builtin.dir/build.make:83: recipe for target 'test_solver_ns_builtin' failed
make[3]: *** [test_solver_ns_builtin] Error 1
CMakeFiles/Makefile2:89: recipe for target 'CMakeFiles/test_solver_ns_builtin.dir/all' failed
make[2]: *** [CMakeFiles/test_solver_ns_builtin.dir/all] Error 2
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/test_solver_ns_builtin.dir/rule' failed
make[1]: *** [CMakeFiles/test_solver_ns_builtin.dir/rule] Error 2
Makefile:118: recipe for target 'test_solver_ns_builtin' failed
make: *** [test_solver_ns_builtin] Error 2

**Comment by ddemidov** [comment]
You can not start with a subfolder of a cmake project, you need to start the configuration at the top level. The following should work:
```sh
mkdir build
cd build
cmake -DAMGCL_BUILD_TESTS=ON -DAMGCL_BUILD_EXAMPLES=ON ..
make
```

**Comment by peteryim** [comment]
Thanks very much.   That worked.

Peter
