### ISSUE TITLE
Coarsening using near null space vectors

### ISSUE THREAD

**Issue by davidherreroperez** [ddemidov/amgcl#135]
Hi Denis,

I'm trying to use rigid body modes in the coarsening with the example [solve.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/solver.cpp).
The problem is that I have a segmentation fault running this [problem](https://www.dropbox.com/sh/0l8ydjsbhl0pu0y/AACinO5PCLH2vTTRzf7ZubF-a?dl=0) with one null-space vector
```
./solver -A A.mtx -f b.mtx -N N.mtx -p solver.type=cg solver.tol=1e-8 solver.maxiter=5000 precond.relax.type=ilu0

Segmentation fault (core dumped)
```
The problem is running obviating the rigid body mode
```
./solver -A A.mtx -f b.mtx -p solver.type=cg solver.tol=1e-8 solver.maxiter=5000 precond.relax.type=ilu0

Solver
======
Type:             CG
Unknowns:         9506
Memory footprint: 297.06 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.02
Grid complexity:     1.03
Memory footprint:    6.49 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         9506         167620      6.40 M (98.41%)
    1          325           2701     98.80 K ( 1.59%)

Iterations: 144
Error:      7.67667e-09

[Profile:       0.313 s] (100.00%)
[ self:         0.000 s] (  0.11%)
[  reading:     0.181 s] ( 57.90%)
[  setup:       0.008 s] (  2.52%)
[  solve:       0.123 s] ( 39.48%)
```
I would appreciate if you can check that the format of N.mtx is right and also the procedure.
Thanks in advantage.

**Comment by ddemidov** [comment]
Thank you for raising this issue, there was a bug in `tentative_prolongation.hpp` ([introduced as far as two year ago!](https://github.com/ddemidov/amgcl/commit/dc9c5bc1c232fe333594ceed9e9cd4f4ad96416f#diff-1d0028039bf2eb7ebd0b8e0176891970R134)), fixed by a0c18b6e3565c02b26706267af07c572816a5936.

Regarding the format of N.mtx, it is formally correct, but in the case of two dimensions (your matrix looks like 2D), it should contain three vectors, not one. I always look up the definition of [`MatNullSpaceCreateRigidBody`](https://github.com/petsc/petsc/blob/6dd80bdec2980634f66887e5e77bea5a1e70dedf/src/mat/interface/matnull.c#L119-L126) in PETSc when I want to remember how to form the rigid body modes for 2 or 3 dimensions.

**Comment by davidherreroperez** [comment]
Thank you for solving the bug and also for your suggestions.
I am not sure if my [2D elasticity problem](https://www.dropbox.com/sh/0l8ydjsbhl0pu0y/AACinO5PCLH2vTTRzf7ZubF-a?dl=0) is configured properly in amgcl, when I run the problem without null-space vectors
```
./solver -A A.mtx -f b.mtx -p solver.type=cg solver.tol=1e-8 solver.maxiter=5000 precond.coarsening.type=aggregation precond.relax.type=ilu0
Solver
======
Type:             CG
Unknowns:         37442
Memory footprint: 1.14 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.02
Grid complexity:     1.03
Memory footprint:    24.54 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        37442         667012     23.89 M (98.44%)
    1         1225          10537    661.13 K ( 1.56%)

Iterations: 275
Error:      8.29946e-09

[Profile:       1.496 s] (100.00%)
[  reading:     0.693 s] ( 46.33%)
[  setup:       0.033 s] (  2.19%)
[  solve:       0.770 s] ( 51.44%)
```
If I introduce one null-space vector (the rotational one), the iterations decrease a little but the coarsening is not modified
```
./solver -A ../mtx/null_space/A.mtx -f ../mtx/null_space/b.mtx -N ../mtx/null_space/Nr.mtx -p solver.type=cg solver.tol=1e-8 solver.maxiter=5000 precond.coarsening.type=aggregation precond.relax.type=ilu0
Solver
======
Type:             CG
Unknowns:         37442
Memory footprint: 1.14 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.02
Grid complexity:     1.03
Memory footprint:    24.54 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        37442         667012     23.89 M (98.44%)
    1         1225          10537    661.13 K ( 1.56%)

Iterations: 243
Error:      9.36091e-09

[Profile:       1.895 s] (100.00%)
[  reading:     0.727 s] ( 38.35%)
[  setup:       0.052 s] (  2.74%)
[  solve:       1.116 s] ( 58.89%)
```
If I introduce the three rigid body mode (RBM) vectors the coarsening is modified but the number of iterations increase
```
./solver -A ../mtx/null_space/A.mtx -f ../mtx/null_space/b.mtx -N ../mtx/null_space/N.mtx -p solver.type=cg solver.tol=1e-8 solver.maxiter=5000 precond.coarsening.type=aggregation precond.relax.type=ilu0
Solver
======
Type:             CG
Unknowns:         37442
Memory footprint: 1.14 M

Preconditioner
==============
Number of levels:    3
Operator complexity: 1.15
Grid complexity:     1.12
Memory footprint:    29.67 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        37442         667012     26.18 M (86.78%)
    1         3675          94833      3.32 M (12.34%)
    2          645           6813    177.19 K ( 0.89%)

Iterations: 425
Error:      8.61081e-09

[Profile:       2.494 s] (100.00%)
[  reading:     0.803 s] ( 32.20%)
[  setup:       0.045 s] (  1.81%)
[  solve:       1.645 s] ( 65.98%)
```
I guess the RBMs are not calculated properly, i'll keep trying it ... Thank you again.

**Comment by ddemidov** [comment]
Can you upload the vector with coordinates of your grid points?

**Comment by ddemidov** [comment]
In fact, it looks like the vector N.mtx you provided initially, does contain the coordinates. With the following python script I am able to obtain three rigid body modes that seem to work with your problem:

```py
from scipy.io import *
from numpy import *

N = mmread('N.mtx')

# Guessing the signs of the coordinates
# (rotational vector from petsc uses opposite signs):
x = -N[1::2].flatten()
y =  N[0::2].flatten()

n = N.shape[0]

N = zeros((n,3))

# First two vectors:
N[0::2,0] = 1 / sqrt(n)
N[1::2,1] = 1 / sqrt(n)

# Third, rotational vector:
N[0::2,2] = -y
N[1::2,2] =  x

mmwrite('N3.mtx', N)

# Using just the first two vectors
# should be equivalent to block-wise coarsening:
mmwrite('N2.mtx', N[:,:2])
```

```
./solver -A A.mtx -f b.mtx -N N3.mtx
Solver
======
Type:             BiCGStab
Unknowns:         9506
Memory footprint: 519.86 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.15
Grid complexity:     1.10
Memory footprint:    5.71 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         9506         167620      4.93 M (87.33%)
    1          975          24309    800.16 K (12.67%)

Iterations: 21
Error:      9.71379e-09

[Profile:       0.407 s] (100.00%)
[ self:         0.000 s] (  0.12%)
[  reading:     0.180 s] ( 44.24%)
[  setup:       0.048 s] ( 11.82%)
[  solve:       0.178 s] ( 43.82%)
```

Using just the first two vectors (without rotations):
```
./solver -A A.mtx -f b.mtx -N N2.mtx
Solver
======
Type:             BiCGStab
Unknowns:         9506
Memory footprint: 519.86 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.06
Grid complexity:     1.07
Memory footprint:    4.64 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         9506         167620      4.29 M (93.94%)
    1          650          10804    360.71 K ( 6.06%)

Iterations: 49
Error:      8.07463e-09

[Profile:       0.529 s] (100.00%)
[  reading:     0.171 s] ( 32.32%)
[  setup:       0.031 s] (  5.90%)
[  solve:       0.327 s] ( 61.70%)
```

Using block-wise coarsening is indeed equivalent:
```
solver -A A.mtx -f b.mtx -p precond.coarsening.aggr.block_size=2
Solver
======
Type:             BiCGStab
Unknowns:         9506
Memory footprint: 519.86 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.06
Grid complexity:     1.07
Memory footprint:    4.63 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         9506         167620      4.28 M (93.94%)
    1          650          10804    360.71 K ( 6.06%)

Iterations: 49
Error:      7.53046e-09

[Profile:       0.513 s] (100.00%)
[ self:         0.001 s] (  0.12%)
[  reading:     0.159 s] ( 31.00%)
[  setup:       0.024 s] (  4.62%)
[  solve:       0.330 s] ( 64.26%)
```

**Comment by davidherreroperez** [comment]
Thank you for the script! The N.mtx file was not properly generated in my code because I was not storing correctly more than one RBM vector in the std::vector null of [solve.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/solver.cpp) ... The performance using RBMs increases significantly.

One last question: Is this functionality supported by the MPI implementation?

**Comment by ddemidov** [comment]
> Is this functionality supported by the MPI implementation?

Not yet (#82). I'll move this up my priority list, but for now the best option for `mpi::amg` is to use either block-wise coarsening or block values.

**Comment by ddemidov** [comment]
85a79bbd3c3c8cf22689ee21f5723dc73e197c0d introduces `amgcl::coarsening::rigid_body_modes(ndim, coo)` function that may be used to create near null-space vectors from coordinates. A usage example may be found in examples/solver.cpp:

https://github.com/ddemidov/amgcl/blob/85a79bbd3c3c8cf22689ee21f5723dc73e197c0d/examples/solver.cpp#L537-L552

**Comment by ddemidov** [comment]
@davidherreroperez , do you mind if I use your system and the coordinates in a tutorial on using near-null space vectors and/or coordinates to improve the coarsening quality in amgcl? I tried to find an elasticity system that would also provide coordinates in the SuiteSparse collection but to no avail.

**Comment by davidherreroperez** [comment]
> @davidherreroperez , do you mind if I use your system and the coordinates in a tutorial on using near-null space vectors and/or coordinates to improve the coarsening quality in amgcl? I tried to find an elasticity system that would also provide coordinates in the SuiteSparse collection but to no avail.

@ddemidov , feel free to use it.

You also can find some examples here

https://www.dropbox.com/sh/0l1scycceejnz9x/AABrfJS6Wso-aZNOr64CYt9ya?dl=0

Please note that I perform some uniform refinements to increase the mesh resolution.

**Comment by ddemidov** [comment]
Thanks! The examples look nice, but there are no coordinate files, so I can not really use them for the tutorial (and the .msh file does not seem to correspond to the matrix file, probably because of the mesh refinement you mentioned).

**Comment by davidherreroperez** [comment]
> Thanks! The examples look nice, but there are no coordinate files, so I can not really use them for the tutorial (and the .msh file does not seem to correspond to the matrix file, probably because of the mesh refinement you mentioned).

I have modified the examples to do not make any mesh refinement, so the coordinates of .msh should correspond to the matrix file now.

**Comment by ddemidov** [comment]
Is it very hard to do the other way around (just for the 3D problem)? Keep the refinement, but somehow save the updated coordinates? The larger problem demonstrates the speed up from using the nullspace better. The benefits are already apparent from the nullspace vectors found by iterating the Ax=0 system, but the rigid body modes obtained from the coordinates should result in a higher quality nullspace and be easier to obtain.

**The refined 'connecting_rod' problem, no nullspace data**:
```
$ solver -A A.mtx -f b.mtx solver.type=cg solver.maxiter=10000
Solver
======
Type:             CG
Unknowns:         31965
Memory footprint: 998.91 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.07
Grid complexity:     1.05
Memory footprint:    28.29 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        31965        1221795     24.11 M (93.20%)
    1         1506          89150      4.19 M ( 6.80%)

Iterations: 502
Error:      8.64426e-09

[Profile:       3.598 s] (100.00%)
[  reading:     0.833 s] ( 23.14%)
[  setup:       0.071 s] (  1.98%)
[  solve:       2.694 s] ( 74.87%)
```

**Same problem, using the computed nullspace vectors**:
```
solver -A A.mtx -f b.mtx solver.type=cg solver.maxiter=10000 precond.coarsening.aggr.eps_strong=0 -N N6.mtx
Solver
======
Type:             CG
Unknowns:         31965
Memory footprint: 998.91 K

Preconditioner
==============
Number of levels:    3
Operator complexity: 1.44
Grid complexity:     1.11
Memory footprint:    49.01 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        31965        1221795     39.23 M (69.59%)
    1         3330         529380      9.73 M (30.15%)
    2           84           4608     47.54 K ( 0.26%)

Iterations: 62
Error:      8.63083e-09

[Profile:       1.512 s] (100.00%)
[  reading:     0.935 s] ( 61.85%)
[  setup:       0.104 s] (  6.87%)
[  solve:       0.473 s] ( 31.26%)
```

**Comment by ddemidov** [comment]
The non-refined problem could work as well, if saving the refined coordinates is too much work:

**No nullspace info**:
```
solver -A A.mtx -f b.mtx solver.type=cg solver.maxiter=5000
Solver
======
Type:             CG
Unknowns:         5175
Memory footprint: 161.72 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.06
Grid complexity:     1.05
Memory footprint:    3.81 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         5175         176241      3.53 M (94.63%)
    1          266          10006    287.83 K ( 5.37%)

Iterations: 250
Error:      8.81744e-09

[Profile:       0.198 s] (100.00%)
[ self:         0.001 s] (  0.39%)
[  reading:     0.123 s] ( 62.00%)
[  setup:       0.005 s] (  2.35%)
[  solve:       0.070 s] ( 35.26%)
```

**Nullspace computed from Ax=0**:
```
solver -A A.mtx -f b.mtx solver.type=cg solver.maxiter=5000 precond.coarsening.aggr.eps_strong=0 -N N6.mtx
Solver
======
Type:             CG
Unknowns:         5175
Memory footprint: 161.72 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.43
Grid complexity:     1.13
Memory footprint:    6.83 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         5175         176241      5.70 M (69.73%)
    1          690          76500      1.13 M (30.27%)

Iterations: 40
Error:      9.40662e-09

[Profile:       0.176 s] (100.00%)
[ self:         0.000 s] (  0.20%)
[  reading:     0.139 s] ( 78.89%)
[  setup:       0.018 s] ( 10.14%)
[  solve:       0.019 s] ( 10.77%)
```

**Nullspace computed from coordinates**:
```
solver -A A.mtx -f b.mtx solver.type=cg solver.maxiter=5000 precond.coarsening.aggr.eps_strong=0 -C C.mtx
Solver
======
Type:             CG
Unknowns:         5175
Memory footprint: 161.72 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.43
Grid complexity:     1.13
Memory footprint:    6.83 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         5175         176241      5.70 M (69.73%)
    1          690          76500      1.13 M (30.27%)

Iterations: 25
Error:      8.10861e-09

[Profile:       0.157 s] (100.00%)
[ self:         0.001 s] (  0.43%)
[  reading:     0.123 s] ( 78.67%)
[  setup:       0.019 s] ( 11.99%)
[  solve:       0.014 s] (  8.91%)
```

**Comment by davidherreroperez** [comment]
You can find the 3D example with a higher resolution in the Dropbox link.

**Comment by ddemidov** [comment]
Great, thank you! How do you wish to be cited in the tutorial?

**Comment by davidherreroperez** [comment]
That would be great. Let me know to contribute!

**Comment by ddemidov** [comment]
I have uploaded the dataset to https://doi.org/10.5281/zenodo.4299865 (to have a more permanent place than dropbox). I hope you don't mind. The new tutorial is published here: https://amgcl.readthedocs.io/en/latest/Nullspace.html. Please see if you have any comments.

Thanks again for the dataset!

**Comment by ddemidov** [comment]
> Is this functionality supported by the MPI implementation?

@davidherreroperez, it is supported now. See https://amgcl.readthedocs.io/en/latest/NullspaceMPI.html

**Comment by davidherreroperez** [comment]
Thanks @ddemidov !

Is there any reason to define the solver parameters in a different way using serial and MPI implementations? I mean

+ Serial implementation:
prm.precond.coarsening.nullspace.cols
prm.precond.coarsening.nullspace.B

+ MPI implementation:
prm.precond.coarsening.aggr.nullspace.cols
prm.precond.coarsening.aggr.nullspace.B

**Comment by ddemidov** [comment]
I don't like this discrepancy either, but implementing the tentative prolongation (the consumer of the nullspace parameters) as part of aggregation makes more sense in the distributed case. In fact, it probably makes more sense in the serial case as well, but changing that would require a bit of refactoring and, more importantly, would break the existing user code.

It should be easy to move the nullspace parameters up a level in the distributed case though, to make it compatible with the serial case. Do you think it should be done?

**Comment by davidherreroperez** [comment]
I think that it is a good idea to maintain the same solver configuration in both cases, but if this modification means a lot of work, it is a minor discrepancy that the user can take into account.
