### ISSUE TITLE
Mixed precision using block values

### ISSUE THREAD

**Issue by davidherreroperez** [ddemidov/amgcl#137]
Hi @ddemidov

Is it possible to jointly use mixed precision and block values? When I modify this code
https://github.com/ddemidov/amgcl/blob/aa0bbeab7f1dc7396c08a0bebfda1526e6392e75/examples/solver.cpp#L82-L85
by this
```
typedef amgcl::static_matrix<float, B, B> value_type_f;
typedef amgcl::static_matrix<float, B, 1> rhs_type_f;
typedef amgcl::backend::builtin<value_type_f> BBackend_f;

typedef amgcl::make_solver<
  amgcl::runtime::preconditioner<BBackend_f>,
  amgcl::runtime::solver::wrapper<BBackend>
  > Solver;
```
I get error conversions with the casting of block types
```
~/include/amgcl/solver/skyline_lu.hpp:185:26: error: conversion from ‘const amgcl::static_matrix<double, 2, 1>’ to non-scalar type ‘amgcl::solver::skyline_lu<amgcl::static_matrix<float, 2, 2>, amgcl::reorder::cuthill_mckee<false> >::rhs_type {aka amgcl::static_matrix<float, 2, 1>}’ requested
```
Do you know of some way to solve this? Thanks in advance.

**Comment by ddemidov** [comment]
Should be fixed by dc1ab1c .

**Comment by ddemidov** [comment]
Sorry, dc1ab1c seems to break [tests on Visual Studio](https://ci.appveyor.com/project/ddemidov/amgcl/builds/29694201). Also, I did not like that `static_matrix` is not POD anymore with that. So I reverted that. c1455d5771015ba9bcfc426199ceda79ac3a7e04 is a new attempt to fix this issue.

**Comment by davidherreroperez** [comment]
Hi @ddemidov

Thank you for solving the previous problem. I'm trying to combine single-precision preconditioner with a double-precision Krylov solver using block values. The problem is now creating the coefficient matrix Af with single-precision as follows 
```
typedef amgcl::static_matrix<float, B, B> value_type_f;
typedef amgcl::backend::builtin<value_type_f> BBackend_f;

typedef amgcl::make_solver<
  amgcl::runtime::preconditioner<BBackend_f>,
  amgcl::runtime::solver::wrapper<BBackend>
  > Solver;

std::vector<float> val_f(val.begin(), val.end());
auto Af = amgcl::adapter::block_matrix<value_type_f>(std::tie(rows, ptr, col, val_f));
size_t nrowsf = Af.rows();
```
I get a segmentation fault or an incorrect number of rows of Af.

**Comment by ddemidov** [comment]
Can you provide a minimal reputable example? Also, you should be able to just use `val` directly, no need to copy it into `val_f`.

**Comment by ddemidov** [comment]
One note: for the block_matrix adapter to work correctly, the rows in your matrix should be sorted by column numbers.

**Comment by davidherreroperez** [comment]
> Can you provide a minimal reproduceable example? Also, you should be able to just use `val` directly, no need to copy it into `val_f`.

Thank you @ddemidov, you are right I can use `val` directly. I have taken a look to the example  [mixed_precision.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/mixed_precision.cpp) and the single-precision preconditioner with double-precision Krylov solver using block values is working fine. Thanks again!

**Comment by davidherreroperez** [comment]
One last point,
A similar issue using mixed precision and block values with the vexcl implementation. For example, it replacing
https://github.com/ddemidov/amgcl/blob/332a9f2ca967e4431368996b3a708c1828693ae6/examples/solver.cpp#L155-L158
by
```
typedef amgcl::static_matrix<float, B, B> value_type_f;
typedef amgcl::backend::vexcl<value_type_f> BBackend_f;

typedef amgcl::make_solver<
  amgcl::runtime::preconditioner<BBackend_f>,
  amgcl::runtime::solver::wrapper<BBackend>
> Solver;
```
I get compilation error related to the operations with float block matrices. I would appreciate it if you indicate me of some way to solve it. Thanks in advance.

**Comment by ddemidov** [comment]
a19b6cf seems to deal with mixed precision and block values in vexcl backend. There is one change you need to make in your code (on in examples/solver.cpp if you use that to test this):

You need to add 

```cpp
    vex::scoped_program_header header_f(ctx,
            amgcl::backend::vexcl_static_matrix_declaration<float,B>());
```

next to

https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/examples/solver.cpp#L167-L168

so that VexCL knows about both double and single precision `static_matrix` types.

**Comment by davidherreroperez** [comment]
Hi @ddemidov

Can I create a matrix with block values in vexcl backend with the BBackend of 

https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/examples/solver.cpp#L151-L153

in a similar way that

https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/examples/mixed_precision.cpp#L60

to use it in the solving as

https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/examples/mixed_precision.cpp#L80

Thanks in advance

**Comment by ddemidov** [comment]
This should work:
```cpp
auto Ad = BBackend::copy_matrix(
  std::make_shared<amgcl::backend::crs<value_type>>(
    amgcl::adapter::block_matrix<value_type>(std::tie(rows, ptr, col, val))),
  bprm
);
...
std::tie(iters, error) = solve(*Ad, f, x);
```

**Comment by davidherreroperez** [comment]
> This should work:
> 
> ```c++
> auto Ad = BBackend::copy_matrix(
>   std::make_shared<amgcl::backend::crs<value_type>>(
>     amgcl::adapter::block_matrix<value_type>(std::tie(rows, ptr, col, val))),
>   bprm
> );
> ...
> std::tie(iters, error) = solve(*Ad, f, x);
> ```

I'm trying to do something similar with the [mpi_amg.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/mpi/mpi_amg.cpp) example modifying the line https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/examples/mpi/mpi_amg.cpp#L403
by
```
auto Ad = solve->system_matrix();
std::tie(iters, error) = (*solve)(Ad, rhs, x);
```
successfully, but I'm not able to create the distributed matrix Ad instead of using the one provided by solve. My attempt is as follows
```
auto Ad = std::make_shared<amgcl::mpi::distributed_matrix<Backend>>(comm, std::tie(chunk, ptr, col, val));
```
with several compilation errors. Please, can you indicate to me if it is possible creating the Ad matrix directly? This is for using mixed precision with mpi computing. Thanks in advance.

**Comment by ddemidov** [comment]
Ah, sorry, I did not realize you were talking about the distributed case. Then [this](https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/amgcl/mpi/distributed_matrix.hpp#L325-L329) should work:

```cpp
amgcl::mpi::distributed_matrix<Backend> A(MPI_COMM_WORLD, std::tie(chunk, ptr, col, val));
A.move_to_backend();
std::tie(iters, error) = solve(A, rhs, x);
```

**Comment by davidherreroperez** [comment]
> Ah, sorry, I did not realize you were talking about the distributed case. Then [this](https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/amgcl/mpi/distributed_matrix.hpp#L325-L329) should work:

Thank you @ddemidov, the serial case of mixed precision using block values is working fine for builtin and vexcl versions, but the same issue of https://github.com/ddemidov/amgcl/issues/137#issue-541186822 happens with the distributed case. Replacing

https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/examples/mpi/mpi_amg.cpp#L247-L261

with

```
typedef amgcl::static_matrix<double, B, B> val_type; 
typedef amgcl::static_matrix<double, B, 1> rhs_type; 

typedef amgcl::static_matrix<float, B, B> val_type_f; 

#if defined(SOLVER_BACKEND_BUILTIN) 
  typedef amgcl::backend::builtin<val_type> Backend;
  typedef amgcl::backend::builtin<val_type_f> Backend_f; 
#elif defined(SOLVER_BACKEND_VEXCL) 
  typedef amgcl::backend::vexcl<val_type> Backend;
  typedef amgcl::backend::vexcl<val_type_f> Backend_f; 
#endif   

typedef 
  amgcl::mpi::make_solver< 
    amgcl::runtime::mpi::preconditioner<Backend_f>, 
    amgcl::runtime::solver::wrapper 
    > Solver; 
```
I get several error related to the data type.

**Comment by ddemidov** [comment]
So apparently at the moment there is no way to use mixed precision with mpi::make_solver. The iterative solver there simply inherits the backend of the preconditioner:

https://github.com/ddemidov/amgcl/blob/a19b6cf8dcd5c4e05a6caaf7c51ed618f12dc40e/amgcl/mpi/make_solver.hpp#L47-L51

I don't think it will be too difficult, but fixing this may take some time (and will break existing code).

**Comment by davidherreroperez** [comment]
Sorry @ddemidov, I am not using mpi::make_solver but I tried to reproduce the error conversions in my code similar to https://github.com/ddemidov/amgcl/issues/137#issue-541186822 doing small modifications of [mpi_amg.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/mpi/mpi_amg.cpp) without much success.

Modifying the solve_block function of [mpi_amg.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/mpi/mpi_amg.cpp) I use amgcl with block values in a similar way that in my code as follows [mpi_amg.cpp.txt](https://github.com/ddemidov/amgcl/files/4004887/mpi_amg.cpp.txt) (defining preconditioner and solver separately), and when I try to use mixed precision in ([mpi_amg_mp.cpp.txt](https://github.com/ddemidov/amgcl/files/4004900/mpi_amg_mp.cpp.txt), lines 349 and 366) I get conversion errors as
```
~/amgcl/mpi/distributed_matrix.hpp:375:32: error: conversion from ‘amgcl::adapter::block_matrix_adapter<std::tuple<long int&, const std::vector<long int, std::allocator<long int> >&, const std::vector<long int, std::allocator<long int> >&, const std::vector<double, std::allocator<double> >&>, amgcl::static_matrix<double, 2, 2> >::row_iterator::val_type {aka amgcl::static_matrix<double, 2, 2>}’ to non-scalar type ‘amgcl::mpi::distributed_matrix<amgcl::backend::builtin<amgcl::static_matrix<float, 2, 2> > >::value_type {aka amgcl::static_matrix<float, 2, 2>}’ requested
                     value_type v = a.value();
```
and also undefined calls for data gathering in the vexcl version
```
~/amgcl/mpi/distributed_matrix.hpp:233:26: error: no match for call to ‘(std::__shared_ptr_access<amgcl::backend::vexcl<amgcl::static_matrix<float, 2, 2>, amgcl::solver::vexcl_skyline_lu<amgcl::static_matrix<float, 2, 2> > >::gather, (__gnu_cxx::_Lock_policy)2, false, false>::element_type {aka amgcl::backend::vexcl<amgcl::static_matrix<float, 2, 2>, amgcl::solver::vexcl_skyline_lu<amgcl::static_matrix<float, 2, 2> > >::gather}) (const vex::vector<amgcl::static_matrix<double, 2, 1> >&, std::vector<amgcl::static_matrix<float, 2, 1>, std::allocator<amgcl::static_matrix<float, 2, 1> > >&)’
                 (*gather)(x, send.val);
```
I do not know the required effort for solving this issue and if this is the right way of using amgcl. So please close this issue if you consider appropriate, and of course, thank you for the previous commits!

**Comment by ddemidov** [comment]
I modified your `mpi_amg_mp.cpp` to get this: [mpi_amg_mp.cpp.txt](https://gist.github.com/ddemidov/6a1e331c8fa6b19fd4d1b6785839813d). It does compile and seems to work for me (note that it is compiled against the current master which has some api breaking changes).

The important thing is you need to set the correct (single precision) value type with block matrix adapter that you are going to use with single precision preconditioner: [line 336](https://gist.github.com/ddemidov/6a1e331c8fa6b19fd4d1b6785839813d#file-mpi_amg_mp-cpp-L336).

**Comment by davidherreroperez** [comment]
Thank you @ddemidov for the corrections, it is great to see that the builtin distributed version using block-values and mixed-precision is working fine with the master code.
Just to mention that the undefined calls still persist in the vexcl version 
```
~/amgcl/mpi/distributed_matrix.hpp:233:26: error: no match for call to ‘(std::__shared_ptr_access<amgcl::backend::vexcl<amgcl::static_matrix<float, 2, 2>, amgcl::solver::vexcl_skyline_lu<amgcl::static_matrix<float, 2, 2> > >::gather, (__gnu_cxx::_Lock_policy)2, false, false>::element_type {aka amgcl::backend::vexcl<amgcl::static_matrix<float, 2, 2>, amgcl::solver::vexcl_skyline_lu<amgcl::static_matrix<float, 2, 2> > >::gather}) (const vex::vector<amgcl::static_matrix<double, 2, 1> >&, std::vector<amgcl::static_matrix<float, 2, 1>, std::allocator<amgcl::static_matrix<float, 2, 1> > >&)’
                 (*gather)(x, send.val);
```

**Comment by ddemidov** [comment]
Sorry about that, forgot to test the vexcl compilation path. 8700eb76d83bdc5fee1cfd3d74da9504b167ad74 should work with vexcl, but you will also need ddemidov/vexcl@6ff7e175329817711d89819fd00de797e6a5de59.

**Comment by davidherreroperez** [comment]
Thank you @ddemidov! Mixed precision is also working in the distributed vexcl version. Please close this issue if you consider it appropriate.
