### ISSUE TITLE
Is there any example how to use METIS library to partition and reorder sparse matrices?

### ISSUE THREAD

**Issue by Amr-Emad994** [ddemidov/amgcl#138]

**Comment by ddemidov** [comment]
There should be some examples in the METIS library documentation: http://glaros.dtc.umn.edu/gkhome/metis/metis/download
(there is a link to the documentation pdf at the bottom of that page).

AMGCL provides wrappers for [ParMETIS](http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview) and [PTSCOTCH](https://www.labri.fr/perso/pelegrin/scotch/) in [`amgcl/mpi/partition`](https://github.com/ddemidov/amgcl/tree/master/amgcl/mpi/partition). Here is an example of how to use those:

https://github.com/ddemidov/amgcl/blob/332a9f2ca967e4431368996b3a708c1828693ae6/examples/mpi/mpi_amg.cpp#L188-L231

**Comment by Amr-Emad994** [comment]
> There should be some examples in the METIS library documentation: http://glaros.dtc.umn.edu/gkhome/metis/metis/download
> (there is a link to the documentation pdf at the bottom of that page).
> 
> AMGCL provides wrappers for [ParMETIS](http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview) and [PTSCOTCH](https://www.labri.fr/perso/pelegrin/scotch/) in [`amgcl/mpi/partition`](https://github.com/ddemidov/amgcl/tree/master/amgcl/mpi/partition). Here is an example of how to use those:
> 
> https://github.com/ddemidov/amgcl/blob/332a9f2ca967e4431368996b3a708c1828693ae6/examples/mpi/mpi_amg.cpp#L188-L231

Ok. For example if

**Comment by Amr-Emad994** [comment]
Is there any example how to use METIS library to partition and reorder sparse matrices?

**Comment by ddemidov** [comment]
See https://amgcl.readthedocs.io/en/latest/tutorial.html
