### ISSUE TITLE
Blockwise backended MGPCG (Gauss-Seidel smoothed) returns nan residual

### ISSUE THREAD

**Issue by liminchen** [ddemidov/amgcl#142]
I'm solving dynamic time stepping with barrier energies and contact on FEM, for each Newton iteration I solved the linear system with SPD system matrix using AMGCL. However in a timestep I got nan residual from AMGCL.
I was able to construct the multigrid, but right after the first CG iteration it returns nan:
```
Number of levels:    2
Operator complexity: 1.48
Grid complexity:     1.11
Memory footprint:    30.96 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         8111          57697     17.58 M (67.78%)
    1          930          27423     13.38 M (32.22%)

Iterations: 1
Error:      nan
```
I'm using the latest commit. The settings are
```
typedef amgcl::static_matrix<double, DIM, DIM> value_type;
    typedef amgcl::static_matrix<double, DIM, 1> rhs_type;
    typedef amgcl::backend::builtin<value_type> BBackend;
    using Solver = amgcl::make_solver<
        amgcl::amg<
            BBackend,
            amgcl::coarsening::smoothed_aggregation,
            amgcl::relaxation::gauss_seidel>,
        amgcl::solver::cg<BBackend>>;
```
for AMG construction I use
```
Solver::params prm;
    prm.solver.tol = 1e-3; // relative
    prm.solver.maxiter = 10;
    prm.precond.coarsening.aggr.eps_strong = 0.0;
    auto A = amgcl::adapter::block_matrix<value_type>(std::tie(Base::numRows, _ia, _ja, _a));
    std::cout << A.rows() << " " << A.cols() << std::endl; //NOTE: [a wierd bug] must keep this line as it is
    solver = new Solver(A, prm);
```
for the solve I use
```
    size_t iters;
    double resid;
    rhs_type const* fptr = reinterpret_cast<rhs_type const*>(rhs.data());
    rhs_type* xptr = reinterpret_cast<rhs_type*>(result.data());
    amgcl::backend::numa_vector<rhs_type> F(fptr, fptr + rhs.size() / DIM);
    amgcl::backend::numa_vector<rhs_type> X(xptr, xptr + result.size() / DIM);

    std::tie(iters, resid) = (*solver)(F, X);
    std::cout << "Iterations: " << iters << std::endl
              << "Error:      " << resid << std::endl;
    if (resid != resid) {
        Base::write("Mnan", rhs);
        exit(-1);
    }

    std::copy(X.data(), X.data() + X.size(), xptr);
```
I've attached my matrix and rhs saved in AMGCL format. As a double check I successfully used CHOLMOD to solve this system. It would be very nice if you could help us understand what could be the issue there. Basically we are testing on solving our problem with direct solver v.s. MGPCG, and are thinking about whether it's a good idea to develop a customized multigrid that can take advantage of the geometric information of the problem.
Looking forward to your reply~!
[linsys.zip](https://github.com/ddemidov/amgcl/files/4257458/linsys.zip)

**Comment by ddemidov** [comment]
What is `DIM` in your case? It seems your are using `DIM=3`, but it does not look like the system has block structure. Keep in mind that the unknowns have to ordered by grid nodes (e.g. `vx vy vz ...  vx vy vz` as opposed to `vx vx vx ... vy vy vy ... vz vz vz ...`).

Also, it looks like you only provide the upper diagonal of the matrix (AMGCL needs a complete matrix):

![Figure_1](https://user-images.githubusercontent.com/270503/75412005-34f61200-5932-11ea-84a2-bc52b4905d9a.png)

Anyway, I can not reproduce the error with your matrix (I am using scalar value type):
```
solver -A M -f M_rhs solver.type=cg precond.relax.type=gauss_seidel precond.coarsening.aggr.eps_strong=0
Solver
======
Type:             CG
Unknowns:         24333
Memory footprint: 760.41 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.04
Grid complexity:     1.03
Memory footprint:    27.55 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        24333         494940     26.67 M (96.01%)
    1          645          20548    907.29 K ( 3.99%)

Iterations: 1
Error:      2.54931e-16

[Profile:       0.415 s] (100.00%)
[ self:         0.001 s] (  0.13%)
[  reading:     0.378 s] ( 90.94%)
[  setup:       0.032 s] (  7.77%)
[  solve:       0.005 s] (  1.17%)
```

**Comment by ddemidov** [comment]
Correction: it does seem that the matrix has block structure. Still, you need to provide the full matrix to amgcl. By changing the header line of your `M` file to look like (changed `generic` to `symmetric`, which makes amgcl file reader to restore the other half of the matrix):
```
%%MatrixMarket matrix coordinate real symmetric
```
I am getting no NaNs with your settings:
```
./solver -A problems/issue-142/M -f problems/issue-142/M_rhs -b3 -p solver.type=cg precond.relax.type=gauss_seidel precond.coarsening.aggr.eps_strong=0
Solver
======
Type:             CG
Unknowns:         8111
Memory footprint: 760.41 K

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.19
Grid complexity:     1.06
Memory footprint:    34.46 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         8111         107283     30.01 M (84.30%)
    1          453          19987      4.45 M (15.70%)

Iterations: 100
Error:      1.00323

[Profile:       1.189 s] (100.00%)
[  reading:     0.638 s] ( 53.70%)
[  setup:       0.076 s] (  6.39%)
[  solve:       0.474 s] ( 39.86%)
```

However, the system does not converge. Switching from CG to LGMRES iterative solver fixes the issue (also, `eps_strong=0` setting is counterproductive here):
```
./solver -A problems/issue-142/M -f problems/issue-142/M_rhs -b3 -p solver.type=lgmres precond.relax.type=gauss_seidel
Solver
======
Type:             LGMRES(30,3)
Unknowns:         8111
Memory footprint: 7.07 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.28
Grid complexity:     1.09
Memory footprint:    39.94 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         8111         107283     29.79 M (78.09%)
    1          731          30097     10.15 M (21.91%)

Iterations: 6
Error:      6.29281e-09

[Profile:       0.898 s] (100.00%)
[ self:         0.002 s] (  0.25%)
[  reading:     0.677 s] ( 75.41%)
[  setup:       0.175 s] ( 19.49%)
[  solve:       0.044 s] (  4.85%)
```

**Comment by ddemidov** [comment]
Just out of curiosity: same system is solved with cholmod python wrapper in around 0.3 sec on the same machine:
```py
In [1]: from scipy.io import mmread                                                                                                                                                                                                                                               

In [2]: from sksparse.cholmod import cholesky                                                                                                                                                                                                                                     

In [3]: A = mmread('M').tocsc()                                                                                                                                                                                                                                                   

In [4]: b = mmread('M_rhs')                                                                                                                                                                                                                                                       

In [5]: %%timeit 
   ...: factor = cholesky(A) 
   ...: x = factor(b) 
   ...:  
   ...:                                                                                                                                                                                                                                                                           
316 ms ± 4.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

**Comment by ddemidov** [comment]
Final remark: `eps_strong=1e-6` to `1e-8` seems to optimal here (and brings total solution time down to 0.114 sec):
```
$ ./solver -A problems/issue-142/M -f problems/issue-142/M_rhs -b3 \
        solver.type=lgmres precond.relax.type=gauss_seidel \
        precond.coarsening.aggr.eps_strong=1e-6
Solver
======
Type:             LGMRES(30,3)
Unknowns:         8111
Memory footprint: 7.07 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.19
Grid complexity:     1.06
Memory footprint:    34.46 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         8111         107283     30.01 M (84.29%)
    1          453          19989      4.45 M (15.71%)

Iterations: 6
Error:      5.97266e-09

[Profile:       0.813 s] (100.00%)
[  reading:     0.699 s] ( 85.96%)
[  setup:       0.075 s] (  9.21%)
[  solve:       0.039 s] (  4.75%)
```

**Comment by ddemidov** [comment]
No, this is the final remark: for a system this small is seems that single level gauss-seidel works much better than multigrid (but this could change with scale):
```
$ ./solver -A problems/issue-142/M -f problems/issue-142/M_rhs -b3 \
        -1 solver.type=lgmres precond.type=gauss_seidel
Solver
======
Type:             LGMRES(30,3)
Unknowns:         8111
Memory footprint: 7.07 M

Preconditioner
==============
Relaxation as preconditioner
  unknowns: 8111
  nonzeros: 107283
  memory:   24.89 M

Iterations: 4
Error:      3.72019e-09

[Profile:       0.703 s] (100.00%)
[  reading:     0.673 s] ( 95.72%)
[  setup:       0.015 s] (  2.19%)
[  solve:       0.014 s] (  2.00%)
```

**Comment by liminchen** [comment]
Thanks a lot for your thorough explanation!! These are really helpful!!
Sorry I uploaded only the upper triangular part, but in the test I'm sure I gave AMGCL the full matrix (just double checked).
Following your suggestions I reproduced the non-converging issue (no nan) of CG scalar backend, and the nice performance of using LGMRES and nonzero eps_strong! But I still got nan from CG blockwise backend. Have you tried that? I thought blockwise backend should be better for FEM systems?
I'm also curious about why LGMRES is so much better than CG even when the system is SPD? And what would be a great strategy on picking eps_strong?
For your real final remark, yeah we were reproducing this issue in a smaller setting for convenience of investigation. We do have large scale systems like around 1M DOF that had the same issue.

**Comment by ddemidov** [comment]
> But I still got nan from CG blockwise backend. Have you tried that?

I can not reproduce the nans with CG, probably because the matrix I got from you is in text format and thus has lost some precision. NaNs could appear because one of the diagonal blocks is singular, and the singularity could disappear when the matrix was exported to text format.

> I'm also curious about why LGMRES is so much better than CG even when the system is SPD?

I have no answer for that. But I would just use LGMRES if that works.

> I thought blockwise backend should be better for FEM systems?

It is better. In my comments above I used block size of 3 (the `-b3` command line option). Without that, the convergence is much worse.

> And what would be a great strategy on picking eps_strong?

Just some experimenting. The default value is 0.08, and you don't usually need to go higher than that.

**Comment by liminchen** [comment]
Thank you so much!

**Comment by liminchen** [comment]
Right now I'm using block-wise backend, LGMRES, eps_strong=1e-6 to continue the simulation. It proceeds further from the frame with the previous issue and runs well. I will let you know how it works throughout as the simulation condition changes a lot in later frames.

**Comment by liminchen** [comment]
So I ran the simulation twice with
- block-wise backend, LGMRES, eps_strong=1e-6
- block-wise backend, LGMRES, default eps_strong
Both with relative_tolerance=1e-6 and max_iteration=1000, and they both get stuck at certain time step where after 1000 iterations, the relative error is still larger than 0.5.
Here I attached the systems M1 and M2, where eps_strong=1e-6 and default eps_strong get stuck respectively. But if I solve M1 using default eps_strong and M2 using eps_strong=1e-6, they both get solved to 1e-6 relative error with hundreds of iterations. 
Maybe it's just because the system changes dramatically so that a single eps_strong value may not fit all time steps? Is eps_strong used as absolute value or relative value? Maybe I can use some prior knowledge to the system to better set the parameters?
https://www.dropbox.com/s/h5hlqrr7wadi86s/linsys.zip?dl=0

**Comment by ddemidov** [comment]
> Maybe I can use some prior knowledge to the system?

You could provide near-null-space vectors for the problem. For example, if this is a 3D elasticity type problem, you could provide 6 rigid-body modes for it.

Alternatively, increasing the number of vectors in LGMRES upto 100 seems to work with your M2 (also, eps_strong=0):

```
$ ./solver -A issue-142/M2 -f issue-142/M2_rhs -b3 \
    solver.type=lgmres solver.maxiter=500 solver.M=100 \
    precond.relax.type=gauss_seidel precond.coarsening.aggr.eps_strong=0
Solver
======
Type:             LGMRES(100,3)
Unknowns:         8111
Memory footprint: 20.22 M

Preconditioner
==============
Number of levels:    2
Operator complexity: 1.19
Grid complexity:     1.06
Memory footprint:    34.45 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         8111         107281     30.01 M (84.37%)
    1          452          19878      4.43 M (15.63%)

Iterations: 161
Error:      8.85128e-09

[Profile:       1.315 s] (100.00%)
[  reading:     0.747 s] ( 56.86%)
[  setup:       0.047 s] (  3.54%)
[  solve:       0.520 s] ( 39.56%)
```

**Comment by liminchen** [comment]
Sounds good! I will try it. Thank you!

**Comment by liminchen** [comment]
Using M=100, eps_strong=0 can let simulation safely finish. Thanks a lot for your help!
