### ISSUE TITLE
Slightly different results when using different number of processors

### ISSUE THREAD

**Issue by zhuminjie** [ddemidov/amgcl#143]
Is that normal? I have set tol = 1e-9, and different is about 1e-5.

**Comment by ddemidov** [comment]
It could be normal. Can not say more based on what you provided.

**Comment by zhuminjie** [comment]
Thanks! I centralize the matrix on the processor 0, and run with different number of processors.

When I distribute the matrix along processors, the results look same with slight difference, but the number of iterations increase from 13 (1 core), to 103 (2 cores) and 251 (4 cores). Is it because of a possibly bad partition?

**Comment by ddemidov** [comment]
What relaxation do you use?

**Comment by zhuminjie** [comment]
Following is the setup:

prm.put("solver.type", "lgmres");
prm.put("solver.maxiter", 1000);
prm.put("solver.tol", 1e-8);
prm.put("precond.coarsening.type", "smoothed_aggregation");

typedef amgcl::mpi::make_solver<
                amgcl::mpi::amg<
                    Backend,
                    amgcl::runtime::mpi::coarsening::wrapper<Backend>,
                    amgcl::runtime::mpi::relaxation::wrapper<Backend>,
                    amgcl::runtime::mpi::direct::solver<double>,
                    amgcl::runtime::mpi::partition::wrapper<Backend>>,
                amgcl::runtime::solver::wrapper>
                Solver;

**Comment by ddemidov** [comment]
Can you share the single-process version of the matrix (in matrixmarket format)?

**Comment by zhuminjie** [comment]
Sure, can you show me how to save in that format?

**Comment by ddemidov** [comment]
You could use [amgcl::io::mm_write()](https://github.com/ddemidov/amgcl/blob/461a66ce6d197a3816218bf94ffd114a367c1ef1/amgcl/io/mm.hpp#L388-L390).

**Comment by zhuminjie** [comment]
[S.zip](https://github.com/ddemidov/amgcl/files/4283204/S.zip)

**Comment by zhuminjie** [comment]
This is a small matrix with 3322 by 3322. Thank you for taking your time to look at it. I really appreciate!

**Comment by ddemidov** [comment]
I can not reproduce this. The number of iterations does change from 5 to 7, which is expected, but not as dramatically as in your case. Could you make an error during the partitioning of your matrix?

Single MPI process:
```
mpirun -n 1 ./mpi_amg -A S.mm 
World size: 1
Type:             BiCGStab
Unknowns:         3322
Memory footprint: 181.67 K

Number of levels:    2
Operator complexity: 1.16
Grid complexity:     1.17

level     unknowns       nonzeros
---------------------------------
    0         3322          60462 (86.10%) [1]
    1          564           9760 (13.90%) [1]

Iterations: 5
Error:      9.57917e-09

[Profile:     0.074 s] (100.00%)
[ self:       0.020 s] ( 26.39%)
[  read:      0.048 s] ( 64.89%)
[  setup:     0.004 s] (  4.96%)
[  solve:     0.003 s] (  3.76%)
```

4 MPI processes, naive partitioning:
```
mpirun -n 4 ./mpi_amg -A S.mm 
World size: 4
Type:             BiCGStab
Unknowns:         831
Memory footprint: 45.45 K

Number of levels:    2
Operator complexity: 1.16
Grid complexity:     1.16

level     unknowns       nonzeros
---------------------------------
    0         3322          60462 (86.08%) [4]
    1          543           9779 (13.92%) [4]

Iterations: 7
Error:      4.32917e-09

[Profile:     0.127 s] (100.00%)
[ self:       0.047 s] ( 37.24%)
[  read:      0.060 s] ( 46.86%)
[  setup:     0.018 s] ( 14.46%)
[  solve:     0.002 s] (  1.44%)
```

4 MPI process, parmetis partitioning:
```
mpirun -n 4 ./mpi_amg -A S.mm -r parmetis
World size: 4
Partitioning[ParMETIS] 4 -> 4
Type:             BiCGStab
Unknowns:         839
Memory footprint: 45.88 K

Number of levels:    2
Operator complexity: 1.16
Grid complexity:     1.17

level     unknowns       nonzeros
---------------------------------
    0         3322          60462 (86.21%) [4]
    1          560           9672 (13.79%) [4]

Iterations: 7
Error:      5.39769e-09

[Profile:           0.091 s] (100.00%)
[ self:             0.019 s] ( 20.45%)
[  read:            0.044 s] ( 48.44%)
[  setup:           0.023 s] ( 24.82%)
[   self:           0.017 s] ( 19.12%)
[    partition:     0.005 s] (  5.70%)
[  solve:           0.006 s] (  6.29%)
```

**Comment by zhuminjie** [comment]
Yes, that is possible. In your second case, 4 MPI processes and naive partitioning, how did mpi_amg do the partition. Does every process reads the same matrix, and only takes the rows that belongs to the process? Which part of the mpi_amg does this naive partitioning?

Thank you so much!

**Comment by ddemidov** [comment]
The code is in [examples/mpi/mpi_amg.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/mpi/mpi_amg.cpp). Each MPI process initially reads its own continuous chunk of the matrix (this *is* the naive partitioning):

https://github.com/ddemidov/amgcl/blob/461a66ce6d197a3816218bf94ffd114a367c1ef1/examples/mpi/mpi_amg.cpp#L119-L152

If the user chooses a non-trivial partition, the matrix is repartitioned here:

https://github.com/ddemidov/amgcl/blob/461a66ce6d197a3816218bf94ffd114a367c1ef1/examples/mpi/mpi_amg.cpp#L188-L231

**Comment by zhuminjie** [comment]
Thank you so much! I will let you know if it works for me.

**Comment by zhuminjie** [comment]
After checking mm.hpp, I find the reason is that the sparse matrix library I use does not sort rows nor sum up duplicates. Once I do those, it gives correct number of iterations. 

Thanks again for your thoughtful inputs!
