### ISSUE TITLE
the settings about solving the sparse symmetric positive definite systems

### ISSUE THREAD

**Issue by ChunyangYe** [ddemidov/amgcl#146]
Hi,
when I assemble the matrix in CRS format, should I only assemble the upper triangular portion of the matrix or assemble the whole matrix? Are there any settings specialized for the symmetric matrix?

**Comment by ddemidov** [comment]
AMGCL always uses the full matrix, so you should assemble both halves. It needs to analyze the matrix structure during construction, and it is more convenient (faster) to do when access to each full row of the matrix is available.

**Comment by ChunyangYe** [comment]
Thanks for your reply.
The linear system in my question contains about 26.7 million unknowns and 200 million nonzeros.
I use the same setting as your Shared memory benchmark - 3D Poisson problem. i.e.,
	typedef
		make_solver<
		amg<
		backend::builtin<double>,
		coarsening::smoothed_aggregation,
		relaxation::spai0
		>,
		solver::cg<backend::builtin<double>>
		> Solver;

	Solver::params prm;
	prm.solver.maxiter = 1000;
	prm.solver.tol = 1e-4;
	Solver solve(std::tie(varN, ia, ja, amg_val), prm);
	std::tie(iters, error) = solve(ps_local.rhs, result_gs);

and the output is as follows,

Solver
======
Type:             CG
Unknowns:         26677382
Memory footprint: 814.13 M

Preconditioner
==============
Number of levels:    5
Operator complexity: 1.07
Grid complexity:     1.07
Memory footprint:    9.28 G

level     unknowns       nonzeros      memory
---------------------------------------------
    0     26677382      373483044      8.66 G (93.45%)
    1      1802156       23798304    577.69 M ( 5.95%)
    2       152930        2198544     51.98 M ( 0.55%)
    3        10954         173478      3.97 M ( 0.04%)
    4          728          12876      1.10 M ( 0.00%)

iters: 1000
error: 0.0326344

[Profile:  2299.556 s] (100.00%)
[  setup:    56.157 s] (  2.44%)
[  solve:  2243.343 s] ( 97.56%)

If I remove the two settings: 	prm.solver.maxiter = 1000; prm.solver.tol = 1e-4;
then the output: 

iters: 100
error: 0.158049

[Profile:   275.146 s] (100.00%)
[  setup:    46.327 s] ( 16.84%)
[  solve:   228.753 s] ( 83.14%)

I use OpenMP with 12 threads. I wonder if this performance is normal？Are there settings that can improve the performance?

**Comment by ChunyangYe** [comment]
> Thanks for your reply.
> The linear system in my question contains about 26.7 million unknowns and 200 million nonzeros.
> I use the same setting as your Shared memory benchmark - 3D Poisson problem. i.e.,
> typedef
> make_solver<
> amg<
> backend::builtin,
> coarsening::smoothed_aggregation,
> relaxation::spai0
> >,
> solver::cg<backend::builtin>
> > Solver;
> 
> ```
> Solver::params prm;
> prm.solver.maxiter = 1000;
> prm.solver.tol = 1e-4;
> Solver solve(std::tie(varN, ia, ja, amg_val), prm);
> std::tie(iters, error) = solve(ps_local.rhs, result_gs);
> ```
> 
> and the output is as follows,
> 
> Solver
> Type: CG
> Unknowns: 26677382
> Memory footprint: 814.13 M
> 
> Preconditioner
> Number of levels: 5
> Operator complexity: 1.07
> Grid complexity: 1.07
> Memory footprint: 9.28 G
> 
> level unknowns nonzeros memory
> 0 26677382 373483044 8.66 G (93.45%)
> 1 1802156 23798304 577.69 M ( 5.95%)
> 2 152930 2198544 51.98 M ( 0.55%)
> 3 10954 173478 3.97 M ( 0.04%)
> 4 728 12876 1.10 M ( 0.00%)
> 
> iters: 1000
> error: 0.0326344
> 
> [Profile: 2299.556 s] (100.00%)
> [ setup: 56.157 s] ( 2.44%)
> [ solve: 2243.343 s] ( 97.56%)
> 
> If I remove the two settings: prm.solver.maxiter = 1000; prm.solver.tol = 1e-4;
> then the output:
> 
> iters: 100
> error: 0.158049
> 
> [Profile: 275.146 s] (100.00%)
> [ setup: 46.327 s] ( 16.84%)
> [ solve: 228.753 s] ( 83.14%)
> 
> I use OpenMP with 12 threads. I wonder if this performance is normal？Are there settings that can improve the performance?

**Comment by ddemidov** [comment]
What kind of problem you are solving?

**Comment by ChunyangYe** [comment]
Solve the optimization problem using the Newton method, Hx=-g, H is the Hessian matrix and g is the gradient.

**Comment by ddemidov** [comment]
Sorry, that does not tell me much. What are the physical processes you are modeling?

**Comment by ddemidov** [comment]
So far the convergence looks very poor.

Without some information about the matrix structure, you could try a more effective relaxation method instead of the `spai0`, such as `ilu0` or `iluk`. 

You could also replace `smoothed_aggregation` coarsening with `ruge_stuben`. It will be more expensive memory-wise, but it may be more sensitive to the system structure.

You have a symmetric system, so `cg` may be a good choice, but you could also try `bicgstab` or `lgmres`.

**Comment by ChunyangYe** [comment]
Thanks. The optimization problem min E(x). E(x), a cumulative sum of the distortion energy on each element, is designed to measure mapping distortion on a triangle mesh. Hessian matrix H is sparse and nonzero H_ij means that i is adjacent to j on the mesh. 
I tried on a small mesh as your suggestion, but it seems that it performs worse than the default setting.

**Comment by ddemidov** [comment]
I am not familiar with these kinds of problems, so can not suggest anything. It is possible that multigrid is just not a good match here. Can you upload a matrix for a smaller system in the matrix market format (you can use [`amgcl::io::mm_write()`](https://github.com/ddemidov/amgcl/blob/2c64c77fa3cc5084cdbad19217204c98f5187b31/amgcl/io/mm.hpp#L388-L390))?

**Comment by ChunyangYe** [comment]
[mat.zip](https://github.com/ddemidov/amgcl/files/4464841/mat.zip)
%%MatrixMarket matrix coordinate real symmetric
405172 405172 3038646

**Comment by ddemidov** [comment]
Can you also upload the RHS? ([mm_write() for dense arrays](https://github.com/ddemidov/amgcl/blob/2c64c77fa3cc5084cdbad19217204c98f5187b31/amgcl/io/mm.hpp#L354-L356))

**Comment by ChunyangYe** [comment]
[rhs.zip](https://github.com/ddemidov/amgcl/files/4464897/rhs.zip)
%%MatrixMarket matrix array real general
405172 1

**Comment by ddemidov** [comment]
Looks like it converges quite fast to 1e-4 tolerance, but then stalls at something like 1e-5 (solver is compiled from [examples/solver.cpp](https://github.com/ddemidov/amgcl/blob/master/examples/solver.cpp)):
```
./solver -A mat -f rhs solver.tol=1e-4
Solver
======
Type:             BiCGStab
Unknowns:         405172
Memory footprint: 21.64 M

Preconditioner
==============
Number of levels:    4
Operator complexity: 1.10
Grid complexity:     1.09
Memory footprint:    148.34 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       405172        5672120    135.10 M (91.00%)
    1        33034         484128     11.17 M ( 7.77%)
    2         3687          67747      1.44 M ( 1.09%)
    3          443           9389    638.74 K ( 0.15%)

Iterations: 8
Error:      7.72777e-05

[Profile:       2.803 s] (100.00%)
[  reading:     2.016 s] ( 71.92%)
[  setup:       0.232 s] (  8.28%)
[  solve:       0.553 s] ( 19.73%)
```
Estimating spectral radius of the matrix helps to speed up convergence to 1e-4, but is not able to get out of 1e-5:
```
./solver -A mat -f rhs solver.tol=1e-4 precond.coarsening.estimate_spectral_radius=true
Solver
======
Type:             BiCGStab
Unknowns:         405172
Memory footprint: 21.64 M

Preconditioner
==============
Number of levels:    4
Operator complexity: 1.10
Grid complexity:     1.09
Memory footprint:    148.93 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       405172        5672120    135.10 M (90.77%)
    1        33034         484128     11.15 M ( 7.75%)
    2         4172          80892      1.70 M ( 1.29%)
    3          558          11994   1007.14 K ( 0.19%)

Iterations: 4
Error:      6.94533e-05

[Profile:       2.424 s] (100.00%)
[ self:         0.003 s] (  0.12%)
[  reading:     1.891 s] ( 78.01%)
[  setup:       0.243 s] ( 10.02%)
[  solve:       0.287 s] ( 11.85%)
```

The solver that is used here is `bicgstab`. Switching to cg seems to be counterproductive:
```
./solver -A mat -f rhs solver.tol=1e-4 precond.coarsening.estimate_spectral_radius=true solver.type=cg
Solver
======
Type:             CG
Unknowns:         405172
Memory footprint: 12.36 M

Preconditioner
==============
Number of levels:    4
Operator complexity: 1.10
Grid complexity:     1.09
Memory footprint:    148.93 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       405172        5672120    135.10 M (90.77%)
    1        33034         484128     11.15 M ( 7.75%)
    2         4172          80892      1.70 M ( 1.29%)
    3          558          11994   1007.14 K ( 0.19%)

Iterations: 100
Error:      0.000504122

[Profile:       5.676 s] (100.00%)
[  reading:     1.986 s] ( 34.99%)
[  setup:       0.253 s] (  4.45%)
[  solve:       3.435 s] ( 60.52%)
``` 

Do you happen to know the near-null-space vectors for the problem? Looks like it could benefit from using the information.
