### ISSUE TITLE
Using zero copy with 32 bit index_type

### ISSUE THREAD

**Issue by BinWang0213** [ddemidov/amgcl#147]
Hi,

In order to save some memory, I'm trying to use zero_copy adaptor and 32-bit index_type (int) for my CSR sparse matrix.

But I searched the issues and found your comments:

> To use a zero_copy adapter, you need to make sure that _StorageIndex in the matrix template parameters is ptrdiff_t (or binary compatible). Then you should be able to use
> 
> zero_copy(A.rows(), A.outerIndexPtr(), A.innerIndexPtr(), A.valuePtr())

Is there any workaround to force AMGCL to use 32-bt index_type as well?

BTW, Pardiso has pardiso() and pardiso_64() for 32-bit and 64-bit index, respectively. So I can switch between them when necessary.

Thanks,
Bin

**Comment by ddemidov** [comment]
No, there is not an easy way to use 32bit index type in amgcl.

**Comment by BinWang0213** [comment]
Got it.  Thanks for your rapid reply. I will close this issue.
