### ISSUE TITLE
get_params & runtime interface

### ISSUE THREAD

**Issue by xgarnaud** [ddemidov/amgcl#149]
Hi,

I got a compilation error when using get_params on a solver built with the runtime interface (issue with the macro AMGCL_PARAMS_EXPORT_CHILD)

It seems that using this fixes the issue
```C++
template <typename T>
inline void __amgcl_params_export_child(boost::property_tree::ptree &p,
                                        const std::string &path,
                                        const char *name, const T &obj) {
  obj.get(p, std::string(path) + name + ".");
}

template <>
inline void
__amgcl_params_export_child(boost::property_tree::ptree &p,
                            const std::string &path, const char *name,
                            const boost::property_tree::ptree &obj) {
  p.add_child(std::string(path) + name, obj);
}

#define AMGCL_PARAMS_EXPORT_CHILD(p, path, name)                               \
  __amgcl_params_export_child(p, path, #name, name)

**Comment by ddemidov** [comment]
Can you provide a reproducible example?

**Comment by ddemidov** [comment]
Sorry, I did not notice that this is about exporting params. Yes, there could be a problem (I think it was a long time since anyone tried that).

**Comment by xgarnaud** [comment]
Hi.

Adding 
```c++
	boost::property_tree::ptree params;
	solve.get_params(params);
```

on l. 315 of examples/solver.cpp reproduces the issue

**Comment by ddemidov** [comment]
Thank you both for reporting this and providing the solution! 4b29d7a should fix the issue.

**Comment by ddemidov** [comment]
However, I am not sure the result here is the one you actually need: instead of outputting the default values for the parameters it dumps the subtree of the parameters you provided. 

for example, with this change in `solver/example.cpp`:
```
	boost::property_tree::ptree params;
	solve.get_params(params);
        write_json(std::cout, params);
```
I am getting this output:
```
./solver -p precond.relax.type=spai0 precond.foo.test=123
...
{
    "precond": {
        "relax": {
            "type": "spai0"
        },
        "foo": {
            "test": "123"
        }
    },
    "solver": ""
}

...
```
Let me see if I can improve this.

**Comment by ddemidov** [comment]
No, I don't see how it may be improved without some massive code alterations.
