### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by peteryim** [ddemidov/amgcl#150]
I was able to run cmake (see below) but Make failed to complete. (See below)    (Ubuntu 18.04.3 LTS, gcc 7.5.0).   I also tried earlier versions of the repository.  Make failed to complete for those too - but at different points.  I tried "sudo make"  too in case it was a permissions issue and I had the same result.  Any suggestions?   

CMAKE output:

~/amgcl/build$ cmake -DAMGCL_BUILD_EXAMPLES=ON ..
-- No build type selected, default to RelWithDebInfo
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   serialization
--   unit_test_framework
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/amgcl/build

Make output:
~/amgcl/build$ make
Scanning dependencies of target libamgcl
[  1%] Building CXX object lib/CMakeFiles/libamgcl.dir/amgcl.cpp.o
[  3%] Linking CXX static library libamgcl.a
[  3%] Built target libamgcl
Scanning dependencies of target libamgcl_mpi
[  5%] Building CXX object lib/CMakeFiles/libamgcl_mpi.dir/amgcl_mpi.cpp.o
[  7%] Linking CXX static library libamgcl_mpi.a
[  7%] Built target libamgcl_mpi
Scanning dependencies of target crs_builder
[  8%] Building CXX object examples/CMakeFiles/crs_builder.dir/crs_builder.cpp.o
[ 10%] Linking CXX executable crs_builder
[ 10%] Built target crs_builder
Scanning dependencies of target mixed_precision
[ 12%] Building CXX object examples/CMakeFiles/mixed_precision.dir/mixed_precision.cpp.o
[ 14%] Linking CXX executable mixed_precision
[ 14%] Built target mixed_precision
Scanning dependencies of target schurpc_mixed
[ 16%] Building CXX object examples/CMakeFiles/schurpc_mixed.dir/schurpc_mixed.cpp.o

**Comment by ddemidov** [comment]
I don't see any errors here, just the incomplete build log. Does it just stop here? Home much memory do you have in your machine? Compiling amgcl may require a lot, due to the amount of templated code.

**Comment by peteryim** [comment]
You are right.  I was installing on an instance with 1 GB memory.  It did
install on an instance with 4 GB using the same operating system/software
image..

Thanks,

Peter

**Comment by ddemidov** [comment]
Just as a note: you don't need to compile anything if you want to install amgcl, since it is a header-only library.

**Comment by peteryim** [comment]
I may have used the wrong word "install" - but I am thinking of
modifying/adapting.
