### ISSUE TITLE
Support for the latest CUDA 11 SDK

### ISSUE THREAD

**Issue by Chaos-ThoR** [ddemidov/amgcl#155]
In the CUDA 11 SDK there is also a new cuSparse lib.

And for this lib:

> The following functions have been removed:
Hybrid format enums and helper functions: cusparseHybPartition_t, cusparseHybPartition_t, cusparseCreateHybMat, cusparseDestroyHybMat...

Source: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#deprecated-features

**Comment by ddemidov** [comment]
Do you know if there are alternatives, or does it mean the hybrid format is no longer supported?

**Comment by Chaos-ThoR** [comment]
As far as I can see, the functions have been removed. Unfortunately, I don't know if there are any alternatives.

**Comment by ddemidov** [comment]
Looks like the only general format they have now is CSR. Thanks for pointing this out!

**Comment by ddemidov** [comment]
@Chaos-ThoR, do you have access to CUDA11? #156 uses the new CUSPARSE API. Would that work for you?

**Comment by Chaos-ThoR** [comment]
The operator() in cuda.hpp:
113     void operator()(cusparseHybMat_t handle) {
114         AMGCL_CALL_CUDA( cusparseDestroyHybMat(handle) );
115     }

causes build errors. But if i remove this operator, it compiles. Then we have some failing tests with different results. I have to speak with my colleague on monday).

Thanks, for the fast answer.

**Comment by ddemidov** [comment]
Forgot about the `cusparseHybMat_t` deleter, sorry. Should be fixed in ab0f8ea9363c86152b201fd587868a7af7f7517c. What kind of tests do you see failing? The path with the CSR matrix does compile on CUDA 10 for me, and it seems to work fine.

**Comment by ddemidov** [comment]
Could the failing tests be related to #157?

**Comment by Chaos-ThoR** [comment]
We are using your lib to calculate some flow calculations (navier stokes equations). I don't know how sensitive the complete algorithm is. I have to speak with the responsible developer. May be he can give us more information about the different results with the changes in the cuda backend.

**Comment by Chaos-ThoR** [comment]
Our responsible developer checked the results and said:
"As I checked, the difference is just caused by the accumulation of small errors during the iteration. So I've reproduced the test data."

So, thanks for the quick support and this "issue" is solved :-)

**Comment by ddemidov** [comment]
Ok, I've merged #156 into master. Thank you for confirmation!
