### ISSUE TITLE
Is it possible to have multiple AMGCL solvers at the same time?

### ISSUE THREAD

**Issue by liminchen** [ddemidov/amgcl#158]
I was trying to maintain multiple AMGCL solvers in my program because only the rhs of my problems changes. So I wrote
```
typedef amgcl::backend::eigen<T> Backend;
    typedef amgcl::make_solver<
            amgcl::amg<
                Backend,
                amgcl::coarsening::smoothed_aggregation,
                amgcl::relaxation::gauss_seidel
            >,
        amgcl::solver::cg<Backend>
    > Solver;
    Solver *pressureSolver = NULL, *diffusionSolver[dim] = { NULL };
```
and then `new Solver` for each pointer.
But it seems I'm unable to use it this way. The program just crashes. (SIGSEGV)
Is it possible to have multiple AMGCL solvers at the same time?

**Comment by ddemidov** [comment]
This is definitely possible, I would just double-check the lifetimes of the objects in your program (that you are not trying to use unallocated or deleted or null pointers).

**Comment by liminchen** [comment]
Thanks a lot! I think I found the problem.
