### ISSUE TITLE
Program abort when using interface 'amgcl_solver_solve_mtx' in C++ and Fortran

### ISSUE THREAD

**Issue by xiangyue1993** [ddemidov/amgcl#159]
Hi,

I want to explicitly provide matrix for amgcl solver without repeatedly creating solver at each iteration in my program, so I tried to use interface 'amgcl_solver_solve_mtx'. However, an abort error  occurred when I tested example of '[call_lib](https://github.com/ddemidov/amgcl/blob/master/examples/call_lib.cpp)'. After I checked the resource code, I found it seemed that the [code](https://github.com/ddemidov/amgcl/blob/master/lib/amgcl.cpp#L240) should be 'boost::make_iterator_range(A_ptr, A_ptr + n + 1)', and it works for example 'call_lib' after I modified the source code.
Then, I tried to bind this C++ interface to Fortran. I modified files of [amgcl.h](https://github.com/xiangyue1993/amgcl/blob/master/lib/amgcl.h#L143), [amgcl.cpp](https://github.com/xiangyue1993/amgcl/blob/master/lib/amgcl.cpp#L252), [dll.def](https://github.com/xiangyue1993/amgcl/blob/master/lib/dll.def#L19), [amgcl.f90](https://github.com/xiangyue1993/amgcl/blob/master/fortran/amgcl.f90#L145) and [poisson.f90](https://github.com/xiangyue1993/amgcl/blob/master/fortran/poisson.f90#L77), and this poisson fortran project was successfully compiled and built. However, I recieved an abort error when the program run to 'amgcl_solver_solve_mtx'.
I'm using VS 2019 and Intel Fortran Compiler on Windows. I wonder if my modification for 'amgcl_solver_solve_mtx' is right, and how to resolve this issue?

Thanks,
Xiang

**Comment by ddemidov** [comment]
Thank you for pointing out the off-by-one error! Further, in order to use `amgcl_solver_solve_mtx` in Fortran, you need to adjust the `ptr` and `col` values by one. #160 attempts to do this. Does it work for you?

**Comment by xiangyue1993** [comment]
Yes it works! Thanks a lot for your reply!
