### ISSUE TITLE
lgmres helps robustly solve super stiff systems but no guarantee on maintaining SPD feature?

### ISSUE THREAD

**Issue by liminchen** [ddemidov/amgcl#163]
I'm trying to solve a stiff SPD system in an optimization to get a descent search direction for armijo line search. As kindly suggested by the author earlier in #142 , I used
```
    typedef amgcl::static_matrix<double, DIM, DIM> value_type;
    typedef amgcl::static_matrix<double, DIM, 1> rhs_type;
    typedef amgcl::backend::builtin<value_type> BBackend;
    using Solver = amgcl::make_solver<
        // Use AMG as preconditioner:
        amgcl::amg<
            BBackend,
            amgcl::coarsening::smoothed_aggregation,
            amgcl::relaxation::gauss_seidel>,
        // And BiCGStab as iterative solver:
        amgcl::solver::lgmres<BBackend>>;
```
with
```
    Solver::params prm;
    prm.solver.tol = 1e-5; // relative
    prm.solver.maxiter = 1000;
    prm.precond.coarsening.aggr.eps_strong = 0.0;
    prm.solver.M = 100;
```
and for the following system:
https://www.dropbox.com/s/rp3xe2xkk5o16zk/StiffSystem.zip?dl=0
AMGCL took 1000 iterations to get a relative error at 0.000360631, but the search direction is not a good descent direction where it fails the armijo line search with very small step size.
Is there any better parameters for this kind of stiff systems? Would there be an option like CG that can make sure the search direction is descent? Any suggestions would be appreciated!

**Comment by ddemidov** [comment]
Sorry, I don't have any immediate suggestions here. I do see that the convergence stalls at around 1e-3 relative residual.

**Comment by liminchen** [comment]
No worries, thanks a lot for your time!
