### ISSUE TITLE
Using Eigen with AMGCL

### ISSUE THREAD

**Issue by ArturSalamatin** [ddemidov/amgcl#167]
Dear Denis,

I am solving a linear problem Ax = b with large sparse matrix A,
where A is an Eigen sparse matrix and x and b are of type VectorXd. 

Following your replies on previous issues, I used the following #include commands:
```
#include <amgcl/adapter/eigen.hpp>
#include <amgcl/backend/builtin.hpp>
#include <amgcl/make_solver.hpp>
#include <amgcl/solver/bicgstab.hpp>
#include <amgcl/amg.hpp>
#include <amgcl/coarsening/smoothed_aggregation.hpp>
#include <amgcl/relaxation/spai0.hpp>
#include <amgcl/adapter/crs_tuple.hpp>
#include <amgcl/solver/gmres.hpp>
#include <amgcl/adapter/eigen.hpp>
```
with
```
AMGCL_USE_EIGEN_VECTORS_WITH_BUILTIN_BACKEND()
```
and introduced the following types

```
typedef Eigen::SparseMatrix<double, RowMajor> SpMat; 
typedef amgcl::backend::builtin<double> Backend;
typedef amgcl::make_solver <
	amgcl::amg < Backend,
	amgcl::coarsening::smoothed_aggregation,
	amgcl::relaxation::spai0
	>,
	amgcl::solver::bicgstab < Backend > > 
Solver_AMG;
```

The code to solve the problem then reads as

		Solver_AMG solve(A);
		int    iters;
		double error;
		std::tie(iters, error) = solve(b, x);

As a result I have the following list of errors:
where ...\amgcl stands for the relative path to the file where the error occurred

Error	C2039	'CLEAR_NOT_IMPLEMENTED': is not a member of 'Eigen::Array<double,-1,1,0,-1,1>'	...\amgcl\backend\interface.hpp	
Error	C3646	'type': unknown override specifier	...\amgcl\backend\interface.hpp	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	...\amgcl\backend\interface.hpp	
Error	C2039	'apply': is not a member of 'amgcl::backend::clear_impl<Vector,void>' 	...\amgcl\backend\interface.hpp	
Error	C3861	'apply': identifier not found	...\amgcl\backend\interface.hpp	
Error	C2039	'AXPBY_NOT_IMPLEMENTED': is not a member of 'amgcl::backend::numa_vector<double>'	...\amgcl\backend\interface.hpp	
Error	C3646	'type': unknown override specifier	...\amgcl\backend\interface.hpp	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	...\amgcl\backend\interface.hpp	
Error	C2039	'apply': is not a member of 'amgcl::backend::axpby_impl<A,Vector1,B,Vector2,void>'	...\amgcl\backend\interface.hpp	
Error	C3861	'apply': identifier not found	...\amgcl\backend\interface.hpp

**Comment by ddemidov** [comment]
Can you provide a minimal example to reproduce the problem? Something along the lines of
https://gist.github.com/ddemidov/cc1d78bc82b21cb9d09f7426ea0e5e56

**Comment by ddemidov** [comment]
The following code uses Eigen inputs and builtin backend and works for me:
https://gist.github.com/ddemidov/7894e9f89ae0f56a39d4a39599db5166

Make sure you do use `Eigen::VectorXd` and not `Eigen::Array` for your vectors.

**Comment by ArturSalamatin** [comment]
Thank you very much for your patience!

Indeed, the problem was that I used Eigen::ArrayXd for the vector of unknowns.

Now code is compiled, and I can proceed with your library.
