### ISSUE TITLE
Cuthill-McKee matrix reorder algorithm with with Eigen::SparseMatrix

### ISSUE THREAD

**Issue by ArturSalamatin** [ddemidov/amgcl#168]
Dear Denis,

would you be so kind to provide an example of how to use
the Cuthill-McKee matrix reorder algorithm with Eigen::SparseMatrix<double, RowMajor>?

Thank you in advance!

**Comment by ddemidov** [comment]
Something like this should work:
https://github.com/ddemidov/amgcl/blob/affc72ec009393134688e17110a8d38661d2a99a/examples/solver.cpp#L92-L112

**Comment by ArturSalamatin** [comment]
Should it work with Eigen library directly, or should I cast my Eigen::SparseMatrix into the CRS tuple format?

**Comment by ddemidov** [comment]
It should work directly it you include the either adapter header.

--
Cheers,
Denis

**Comment by ArturSalamatin** [comment]
Currently I am using this
```
#include <amgcl/adapter/eigen.hpp>
#include <amgcl/backend/builtin.hpp>
#include <amgcl/make_solver.hpp>
#include <amgcl/solver/gmres.hpp>
#include <amgcl/amg.hpp>
#include <amgcl/coarsening/smoothed_aggregation.hpp>
#include <amgcl/relaxation/spai0.hpp>

AMGCL_USE_EIGEN_VECTORS_WITH_BUILTIN_BACKEND()

typedef Eigen::SparseMatrix<double, RowMajor> SpMat;

typedef amgcl::make_solver<
	amgcl::amg<
	amgcl::backend::builtin < double >,
	amgcl::coarsening::smoothed_aggregation,
	amgcl::relaxation::spai0
	>,
	amgcl::solver::gmres<amgcl::backend::builtin < double > >
> 
Solver_AMG;
```


Visual Studio does not allow ADAPTER after AMGCL in 
```
amgcl::adapter::reorder<> perm(A);
```

**Comment by ddemidov** [comment]
Could the error message be closer to "I don't know what you mean by `amgcl::adapter::reorder<>`"? Please see if including [`<amgcl/adapter/reorder.hpp>`](https://github.com/ddemidov/amgcl/blob/master/amgcl/adapter/reorder.hpp) helps.

**Comment by ArturSalamatin** [comment]
With this include command the code compiles, but the program throws an error in line 126 of cutheel-mckee.hpp file
```
Exception thrown at 0x00007FF61DA330D4 in OilReservoir_Eigen.exe: 0xC0000005: Access violation writing location 0x0000000000000000. occurred
```
To guarantee its symmetry, as the matrix A I use 
```
A = A * A.transpose();
```

Additional comments:
1. The matrix size is 3*N x 3*N, and the last N x N diagonal block is ZERO,
while the matrix rank is correct, rank(A) = 3N.
2. So far, I use the Eigen::SparseMatrix representation and store the entire matrix rather than its upper or lower half.

Offtop:
It seems that the iterative solvers returns different solutions depending on whether I store A as a RowMajor or ColumnMajor.
However, this I have to investigate in more details.

**Comment by ddemidov** [comment]
> ```
> Exception thrown at 0x00007FF61DA330D4 in OilReservoir_Eigen.exe: 0xC0000005: Access violation writing location 0x0000000000000000. occurred
> ```

This looks like a memory error somewhere in your program. The following example works without errors for me:
https://gist.github.com/ddemidov/10727dfdcbf09381e55a14c3d62853b1
(you can test it with an example in matrix market format from suitesparse, e.g. https://sparse.tamu.edu/Botonakis/thermomech_dM).



> 1. The matrix size is 3_N x 3_N, and the last N x N diagonal block is ZERO,

Is it a [Navier-]Stokes type system? Have a look at https://arxiv.org/abs/2006.06052 for possible solution options. The idea is to use preconditioner tailored for the problem at hand.

> 2\. So far, I use the Eigen::SparseMatrix representation and store the entire matrix rather than its upper or lower half.

That is the only valid option.



> It seems that the iterative solvers returns different solutions depending on whether I store A as a RowMajor or ColumnMajor.

The only valid choice for amgcl is RowMajor.
