### ISSUE TITLE
Using amg relaxation as preconditioner.

### ISSUE THREAD

**Issue by g873249824** [ddemidov/amgcl#174]
1.When i use the /example/solver.cpp like this 
   ./solver -p precond=relaxation precond.relax=ilu0 solver.type=gmres
does it mean that i use the ilu0 as precondtioner, although it setup the amg. i didn't tell the obvious difference between with or without "precond=relaxation" in running, i want to comfirm that. Do i use it rightly?

2.by the way, when i use the BACKEND_SOlVER_EIGEN,maybe there is some problem with the commandline output, which is like   this  
```
Preconditioner
==============
Number of levels:    3
Operator complexity: 1.59
Grid complexity:     1.14
Memory footprint:    1.12 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        32768         223232      0.00 B (62.80%)
    1         4192         114356      0.00 B (32.17%)
    2          346          17898      1.12 M ( 5.03%)
```
Best regards.
GENG

**Comment by g873249824** [comment]
Sorry, i find the problem. I need to use "precond.class=relaxation" as paramaters.

**Comment by ddemidov** [comment]
AMG uses one or more relaxation (smoother) iterations on each level of AMG hierarchy. And `precond.relax.type` command line parameter for `examples/solver` chooses the smoother. A relaxation method may also be used as a standalone single-level preconditioner. In this case, you set `precond.class=relaxation` and you choose the relaxation method with `precond.type`.

**Comment by g873249824** [comment]
Thank you very much.
GENG
