### ISSUE TITLE
How to use mm to read more than one right hand side?

### ISSUE THREAD

**Issue by g873249824** [ddemidov/amgcl#177]
I feel very greatful for your patience and work. 
I wonder if I can use mm.hpp to read more than one right hand side like n * 2 or n * 3 in the format of matrix market.
[Queen_4147.txt](https://github.com/ddemidov/amgcl/files/5557536/Queen_4147.txt)
[dgreen.txt](https://github.com/ddemidov/amgcl/files/5557537/dgreen.txt)

By the way, i want to use some "skills" to accelerate the convergence of amg as a standalone solver. Some questions bother me (having nothing to do with the code).
1.Why doesn't amg work alone(as a solver) usually?
2.Does amg deficient in stability or effience for most common problems compared with preconditioned Krylov subspace methods?(I got ambiguous understanding from literature)
3.I want to do some comparison tests, but for some problems the amg solver divergences, like 
https://sparse.tamu.edu/VLSI/dgreen
https://sparse.tamu.edu/Janna/Queen_4147
form SuiteSparse.
What i used are default parameters(coarsening:smoothed aggregation ,relax:spai0). I tried little changes but it still didn't work.
What is your seggestion for the test ?(Maybe poisson problem ?)

Sorry to bother you frequently.

Best regards.

GENG

**Comment by ddemidov** [comment]
> I wonder if I can use mm.hpp to read more than one right hand side like n * 2 or n * 3 in the format of matrix market.

You can. What you get is a continuous array representing the n x m matrix. If the matrix in the mm file is 'wide' (stored such that individual RHS vectors are stored continuously), then you could use `amgcl::make_iterator_range()` to get the RHS vectors. In other case, you could use something like strided iterator range from boost or simply copy individual vectors to separate containers.

> 1.Why amg doesn't work alone(as a solver) usually?

It does, only using it with a Krylov solver is much more effective. See discussion here: https://groups.google.com/g/amgcl/c/dfi9XjANnDU and [1] for more details (specifically section A.7.3).

[1] Stüben, Klaus. "An introduction to algebraic multigrid." Multigrid (2001): 413-532.
http://ebrary.free.fr/Mesh%20Generation/Trottenberg%20-%20Multigrid/app01.pdf

> 2. Does amg deficient in stability or effience for most common problems compared with preconditioned Krylov subspace methods?(I got ambiguous understanding from literature)

The standard use of amg is as a preconditioner to a Krylov solver.

> 3.I want to do some comparison tests, but for some problems the amg solver divergences

AMG has some theoretical limitations, for example, the matrix has to be an M-matrix (positive semi-definite). If AMG with default parameters does not work, you often need to understand the properties of the system to make some educated guesses about how to proceed. For example, AMG is not applicable to saddle-point systems directly, but may be a part of a composite preconditioner.

> What is your seggestion for the test ?(Maybe poisson problem ?)

A Poisson problem would definitely work, but may be is too boring (it is ideally suited for AMG). Maybe a 3D structural mechanics problem would be more interesting. Anyway, I think you should test the problems you are actually interested in solving.

**Comment by g873249824** [comment]
Thank you so much for your guidance and patience. I got a clearer understanding of that and I will refer to more related literature for more detail.
So, if i want to do enough benchmark test to comfirm the acceleration of convergenvce(like number of cycles) using amg as standalone solver. Which type of questions would be suitable for that?
Maybe I need to got some classications from SuiteSparse like structural problems,electromagnetics,thermodynamics,computational fluid dynamics...etc. chosing form some of above classifications. I am not sure if it's the right way to do that.

**Comment by ddemidov** [comment]
> So, if i want to do enough benchmark test to comfirm the acceleration of convergenvce(like number of cycles) using amg as standalone solver

I have recently added a [Richardson iteration](https://en.wikipedia.org/wiki/Modified_Richardson_iteration) as a solver type. It is basically equivalent to the application of a preconditioner in a loop. So it is possible to do some tests using the solver:

**3D Poisson problem solved with CG preconditioned with AMG**:
```
./solver -n 50 solver.type=cg
Solver
======
Type:             CG
Unknowns:         125000
Memory footprint: 3.81 M

Preconditioner
==============
Number of levels:    3
Operator complexity: 1.60
Grid complexity:     1.14
Memory footprint:    46.74 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       125000         860000     32.66 M (62.31%)
    1        15850         453052      9.75 M (32.83%)
    2         1141          67063      4.34 M ( 4.86%)

Iterations: 14
Error:      2.54468e-09

[Profile:          0.255 s] (100.00%)
[ self:            0.001 s] (  0.35%)
[  assembling:     0.013 s] (  5.19%)
[  setup:          0.107 s] ( 41.84%)
[  solve:          0.134 s] ( 52.62%)
```

**Same problem solved with Richardson iteration preconditioned with AMG** (should be close to standalone AMG):
```
./solver -n 50 solver.type=richardson
Solver
======
Type:             Richardson
Unknowns:         125000
Memory footprint: 1.91 M

Preconditioner
==============
Number of levels:    3
Operator complexity: 1.60
Grid complexity:     1.14
Memory footprint:    46.74 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       125000         860000     32.66 M (62.31%)
    1        15850         453052      9.75 M (32.83%)
    2         1141          67063      4.34 M ( 4.86%)

Iterations: 30
Error:      6.86814e-09

[Profile:          0.378 s] (100.00%)
[ self:            0.004 s] (  1.16%)
[  assembling:     0.013 s] (  3.34%)
[  setup:          0.122 s] ( 32.28%)
[  solve:          0.239 s] ( 63.22%)
```

As you can see, the standalone AMG works, but coupling it with a Krylov solver is working better.

> Maybe I need to got some classications from SuiteSparse like structural problems,electromagnetics,thermodynamics,computational fluid dynamics...etc. chosing form some of above classifications. I am not sure if it's the right way to do that.

The systems from the SuiteSparse collection have very little information attached to them. And you need this info if you want to tune the solver for a specific system (e.g. spatial coordinates of the grid nodes, which DOFs correspond to which physical processes, etc).  So the right way would be to discretize your own problem. You could also use some systems with more data available. For example, both the code and the dataset for the benchmarks in [2] are publicly available.

[2] Demidov, Denis, Lin Mu, and Bin Wang. "Accelerating linear solvers for Stokes problems with C++ metaprogramming." arXiv preprint [arXiv:2006.06052](https://arxiv.org/abs/2006.06052) (2020).

**Comment by g873249824** [comment]
Thank you for your suggestions and guidance.

Sincerely.

GENG
