### ISSUE TITLE
Can I couple custom solvers with the preconditioners?

### ISSUE THREAD

**Issue by Arsennnic** [ddemidov/amgcl#182]
Dear Denis,

I am new to AMG and AMGCL. I modified `Fortran/poisson.f90` to solve a three-dimensional poisson problem. Besides, I compared the efficiency of implemented BiCGStab solver and my custom solver (based on BICGS, without any coarsening operations, written in pure Fortran). No MPI or OpenMP or GPU accelerating techniques were used.
```Fortran
call cpu_time(tic)

params = amgcl_params_create()
call amgcl_params_sets(params, "solver.type", "bicgstab")
call amgcl_params_setf(params, "solver.tol", 1e-6)
call amgcl_params_seti(params, "precond.max_levels", 8)

solver = amgcl_solver_create(nall, ptr, col, val, params)
call amgcl_solver_report(solver)
cnv = amgcl_solver_solve(solver, rhs, x1)

call amgcl_solver_destroy(solver)
call amgcl_params_destroy(params)

call cpu_time(toc)
print *, 'AMGCL:', toc - tic
    
call cpu_time(tic)
call my_custom_solver(nall, nnz, ptr, col, val, x2, rhs)
call cpu_time(toc)
print *, 'CUSTOM:', toc - tic
```

The outputs were as follows.
```
Number of levels:    4
Operator complexity: 1.60
Grid complexity:     1.13
Memory footprint:    1.42 G

level     unknowns       nonzeros      memory
---------------------------------------------
    0      4194304       28803072      1.07 G (62.66%)
    1       524976       14754962    320.79 M (32.10%)
    2        37942        2355460     41.71 M ( 5.12%)
    3         1781          53649      3.65 M ( 0.12%)

AMGCL:   57.421875000000000
CUSTOM:  18.531250000000000
```

I surprisingly found that my custom solver preformed much more better than BiCGStab solver. I wondered if the parameters were set properly in my code. Or perhaps this just meant the BiCGStab solver provided by Eigen consumed too much time? If so, will it be possible to couple my custom solver with the preconditioners?

**Comment by ddemidov** [comment]
The parameters look ok, except I would drop the `precond.max_levels` (the solver should determine this automatically; in this case it looks like it would choose 8 levels anyway).

Can you separate the times for the construction (line
```f90
solver = amgcl_solver_create(nall, ptr, col, val, params)
```
) and the solution (line
```f90
cnv = amgcl_solver_solve(solver, rhs, x1)
```
)? Also, can you output the number of iterations (`cnv%iterations`) it took amgcl to converge?

And, of course, please make sure that the amgcl library (`libamgcl`, the one compiled with C++) is compiled with full optimization.

**Comment by Arsennnic** [comment]
I have separated the times for the construction and the solution now.
```Fortran
call cpu_time(tic)
params = amgcl_params_create()
call amgcl_params_sets(params, "solver.type", "bicgstab")
call amgcl_params_setf(params, "solver.tol", 1e-6)
solver = amgcl_solver_create(nall, ptr, col, val, params)
call amgcl_solver_report(solver)
call cpu_time(toc)
time(1) = toc - tic

call cpu_time(tic)
cnv = amgcl_solver_solve(solver, rhs, x1)
write(*,"('Iterations:', I3, ', residual: ', E13.6)") cnv%iterations, cnv%residual
call cpu_time(toc)
time(2) = toc - tic

call amgcl_solver_destroy(solver)
call amgcl_params_destroy(params)

call cpu_time(tic)
call soscgs(nall, nnz, ptr, col, val, x2, rhs, signr)
call cpu_time(toc)
time(3) = toc - tic

print *, 'AMGCL (construction):', time(1)
print *, 'AMGCL (solution):', time(2)
print *, 'AMGCL (construction + solution):', time(1) + time(2)
print *, 'CUSTOM:', time(3)
```

And now the outputs were as follows.
```
Number of levels:    4
Operator complexity: 1.60
Grid complexity:     1.13
Memory footprint:    1.42 G

level     unknowns       nonzeros      memory
---------------------------------------------
    0      4194304       28803072      1.07 G (62.66%)
    1       524976       14754962    320.79 M (32.10%)
    2        37942        2355460     41.71 M ( 5.12%)
    3         1781          53649      3.65 M ( 0.12%)

Iterations:  6, residual:  0.618685E-06

AMGCL (construction):   21.453125000000000
AMGCL (solution):   49.515625000000000
AMGCL (construction + solution):   70.968750000000000
CUSTOM:   23.312500000000000
```

Meanwhile, AMGCL library was indeed compiled with full optimization (-O3 -DNDEBUG).
![WeChat Screenshot_20210212184022](https://user-images.githubusercontent.com/23273199/107758518-f84d4180-6d61-11eb-8ef2-4c49530005e4.png)

**Comment by ddemidov** [comment]
That looks strange indeed. Couple of things I would try:

* set environment variable `OMP_NUM_THREADS=1` in case there is something else happening in the system during the test, and the CPU is oversubscribed.
* Compile the `examples/solver.cpp` from amgcl, save the matrix and the rhs to the matrix market format, and check if the standalone solver shows similar performance (`./solver -A A.mtx -f b.mtx`). You can also use the compiled example from the docker image:
```
docker run -v $PWD:/data amgcl/examples solver -A A.mtx -f b.mtx
```
* If the standalone solver indeed is showing similar performance to the fortran wrapper, I would also try using the single-level preconditioner:
```
./solver -A A.mtx -f b.mtx -1
```

**Comment by Arsennnic** [comment]
I had tried the single-level preconditioner before by `call amgcl_params_seti(params, "precond.max_levels", 1)`. 
It spent more time than multiple-level cases, and it proved that AMGCL is effective.
I will set the environment variable, and check the performance of the solver without Fortan wrapper.
Thanks a lot Denis.
