### ISSUE TITLE
Recommendations for solver type and preconditioners

### ISSUE THREAD

**Issue by mobereng** [ddemidov/amgcl#184]
Hi Denis !

At the moment I'm using the default builtin solver `<double>` type with `coarsening::smoothed_aggregation` and `relaxation::spai0` I'm creating this issue to ask, what you think is better in terms of results accuracy and speed. All my matrix cases are SPD, I'm solving At*A x = At*b energy minimization (least squares problem) with dimentions from 7000x7000 to 200.000x200.000

I will also test today with CUDA

Appreciate your help !

**Comment by ddemidov** [comment]
I think you just need to try a couple of different options and see what is working best for your problems.
You could use the `examples/solver.cpp` to do that if you save your matrix into the matrix market format.

**Comment by mobereng** [comment]
Excellent ! let me validate what fits better for my current matrices, I will come back if I have an specific question, thanks !

**Comment by mobereng** [comment]
Hi again Denis, do you have a full example on CUDA only ? I'm having issues in the compilation process

**Comment by ddemidov** [comment]
See the last bit here: https://amgcl.readthedocs.io/en/latest/tutorial/poisson3Db.html

**Comment by mobereng** [comment]
Perfect, Already implemented that way but I ran into another issue of CUDA compilation:

![image](https://user-images.githubusercontent.com/69315094/107866802-e09db800-6e4a-11eb-82d8-4f01e8b81cda.png)

Does that mean I shoud use .cu files instead of .hpp that I'm currently using ?

**Comment by ddemidov** [comment]
Yes. Did you try that before asking here?

**Comment by mobereng** [comment]
Hi @ddemidov all good here, I will do several test and after that will close the issue, just in case I find some other doubt. Thanks for the help so far
