### ISSUE TITLE
Assert is used without including <cassert>

### ISSUE THREAD

**Issue by ilyapopov** [ddemidov/amgcl#185]
Several header files in amgcl use `assert`, but none of those include `<cassert>`. Which cases compilation fail.

```
amgcl/detail/inverse.hpp
amgcl/mpi/cpr.hpp
amgcl/mpi/coarsening/pmis.hpp
amgcl/backend/vexcl_static_matrix.hpp
amgcl/preconditioner/cpr.hpp
```

**Comment by ddemidov** [comment]
Thanks for reporting this! Would you care to provide a PR?

**Comment by ilyapopov** [comment]
Yes, I can in a few hours.
