### ISSUE TITLE
Compilation fails if Scotch is present but Ptscotch is not

### ISSUE THREAD

**Issue by ilyapopov** [ddemidov/amgcl#188]
Currently, [FindScotch.cmake](https://github.com/ddemidov/amgcl/blob/master/cmake/FindScotch.cmake) only requires availability of scotch. However, on Ubuntu, scotch and ptscotch are separate packages. If only scotch is installed, FindScotch succeeds, but then compiling examples in `examples/mpi` directory fails because of missing ptscotch. I see two options:

- Require both scotch and ptscotch in FindScotch
- Detect scotch and ptscotch separately and enable/disable examples based on ptscotch availability

**Comment by ddemidov** [comment]
Would #190 work on your system?

**Comment by ilyapopov** [comment]
No, this does not work. The problem is that `scotch_target` is conditioned on Scotch_INCLUDES being defined and does not take into account PTScotch. I guess the condition should be `Scotch_FOUND` instead. `find_package_handle_standard_args` function sets that variable if all include and library variables passed to it are defined. 

https://github.com/ddemidov/amgcl/blob/f7afd56719e0bf19357266ec878b7025f0cb4374/CMakeLists.txt#L204-L226

https://cmake.org/cmake/help/v3.20/module/FindPackageHandleStandardArgs.html

**Comment by ilyapopov** [comment]
I can confirm that after changing conditions https://github.com/ddemidov/amgcl/blob/f7afd56719e0bf19357266ec878b7025f0cb4374/CMakeLists.txt#L204 and https://github.com/ddemidov/amgcl/blob/f7afd56719e0bf19357266ec878b7025f0cb4374/CMakeLists.txt#L211 to use `Scotch_FOUND`, it skips building targets depending on scotch and everything compiles successfully.

**Comment by ddemidov** [comment]
I've just pushed 5ae3f2528f72851e446c7e4b7e861972021672e4 to #190.

**Comment by ilyapopov** [comment]
Yes, this works!
