### ISSUE TITLE
Moving to C++ 17 standard

### ISSUE THREAD

**Issue by ArturSalamatin** [ddemidov/amgcl#192]
I try to compile your library with the C++ Language Standard
ISO C++17 Standard (std:c++17)
in Visual Studio 2019

The compiler shows a number of errors since you extensively use functions
std::binary_function
std::auto_ptr
std::bind2nd
some members of std::allocator

They seem to be not part of the standard in C++17.

Do you plan/intent to update the library according to the new standard?

**Comment by ddemidov** [comment]
I don't think I use any of those functions in the code. The warnings are probably coming from outside the library.

**Comment by ArturSalamatin** [comment]
Yes, they are in the boost library.
Does your code still calls some of its functions?

**Comment by ddemidov** [comment]
Not in the core library:
```
grep -r std::binary_functions amgcl/
grep -r std::auto_ptr amgcl/
grep -r std::bind2nd amgcl/
```
There are two uses of `std::bind2d` in the examples:
```
grep -r std::bind2nd examples
examples/mpi/mba.hpp:    std::transform(a.begin(), a.end(), a.begin(), std::bind2nd(std::minus<T>(), b));
examples/mpi/mba.hpp:    std::transform(a.begin(), a.end(), a.begin(), std::bind2nd(std::multiplies<T>(), b));
```
which could be replaced with a lambda function, but that should not touch your code anyway.

**Comment by ddemidov** [comment]
Boost is used for the runtime interface. If you only use the compile-time interface, you can get rid of boost dependency by defining `AMGCL_NO_BOOST`.

**Comment by ArturSalamatin** [comment]
I explicitly put
AMGCL_NO_BOOST
in util.hpp

it works now.
