### ISSUE TITLE
No diagonal value in system matrix

### ISSUE THREAD

**Issue by orxshi** [ddemidov/amgcl#193]
I have a custom gmres code with ilu preconditioner which works with the given crs matrix format. I tested amgcl with the same matrix but got "No diagonal value in system matrix". In the code below `make_mat_crs` produces crs matrix. Since my version of gmres works fine with the given matrix, I suspect I am giving the matrix to amgcl incorrectly. How does the following code looks?

```
int n, nz_num;
std::vector<int> ia, ja;
std::vector<double> a, rhs;

make_mat_crs(n, nz_num, ia, ja, a, rhs); // user function to make crs format.

if (n == 0)
{
     return;
}

std::vector<double> x(n, 0.); 

amgcl::make_solver<
    amgcl::relaxation::as_preconditioner<Backend, amgcl::relaxation::ilu0>,
    amgcl::solver::gmres<Backend>
        > amgcl_solver(std::tie(n, ia, ja, a));

auto [iters, error] = amgcl_solver(rhs, x);
```

**Comment by ddemidov** [comment]
GMRES does not use inverses of the matrix diagonal, so it may be the case that some diagonal values are zero, and GMRES is still working fine. (Some) smoothers in amgcl (including ilu0) do rely on the non-zero diagonal values, so you may get this error.
You can try, for example, `chebyshev` relaxation instead of `ilu0`.

**Comment by ddemidov** [comment]
Another possibility is that the ilu preconditioner you used supports pivoting, while amgcl one does not.

**Comment by ddemidov** [comment]
Also, make sure the rows of the system matrix are sorted by column indices. amgcl::amg [does that](https://github.com/ddemidov/amgcl/blob/3a207307f9b567079db6e3476c4258aad106a071/amgcl/amg.hpp#L194) for you, but  `amgcl::relaxation::as_preconditioner` does not.

**Comment by orxshi** [comment]
chebyshev worked fine.
