### ISSUE TITLE
Handling of symmetric CSR matrices 

### ISSUE THREAD

**Issue by Sbai7** [ddemidov/amgcl#194]
Dear Denis, 

Thank you for this wonderful library. I've been working with it for groundwater flow and transport problems (mainly FDM) through the MATLAB interface in the past couple of years. 

Now, I'm planning to plug it into the framework of a legacy production code for groundwater flow modeling. The assembled conductance FE matrix for such problems is symmetric. Hence, my code stores the lower triangular part of it including the diagonals, though other CSR column and pointer arrays are conforming to the standard CSR format. 

Do I have to pass the full matrix values array to AMGCL solver routines? or there is an option to handle such special case.

Thanks for your support.

Regards, 
Adil

**Comment by ddemidov** [comment]
Hello Adil,

I'll copy my answer from this thread:

https://groups.google.com/g/amgcl/c/20qWFC9XOgs

> There is no optimization in amgcl for symmetric matrices at this point. Symmetric matrices are treated as non-symmetric ones, and the user has to provide both halves of the matrix.
I don't have any plans for this either, as it would require considerable effort to implement both the setup phase and the solution for all supported backends.

So unfortunately you would have to restore the full representation of the matrix before sending it to amgcl.
Something similar to (A + A^T) followed by halving the diagonal should work (and both matrix [sum](https://github.com/ddemidov/amgcl/blob/3a207307f9b567079db6e3476c4258aad106a071/amgcl/backend/builtin.hpp#L395-L398) and [transpose](https://github.com/ddemidov/amgcl/blob/3a207307f9b567079db6e3476c4258aad106a071/amgcl/backend/builtin.hpp#L342-L344) are available in amgcl).

**Comment by Sbai7** [comment]
Dear Denis,
Thank you. I'll manage to setup the matrix directly from my code.
