### ISSUE TITLE
The convergence theory for iterative methods as preconditioner

### ISSUE THREAD

**Issue by g873249824** [ddemidov/amgcl#196]
I'm sorry to distrub you for something having nothing to do with code. I am confused about the precondtioners for the solvers as CG, GMRES. As stated the book of Saad "Iterative methods for sparse linear systems", the flexiable variant of GMRES is seperately discussed for the cases  where M is not a constant operator (as you did in the AMGCL). I want to kown:
1.Whether is it the right way to use nested precondtioner for solvers like CG, GMRES? or I need to use the flexiable version of those solvers, especially CG. Maybe I need to get more literature to learn about that.
2.As far as I thought,  algebraic multigrid is not a constant operator as preconditioner, I am not sure it is right.

**Comment by ddemidov** [comment]
Flexible GMRES in amgcl was mainly introduced for use with composite preconditioners (such as Schur pressure correction), which use nested iterative solvers as components, which makes the overall preconditioner non-linear.

> 1.Whether is it the right way to use nested precondtioner for solvers like CG, GMRES? or I need to use the flexiable version of those solvers, especially CG. Maybe I need to get more literature to learn about that.

What do you mean by nested preconditioners here?

> 2.As far as I thought, algebraic multigrid is not a constant operator as preconditioner, I am not sure it is right.

It may or may not be linear depending on the relaxation operator. If the relaxation operator is linear, then I believe the complete V-cycle is linear.

**Comment by g873249824** [comment]
Thanks for your reply.
I used nested preconditioners representing solvers like CG with preconditioning as preconditioners. Whether it is right to use a non-linear (not constant) preconditioner for solvers like CG or GMRES rather than FGMRES,

**Comment by ddemidov** [comment]
Did you try this approach? If that works, then I say it is ok to use it :) (although I don't think you'll see any speedup from this)

**Comment by g873249824** [comment]
No, I haven't tried that yet. I think you give me the answer.
It is not right to do this.
