### ISSUE TITLE
Improve solving times for SPD matrices larger than 100.000x100.000

### ISSUE THREAD

**Issue by mobereng** [ddemidov/amgcl#199]
Hi Denis,

I have a problem that requires several Ax = b solves, my current goal is use AMG to improve the times of my final solution. The main issue I have at this point is that I can calculate an accurate solution for the first and second linear system solves, after the 3 one is stuck and if I add a simple `maxiter` limit to something like 100 or 200, it does not generates a proper result

Matrix and problem description:

1. Is an SPD matrix of 120000x120000 with over 2M nnz
2. Epsilon for error should be around 1e-4 and 1e-8
3. As it is SPD I have used CG solver

Those are the current [matrices](https://drive.google.com/drive/folders/1NmqoyEayeAts43KopEUY1s7JoPEVTcvm?usp=sharing)

NOTE: All have been tested as tutorial suggest with the `example/solver` file

So my question here is about changes on the relaxation and coarsening strategies and its parameters in order to improve the convergence of this matrices

**Comment by mobereng** [comment]
Case 0 execution:

`solver solver.type=cg solver.maxiter=100000 --matrix 0_ata.mtx --rhs 0_bx.mtx --scale --reorder`

Response:
![image](https://user-images.githubusercontent.com/69315094/116826142-8ca89280-ab60-11eb-8399-7affc2da5f1a.png)

**Comment by mobereng** [comment]
Case 1 execution:

solver solver.type=cg solver.maxiter=100000 --matrix 1_ata.mtx --rhs 1_bx.mtx --scale --reorder

Response:
![image](https://user-images.githubusercontent.com/69315094/116826191-cb3e4d00-ab60-11eb-95aa-7f7c80ea659e.png)

**Comment by mobereng** [comment]
Case 3 execution:

solver solver.type=cg solver.maxiter=100000 --matrix 2_ata.mtx --rhs 2_bx.mtx --scale --reorder

Response:

![image](https://user-images.githubusercontent.com/69315094/116826237-02acf980-ab61-11eb-83f5-f160e42938e6.png)

NOTE: Here no solution could be generated, stuck there for hours

**Comment by ddemidov** [comment]
The best I could come up with is ruge_stuben coarsening:
```
$ solver -A 1_ata.mtx -f 1_bx.mtx solver.tol=1e-4 \
    precond.coarsening.type=ruge_stuben solver.{type=cg,maxiter=4000} 
Solver
======
Type:             CG
Unknowns:         120660
Memory footprint: 3.68 M

Preconditioner
==============
Number of levels:    5
Operator complexity: 1.83
Grid complexity:     1.64
Memory footprint:    88.39 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0       120660        2317538     49.39 M (54.59%)
    1        55559        1467685     28.24 M (34.57%)
    2        15877         351531      6.97 M ( 8.28%)
    3         4524          88568      1.80 M ( 2.09%)
    4         1239          19655      1.99 M ( 0.46%)

Iterations: 303
Error:      9.70837e-05

[Profile:       8.336 s] (100.00%)
[  reading:     2.888 s] ( 34.64%)
[  setup:       0.180 s] (  2.16%)
[  solve:       5.268 s] ( 63.19%)
```
It still is not able to deal with cases starting with 3. 

The fact that Ruge-Stuben works better than smoothed aggregation probably means that you have a highly irregular grid, or a highly anisotropic problem. Maybe you need to somehow relax your system, or switch to a specialized preconditioner.

**Comment by mobereng** [comment]
Thanks Denis !

I'm currently trying to relax my system as I generate each matrix, I notice that when the matrix becomes diagonally dominant is the point when it starts to show the issue as you saw on cases after 3

Also if you have any ideas to relax that diagonal would be great

Thanks again

**Comment by ddemidov** [comment]
That is strange, as it should be easier to solve a system that is more diagonally dominant. What kind of problem are you solving?

**Comment by mobereng** [comment]
Is this one [Skeleton Extraction](https://www.cs.tau.ac.il/~dcor/articles/2008/Skeleton-Extraction.pdf) is a geometry problem which is composed by subsequent laplacian smoothing iterations

This is the description of the matrices involved:
![image](https://user-images.githubusercontent.com/69315094/117133902-da94e480-ad72-11eb-9977-428bc476a4ad.png)

Where Wh and Wl are diagonal matrices, L is the laplacian matrix and V is my RHS vector

**Comment by mobereng** [comment]
I'm currently solving it in Least Squares sense, so before applying the solver I do At*A and At*b

**Comment by ddemidov** [comment]
I have no experience with these kinds of problems, sorry. Can not even say if a multigrid preconditioner should in principle work here.

**Comment by mobereng** [comment]
No problems ! thanks for the help, they mention that the used a multigrid solver, I will continue validating to see if there's anything I can do
