### ISSUE TITLE
Epetra ->ViennaCL/Eigen->Epetra

### ISSUE THREAD

**Issue by skn123** [ddemidov/amgcl#20]
Hi Denis
Can you please provide an example of how to wrap a ViennaCL/Eigen sparse matrix to Epetra and vice-versa so that we can use amgcl or use Anasazi that is part of the trilinos project?

**Comment by ddemidov** [comment]
Hi,

I am not sure what exactly you are trying to achieve. In the context of amgcl, Epetra matrices may only be used for input during AMG setup, and ViennaCL may only be used as a backend. So the only thing I can think of involving both Epetra and ViennCL would be to setup a subdomain deflation solver for a (distributed) Epetra matrix and use it for parallel solution on multiple nodes using ViennaCL as a backend. There is no way to convert Epetra matrix to ViennaCL matrix and back in amgcl.
