### ISSUE TITLE
PARMETIS ERROR: Poor initial vertex distribution. Processor 0 has no vertices assigned to it!

### ISSUE THREAD

**Issue by lyz0530** [ddemidov/amgcl#200]
Hi, when I run the 3D poisson problem (MPI version), I get parmetis or pt-scotch errors, just like the title.
My matrix is created by myself. If use the naive partitioning, the result is right, but fail with parmetis or pt-scotch.
Can anyone tell me how to fix this issue? Thanks a lot.

_Partitioning[ParMETIS] 4 -> 4
PARMETIS ERROR: Poor initial vertex distribution. Processor 0 has no vertices assigned to it!
PARMETIS ERROR: Poor initial vertex distribution. Processor 2 has no vertices assigned to it!
Failed assumption: Error in ParMETIS
Offending processes: 0 1 2 3
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error in ParMETIS
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::runtime_error'
std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error in ParMETIS
  what():  Error in ParMETIS
  what():  Error in ParMETIS_

**Comment by ddemidov** [comment]
How do you distribute the matrix initially? The errors seem to suggest you have zero matrix rows on 0th and 2nd processors.

**Comment by lyz0530** [comment]
> How do you distribute the matrix initially? The errors seem to suggest you have zero matrix rows on 0th and 2nd processors.

I recompiled the parmetis static library, then it works.
However, the ptscotch still reports errors as below:

_Partitioning[PT-Scotch] 4 -> 4
(0): ERROR: (1): ERROR: (2): ERROR: (3): ERROR: SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
SCOTCH_dgraphInit: Scotch compiled with SCOTCH_PTHREAD and program not launched with MPI_THREAD_MULTIPLE
Failed assumption: SCOTCH error
Offending processes: 0 1 2 3
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  SCOTCH error
  what():  SCOTCH error
  what():  SCOTCH error
terminate called after throwing an instance of 'std::runtime_error'
  what():  SCOTCH error_

**Comment by ddemidov** [comment]
Try to replace `MPI_Init()` call with `MPI_Init_thread()`, as the error suggests. See an example here:

https://github.com/ddemidov/amgcl/blob/61d219699005743338a41768c41bca0a8678d24e/examples/mpi/call_mpi_lib.cpp#L20

**Comment by lyz0530** [comment]
> Try to replace `MPI_Init()` call with `MPI_Init_thread()`, as the error suggests. See an example here:
> 
> https://github.com/ddemidov/amgcl/blob/61d219699005743338a41768c41bca0a8678d24e/examples/mpi/call_mpi_lib.cpp#L20

Great! It works well. Thanks for your attention!
