### ISSUE TITLE
is there any example to obtain the original ordering solution x by x = Py in the Poisson probem (MPI version) ?

### ISSUE THREAD

**Issue by lyz0530** [ddemidov/amgcl#201]
Hi, when I try to obtain the original ordering solution x by x = Py of the poisson3Db problem, some errors happen. The printed info is below.

World size: 3
Matrix A.bin: 32768x32768
RHS b.bin: 32768x1
Partitioning[ParMETIS] 3 -> 3
Type:             BiCGStab
Unknowns:         10923
Memory footprint: 597.35 K

Number of levels:    3
Operator complexity: 1.56
Grid complexity:     1.13

level     unknowns       nonzeros
---------------------------------
    0        32768         223232 (63.91%) [3]
    1         3877         109817 (31.44%) [3]
    2          330          16222 ( 4.64%) [3]

Iters: 8
Error: 4.39412e-09

[poisson3Db MPI:     0.260 s] (100.00%)
[  partition:        0.080 s] ( 30.77%)
[  read:             0.000 s] (  0.00%)
[  setup:            0.110 s] ( 42.31%)
[  solve:            0.070 s] ( 26.92%)

*** glibc detected *** ./poisson3Db_mpi: double free or corruption (!prev): 0x000000000273d680 ***

my code has been pasted here, slightly different from the source code. **Different lines are marked.**
Can anyone help me? Thanks a lot.

```cpp
decltype(A) P; // **here**
if (world.size > 1) 
{
  prof.tic("partition");
  Partition part;

    // part(A) returns the distributed permutation matrix:
    //  auto P = part(*A); // **here**
    P = part(*A);  // **here**
    auto R = transpose(*P);

    // Reorder the matrix:
    A = product(*R, *product(*A, *P));

    // and the RHS vector:
    std::vector<double> new_rhs(R->loc_rows());
    R->move_to_backend(typename DBackend::params());
    amgcl::backend::spmv(1, *R, rhs, 0, new_rhs);
    rhs.swap(new_rhs);

    // Update the number of the local rows
    // (it may have changed as a result of permutation):
    chunk = A->loc_rows();
    prof.toc("partition");
}
// Initialize the solver:
prof.tic("setup");
Solver solve(world, A);
prof.toc("setup");

// Show the mini-report on the constructed solver:
if (world.rank == 0)
    std::cout << solve << std::endl;

// Solve the system with the zero initial approximation:
int iters;
double error;
std::vector<double> x(chunk, 0.0);
std::vector<double> x_original(chunk, 0.0);  // **here**

prof.tic("solve");
 std::tie(iters, error) = solve(*A, rhs, x);
prof.toc("solve");

P->move_to_backend(typename DBackend::params());  // **here**
amgcl::backend::spmv(1, *P, x, 0, x_original);  // **here**
```

**Comment by ddemidov** [comment]
The code looks mostly correct, except that you use wrong size for the `x_original`. Note that `chunk` is updated here:

https://github.com/ddemidov/amgcl/blob/61d219699005743338a41768c41bca0a8678d24e/tutorial/1.poisson3Db/poisson3Db_mpi.cpp#L107

and you need to use the original value:

https://github.com/ddemidov/amgcl/blob/61d219699005743338a41768c41bca0a8678d24e/tutorial/1.poisson3Db/poisson3Db_mpi.cpp#L47

Here is a patch to the tutorial code that works for me:
```patch
diff --git a/tutorial/1.poisson3Db/poisson3Db_mpi.cpp b/tutorial/1.poisson3Db/poisson3Db_mpi.cpp
index 5557f0f..3e3af04 100644
--- a/tutorial/1.poisson3Db/poisson3Db_mpi.cpp
+++ b/tutorial/1.poisson3Db/poisson3Db_mpi.cpp
@@ -45,6 +45,7 @@ int main(int argc, char *argv[]) {
     ptrdiff_t row_beg = std::min(rows, chunk * world.rank);
     ptrdiff_t row_end = std::min(rows, row_beg + chunk);
     chunk = row_end - row_beg;
+    ptrdiff_t chunk0 = chunk;
 
     // Read our part of the system matrix and the RHS.
     std::vector<ptrdiff_t> ptr, col;
@@ -75,6 +76,8 @@ int main(int argc, char *argv[]) {
     auto A = std::make_shared<amgcl::mpi::distributed_matrix<DBackend>>(
             world, std::tie(chunk, ptr, col, val));
 
+    std::shared_ptr<amgcl::mpi::distributed_matrix<DBackend>> P;
+
     // Partition the matrix and the RHS vector.
     // If neither ParMETIS not PT-SCOTCH are not available,
     // just keep the current naive partitioning.
@@ -90,7 +93,7 @@ int main(int argc, char *argv[]) {
         Partition part;
 
         // part(A) returns the distributed permutation matrix:
-        auto P = part(*A);
+        P = part(*A);
         auto R = transpose(*P);
 
         // Reorder the matrix:
@@ -127,6 +130,10 @@ int main(int argc, char *argv[]) {
     std::tie(iters, error) = solve(*A, rhs, x);
     prof.toc("solve");
 
+    P->move_to_backend(typename DBackend::params());
+    std::vector<double> x0(chunk0);
+    amgcl::backend::spmv(1, *P, x, 0, x0);
+
     // Output the number of iterations, the relative error,
     // and the profiling data:
     if (world.rank == 0)
```

**Comment by lyz0530** [comment]
> The code looks mostly correct, except that you use wrong size for the `x_original`. Note that `chunk` is updated here:
> 
> https://github.com/ddemidov/amgcl/blob/61d219699005743338a41768c41bca0a8678d24e/tutorial/1.poisson3Db/poisson3Db_mpi.cpp#L107
> 
> and you need to use the original value:
> 
> https://github.com/ddemidov/amgcl/blob/61d219699005743338a41768c41bca0a8678d24e/tutorial/1.poisson3Db/poisson3Db_mpi.cpp#L47
> 
> Here is a patch to the tutorial code that works for me:
> 
> ```diff
> diff --git a/tutorial/1.poisson3Db/poisson3Db_mpi.cpp b/tutorial/1.poisson3Db/poisson3Db_mpi.cpp
> index 5557f0f..3e3af04 100644
> --- a/tutorial/1.poisson3Db/poisson3Db_mpi.cpp
> +++ b/tutorial/1.poisson3Db/poisson3Db_mpi.cpp
> @@ -45,6 +45,7 @@ int main(int argc, char *argv[]) {
>      ptrdiff_t row_beg = std::min(rows, chunk * world.rank);
>      ptrdiff_t row_end = std::min(rows, row_beg + chunk);
>      chunk = row_end - row_beg;
> +    ptrdiff_t chunk0 = chunk;
>  
>      // Read our part of the system matrix and the RHS.
>      std::vector<ptrdiff_t> ptr, col;
> @@ -75,6 +76,8 @@ int main(int argc, char *argv[]) {
>      auto A = std::make_shared<amgcl::mpi::distributed_matrix<DBackend>>(
>              world, std::tie(chunk, ptr, col, val));
>  
> +    std::shared_ptr<amgcl::mpi::distributed_matrix<DBackend>> P;
> +
>      // Partition the matrix and the RHS vector.
>      // If neither ParMETIS not PT-SCOTCH are not available,
>      // just keep the current naive partitioning.
> @@ -90,7 +93,7 @@ int main(int argc, char *argv[]) {
>          Partition part;
>  
>          // part(A) returns the distributed permutation matrix:
> -        auto P = part(*A);
> +        P = part(*A);
>          auto R = transpose(*P);
>  
>          // Reorder the matrix:
> @@ -127,6 +130,10 @@ int main(int argc, char *argv[]) {
>      std::tie(iters, error) = solve(*A, rhs, x);
>      prof.toc("solve");
>  
> +    P->move_to_backend(typename DBackend::params());
> +    std::vector<double> x0(chunk0);
> +    amgcl::backend::spmv(1, *P, x, 0, x0);
> +
>      // Output the number of iterations, the relative error,
>      // and the profiling data:
>      if (world.rank == 0)
> ```

Wow, can't believe that I've got a reply so quickly! It works! GREAT!
