### ISSUE TITLE
OpenMP version is slower than MPI version?

### ISSUE THREAD

**Issue by lyz0530** [ddemidov/amgcl#203]
Hi Denis!

A new question. I tried both the built-in backend, i.e. openMP and  the mpi backend for a common SPD system.
I found that the openMP version is much slower than MPI version. I noticed that there is no partition step in openMP version.
It seems that the paradigms behind these two versions are different. 
How is the matrix partitioned in openMP version? Have you ever tried mt-metis?

Looking for your help!

**Comment by ddemidov** [comment]
There is no need to partition the matrix in the OpenMP case, since this is a shared memory paradigm and the parallelization is done using parallel for loops. It may be tricky to tune, especially if you have a NUMA machine. In this case you want to make sure that the chunks of omp loops for each thread stay on the NUMA node the memory was initially allocated on. Exporting environment variable [OMP_PLACES=cores](https://gcc.gnu.org/onlinedocs/libgomp/Environment-Variables.html) and using [`numactl -l ./my_program`](https://linux.die.net/man/8/numactl) might help.

How much slower is OpenMP in your case? How many iterations you get for OpenMP and MPI?

**Comment by lyz0530** [comment]
> There is no need to partition the matrix in the OpenMP case, since this is a shared memory paradigm and the parallelization is done using parallel for loops. It may be tricky to tune, especially if you have a NUMA machine. In this case you want to make sure that the chunks of omp loops for each thread stay on the NUMA node the memory was initially allocated on. Exporting environment variable [OMP_PLACES=cores](https://gcc.gnu.org/onlinedocs/libgomp/Environment-Variables.html) and using [`numactl -l ./my_program`](https://linux.die.net/man/8/numactl) might help.
> 
> How much slower is OpenMP in your case? How many iterations you get for OpenMP and MPI?

Nice! My problem: matrix size: 164238 x 164238, which needs to be solved 999 times with different rhs.
Following your guides, OpenMP performance has been improved, but yet unsatisfying if compared to MPI version, especially in more processes/threads cases.

Test results are listed (unit: second).
np/threads          MPI          OpenMP         speedup         OpenMP+NUMA         speedup
        5               39.36            81.44              2.07x                 44.48                             1.13x
      10               21.01            46.72              2.22x                 28.4                               1.35x
      20               13.14            42.56              3.24x                 21.64                             1.65x
      30               10.46            35.43              3.39x                 27.97                             2.67x
      40                9.79             36.69              3.75x                 27.4                               2.8x

The number of iteration looks almost the same, which changes among 12, 13, 18~22.

Do you have any other suggestions?
Thanks a lot!

**Comment by lyz0530** [comment]
> There is no need to partition the matrix in the OpenMP case, since this is a shared memory paradigm and the parallelization is done using parallel for loops. It may be tricky to tune, especially if you have a NUMA machine. In this case you want to make sure that the chunks of omp loops for each thread stay on the NUMA node the memory was initially allocated on. Exporting environment variable [OMP_PLACES=cores](https://gcc.gnu.org/onlinedocs/libgomp/Environment-Variables.html) and using [`numactl -l ./my_program`](https://linux.die.net/man/8/numactl) might help.
> 
> How much slower is OpenMP in your case? How many iterations you get for OpenMP and MPI?

Nice! My problem: matrix size: 164238 x 164238, which needs to be solved 999 times with different rhs.
Following your guides, OpenMP performance has been improved, but yet unsatisfying if compared to MPI version, especially in more processes/threads cases.

Test results are listed (unit: second).
np/threads          MPI          OpenMP         speedup         OpenMP+NUMA         speedup
        5               39.36            81.44              2.07x                 44.48                             1.13x
      10               21.01            46.72              2.22x                 28.4                               1.35x
      20               13.14            42.56              3.24x                 21.64                             1.65x
      30               10.46            35.43              3.39x                 27.97                             2.67x
      40                9.79             36.69              3.75x                 27.4                               2.8x

The number of iteration looks almost the same, which changes among 12, 13, 18~22.

Do you have any other suggestions?
Thanks a lot!

**Comment by ddemidov** [comment]
I think MPI scales better than OpenMP out of the box. It is in general harder to tune openmp on NUMA systems.

**Comment by ddemidov** [comment]
You could play with OMP environment from this page:
https://gcc.gnu.org/onlinedocs/libgomp/Environment-Variables.html
Especially things like OMP_SCHEDULE=static, OMP_WAIT_POLICY=active

**Comment by lyz0530** [comment]
Okay, I'll try. Many thanks!
