### ISSUE TITLE
One question about using GPU backend to speed up the Poisson3Db_mpi example

### ISSUE THREAD

**Issue by lyz0530** [ddemidov/amgcl#205]
Hi,  I try to play with the poisson3Db_mpi_vexcl.cpp.

In the tutorial, it says that _Use vex::Filter::Exclusive so that different MPI processes get different GPUS. Each process gets a single GPU_. I am a newman in GPU. Does these words mean that if I want to run 20 MPI processes,  20 GPUs should be installed?

I read your paper _AMGCL: An Efficient, Flexible, and Extensible Algebraic Multigrid Implementation_ and find that in the shared memory benchmarks, you only used an NVIDIA Tesla K80 GPU that combines two graphics processors. But in Fig.1, you tested upto 16 MPI processes...How does this happen? I'm puzzled. Can you give an explaination? 

Thanks.

**Comment by ddemidov** [comment]
> Does these words mean that if I want to run 20 MPI processes, 20 GPUs should be installed?

Yes, in a way. Or rather, the other way around: you should launch one MPI process per GPU available on a compute node.

> But in Fig.1, you tested upto 16 MPI processes

CPU-based versions in the figure use up to 16 cores. AMGCL/CUDA and CUSP plots are flat, because they only use single process/GPU (amgcl may use all available OpenMP cores during setup stage though).

**Comment by lyz0530** [comment]
>AMGCL/CUDA and CUSP plots are flat, because they only use single process/GPU

NVIDIA Tesla K80 has two graphics processors, so you used 2 processes in the test?
2 processes based on GPU (AMGCL/CUDA and CUSP) achieved a speedup of 3~4 compared to 16 processes based on CPU (AMGCL/OpenMP) if just taking the solution time into consideration?

**Comment by ddemidov** [comment]
I think just half of K80 (visible as a single GPU) was used in the experiments. CUSP can only use single GPU, and its performance is comparable to AMGCL/CUDA.

From the paper (p.543):

> When taking into consideration just the solution time (without setup), then both AMGCL/CUDA and CUSP are able to outperform CPU-based versions (with full utilization of the CPU cores) by a factor of 3–4. The total solution time for AMGCL/CUDA is only 30%better than that of AMGCL/OpenMP or Trilinos. This is explained by the fast convergence rate of the Poisson problem, which means the solution step of AMGCL/CUDA is not able to amortize the relatively expensive setup step.

The raw data for the figure is available here: https://github.com/ddemidov/amgcl/tree/master/docs/smem_data/poisson,
the columns is each of the files are 'number of processes', 'problem size', 'number of iterations', 'setup time', 'solve time'.

**Comment by lyz0530** [comment]
Got it. 

>This is explained by the fast convergence rate of the Poisson problem, which means the solution step of AMGCL/CUDA is not able to amortize the relatively expensive setup step.

Exactly! However, in my case, I repeat using the preconditioner for nearly 1,000 times, thus the setup step is relatively cheaper than the solution step. So you know, in these days, I has been trying to compare the performances among OpenMP, MPI and CUDA. Yesterday, we reached that MPI scales better than OpenMP for my case in NUMA. Today, I want to know MPI or CUDA, which one outperforms? I'll try cuda later. Thank you kindly.

By the way, do you think if it is possible to double the MPI version speed? For example, half the number of iteration, optimize the codes of solution step, etc. Can you give any suggestion about improvement?

**Comment by ddemidov** [comment]
> By the way, do you think if it is possible to double the MPI version speed? For example, half the number of iteration, optimize the codes of solution step, etc. Can you give any suggestion about improvement?

Not really, except to try available amgcl components (smoothers/coarseners) and their options for your specific problem.
You should set OMP_NUM_THREADS to 1 so as to not oversubscribe your CPU, but judging by your results I think you already did that.

**Comment by lyz0530** [comment]
>You should set OMP_NUM_THREADS to 1 so as to not oversubscribe your CPU

Yeah. I tested this environment variable before. However it had little effect on my case. I often ignore it. 

Anyway, thanks Dennis!
