### ISSUE TITLE
A bug in mm_reader on Windows OS

### ISSUE THREAD

**Issue by kvkol** [ddemidov/amgcl#206]
I came across at an out-of-range bug. The directions for reproducing it. 
1. Generate A.mtx and b.mtx using make_poisson.py from the 'examples' folder.
2. Pass A and b to poisson3Db. 
3. Exception is thrown because levelSet has a size of 768, while c gets a value of 1025 in the code given below.
                    for(auto a = backend::row_begin(A, node); a; ++a) {
                        ptrdiff_t c = a.col();
                        if (levelSet[c] == 0) {
 ...
}

**Comment by ddemidov** [comment]
Did you pass any command line arguments for `make_poisson.py`? I can not reproduce it so far:
```
[build/tutorial/1.poisson3Db] $ ../../../examples/make_poisson.py
[build/tutorial/1.poisson3Db] $ ./poisson3Db A.mtx b.mtx 
Matrix A.mtx: 32768x32768
RHS b.mtx: 32768x1
Solver
======
Type:             BiCGStab
Unknowns:         32768
Memory footprint: 1.75 M

Preconditioner
==============
Number of levels:    3
Operator complexity: 1.59
Grid complexity:     1.14
Memory footprint:    11.54 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0        32768         223232      8.48 M (62.80%)
    1         4192         114356      2.49 M (32.17%)
    2          346          17898    579.04 K ( 5.03%)

Iters: 7
Error: 5.23734e-09

[poisson3Db:     0.144 s] (100.00%)
[ self:          0.000 s] (  0.15%)
[  read:         0.100 s] ( 69.44%)
[  setup:        0.017 s] ( 11.71%)
[  solve:        0.027 s] ( 18.70%)
```

**Comment by ddemidov** [comment]
In fact, `levelSet` size is the number of rows in the matrix, so I can not see how `c = a.col()` could be out of bounds unless the matrix is non-square.

**Comment by kvkol** [comment]
It seems that there is a bug in mm_reader, and it manifests itself only on Windows. I "forgot" to mention that I compiled AMGL under Windows using CMake for Windows. Under Ubuntu I did not see any problems with the Poisson3Db tutorial sample. 
The sizes of A and b after mm_reader on Windows are 
Matrix A.mtx: 768x32768
RHS b.mtx: 768x1

**Comment by ddemidov** [comment]
Unfortunately, I don't have access to a windows computer. Could you pinpoint the reason for the bug there? It looks like `mm_reader` is only using standard iostream operations, so I am not sure what could go wrong there.

Also, to exclude the other possibility, is the matrix generated correctly for you? The first few lines of `A.mtx` should look like this:
```
%%MatrixMarket matrix coordinate real symmetric
%
32768 32768 128000
1 1 1.000000000000000e+00
2 1 -1.666666666666667e-01
2 2 1.000000000000000e+00
3 2 -1.666666666666667e-01
3 3 1.000000000000000e+00
4 3 -1.666666666666667e-01
4 4 1.000000000000000e+00
```

**Comment by kvkol** [comment]
> Could you pinpoint the reason for the bug there?
ОК, I'll check it.
> I don't have access to a windows computer. 
Pity. I think many people use your lib under Windows. With the help of Win CMake, everything compiles without any problems. 

The matrix looks OK. The first few lines are the same as yours -->
%%MatrixMarket matrix coordinate real symmetric
%
32768 32768 128000
1 1 1.000000000000000e+00
2 1 -1.666666666666667e-01
2 2 1.000000000000000e+00
3 2 -1.666666666666667e-01
3 3 1.000000000000000e+00
4 3 -1.666666666666667e-01
4 4 1.000000000000000e+00

**Comment by kvkol** [comment]
The third line is read as "768 32768 128000." To be exact, it is first read correctly in the loop
do {
                pos = f.tellg();
                precondition(std::getline(f, line), format_error("unexpected eof"));
            } while (line[0] == '%');
But then the line
f.seekg(pos);
returns us back at an incorrect position. I suspect that on line 2 in A.mtx there is some Unix symbol that is wrongly interpreted, so that tellg() gives a wrong pos.

**Comment by ddemidov** [comment]
Ok, that makes things more clear. This seems to be relevant:
https://stackoverflow.com/questions/12252075/ifstream-tellg-not-returning-the-correct-position

Could you please check if the following patch helps?
```patch
diff --git a/amgcl/io/mm.hpp b/amgcl/io/mm.hpp
index 84fc709..d1d6feb 100644
--- a/amgcl/io/mm.hpp
+++ b/amgcl/io/mm.hpp
@@ -52,7 +52,7 @@ namespace io {
 class mm_reader {
     public:
         /// Open the file by name
-        mm_reader(const std::string &fname) : f(fname.c_str()) {
+        mm_reader(const std::string &fname) : f(fname.c_str(), std::ios::binary) {
             precondition(f, "Failed to open file \"" + fname + "\"");
 
             // Read banner.
```

**Comment by ddemidov** [comment]
The patch above should probably work everywhere except older Mac systems, but still, using `std::getline` to read from binary file sounds dangerous. 681bfc71edf6c3721109bd0f263b33c92ec3ba2e should be more reliable as it removes the need to remember the file position.

**Comment by kvkol** [comment]
> Could you please check if the following patch helps?
Sorry, I cannot do it before Monday.

**Comment by kvkol** [comment]
Denis, to be honest, I would say the entire code of mm_read is
overcomplicated. For such things as a reader, the rule "the simpler, the
better " is usually true.

**Comment by ddemidov** [comment]
I wholeheartedly agree with the "simpler is better" principle, and any suggestions are welcome. Do you have anything specific in mind?

**Comment by kvkol** [comment]
Denis, I checked your fix on Windows 10. It works fine.

**Comment by ddemidov** [comment]
Thanks for confirming!
