### ISSUE TITLE
Details of the prolongation smoother and tentative prolongator of the smoothed aggregation in amgcl

### ISSUE THREAD

**Issue by lyz0530** [ddemidov/amgcl#207]
Hi Denis!

I have read some papers about smoothed aggregation (SA) methods. You know, the choice of the prolongation smoother and tentative prolongator is the spirit of one SA method. I am curious about the construction of these two objects in amgcl. Can you explain briefly, or is there any literature to recommend?

Thanks.

**Comment by ddemidov** [comment]
The code for the tentative prolongation construction is here:

https://github.com/ddemidov/amgcl/blob/681bfc71edf6c3721109bd0f263b33c92ec3ba2e/amgcl/coarsening/tentative_prolongation.hpp#L112-L227

The code references [Vanek, Petr, Marian Brezina, and Jan Mandel. "Convergence of algebraic multigrid based on smoothed aggregation." Numerische Mathematik 88.3 (2001): 559-579.](https://link.springer.com/content/pdf/10.1007/s211-001-8015-y.pdf)

Smoothing is applied here:

https://github.com/ddemidov/amgcl/blob/681bfc71edf6c3721109bd0f263b33c92ec3ba2e/amgcl/coarsening/smoothed_aggregation.hpp#L147-L234

and the code references [Vaněk, Petr, Jan Mandel, and Marian Brezina. Algebraic multigrid by smoothed aggregation for second and fourth order elliptic problems. Computing 56.3 (1996): 179-196.](https://link.springer.com/content/pdf/10.1007/BF02238511.pdf)

**Comment by lyz0530** [comment]
Got it. Very kind of you!
