### ISSUE TITLE
Using CPR with CUDA backend

### ISSUE THREAD

**Issue by Tongdongq** [ddemidov/amgcl#210]
Does the CUDA backend support CPR?
I've tried to adapt `tutorials/1.poisson3Db/poisson3Db_cuda.cu` to use CPR with the definitions in `examples/cpr.cpp`.
This is the error
```
../../amgcl/backend/cuda.hpp(383): error: static assertion failed with "Unsupported value type for cuda backend"
```
The cuda backend appears the only one that has that `static_assert(std::is_same<real, float>::value || std::is_same<real, double>::value, "Unsupported value type for cuda backend");`

I'd like to try it in [opm-simulators](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/linalg/bda/amgclSolverBackend.cu).

**Comment by Tongdongq** [comment]
I've made a blocked ilu0-bicgstab solver in cusparse that worked. In particular the `cusparseXbsrmv()` and `cusparseXbsrilu02()` were used.
It probably doesn't matter, since I need to use amg anyway, so I'll try the VexCL-CUDA solution.

**Comment by ddemidov** [comment]
Thanks for pointing the block versions out. It does look like extending the cuda backend to support block values should be possible. I am not sure when (or if) that would be available, so using VexCL-CUDA should be the easiest option for now.

**Comment by Tongdongq** [comment]
I got that working now, thanks!
