### ISSUE TITLE
Two uninitialized fields

### ISSUE THREAD

**Issue by kvkol** [ddemidov/amgcl#211]
Dear Denis, 
my compiler produces a warning about uninitialized fields (I use AMGCL as a submodule connected to Github), and I would like to have a zero number of warnings ;-) Could I ask you to initialize those fields somehow so that I could get rid of the warnings (see below)?
...amgcl/amgcl/amg.hpp:347:13: warning: 2 uninitialized fields at the end of the constructor call [clang-analyzer-optin.cplusplus.UninitializedObject]
[build]             level() {}
[build]             ^
.../amgcl/amgcl/amg.hpp:313:20: note: uninitialized field 'this->m_rows'
[build]             size_t m_rows, m_nonzeros;
[build]                    ^
.../amgcl/amgcl/amg.hpp:313:28: note: uninitialized field 'this->m_nonzeros'
[build]             size_t m_rows, m_nonzeros;

**Comment by ddemidov** [comment]
Thanks, should be fixed by 3fd81fe.
