### ISSUE TITLE
Advice about understand block coarse strategy

### ISSUE THREAD

**Issue by qzxuhui** [ddemidov/amgcl#213]
Sir, I am using amgcl.
I come from https://github.com/ddemidov/amgcl/issues/175.
We can find using block information the solver can obtain a great performance boost.
I am really interested in how a coarse grid can be established and how the block information can help to gain performance.
Do you have some suggested material about how to understand the block version?
Maybe some books, articles, or papers?
I apologize if it is a stupid problem. Thanks for your time.

**Comment by ddemidov** [comment]
There is a paper [1], where the block values are considered as a possible acceleration strategy. The code for the paper is available here: https://github.com/ddemidov/cppstokes_benchmarks

[1] Demidov, D., Mu, L., & Wang, B. (2021). Accelerating linear solvers for Stokes problems with C++ metaprogramming. Journal of Computational Science, 49, 101285. [arxiv:2006.06052](https://arxiv.org/abs/2006.06052)

**Comment by qzxuhui** [comment]
Thanks sir.
