### ISSUE TITLE
How to iterate Vcycles by myself?

### ISSUE THREAD

**Issue by stigersh** [ddemidov/amgcl#230]
Thank you so much for releasing this package.
I'm comparing several iterative solvers, thus I would like to have a comparable framework where I can test the convergence of the algebraic multi grid solver against others.
I'm a bit lost in the code hierarchies and structure, how can I isolate and run a single Vcycle iteration in a loop where I can track my metrics for the result and measure times - like when given A, rhs, and initial solution in previous_x, we like to output 
x s.t. Ax=rhs

solver()
solver.init(A)
while (my convergence criteria)
    x = solver.single_vcycle(previous_x, rhs)
    save_my_error_metrics_and_iteration_time
    previous_x=x

Thanks again!
*I'm using eigen backend

**Comment by ddemidov** [comment]
There is `amgcl::amg::cycle(f,x)` method you could use:

https://github.com/ddemidov/amgcl/blob/c71ab45f911771c108b1842ea7cd11b62432bbf3/amgcl/amg.hpp#L271-L279

Instead of a complete solver you could create just the AMG preconditioner:

```cpp
amgcl::amg<
    Backend,
    amgcl::coarsening::smoothed_aggregation,
    amgcl::relaxation::spai0
    > AMG(A, prm);
```
 and call `AMG.cycle(rhs, x)` in a loop

**Comment by stigersh** [comment]
Thank you! I will try it out
