### ISSUE TITLE
Any way to reuse preconditioner?

### ISSUE THREAD

**Issue by njsyw1997** [ddemidov/amgcl#243]
Hi, I am trying to use AMGCL to solve a dynamic problem. Since in each time step, the system matrix will not change a lot, I want to reuse the preconditioner in continious steps. Can I temporarily save the preconditioner for reuse?

**Comment by ddemidov** [comment]
You could use the same preconditioner with a different matrix using the `solve(A, f, x)` signature:
https://amgcl.readthedocs.io/en/latest/components/coupled_solvers.html#_CPPv4I000ENK5amgcl11make_solverclENSt5tupleI6size_t11scalar_typeEERK6MatrixRK9VectorRHSR7VectorX

You could also use the `rebuild()` method of the preconditioner to update the AMG hierarchy for the new matrix:

https://amgcl.readthedocs.io/en/latest/components/preconditioners.html#_CPPv4I0EN5amgcl3amg7rebuildEvRK6MatrixRK14backend_params

Also, see the relevant discussions here:

- https://groups.google.com/g/amgcl/c/FL5llFOKv9E
- https://groups.google.com/g/amgcl/c/RdQ2F_QTn7w

**Comment by njsyw1997** [comment]
Thank you very much! That's exactly what I need.
