### ISSUE TITLE
How to handle symmetric Systems ?

### ISSUE THREAD

**Issue by zx-82** [ddemidov/amgcl#246]
Hi,

maybe I'm missing something, but from reading the docs/tutorial it has not become clear how to best handle symmetric matrices (e.g. for the CG iterative solver).
Could you provide an example of a setup for solving a symmetric system (i.e. storing & processing only of the upper/lower triangle) ?

Thanks

**Comment by ddemidov** [comment]
Hi, there is no shortcut in amgcl for handling symmetric systems. You have to fill out both parts of the input matrix, even if it is symmetric.

**Comment by zx-82** [comment]
Thanks for the clarification.
