### ISSUE TITLE
QR decomposition fails

### ISSUE THREAD

**Issue by dondieselkopf** [ddemidov/amgcl#26]
Hi Denis,

Hope you are doing great. Nice to see that your project keeps advancing. There is a minor issue which I cannot really sort out myself. I recently tried to use your QR decomposition on a complex matrix. However, I get a few nan's in the result. When using Mathematica things seem okay. I have added some code in your QR test case to check it:

https://github.com/dondieselkopf/amgcl/commit/355c521c631fe7859ca952c5692bb9302aef2dbf

Input matrix can be found here: [X.tar.gz](https://github.com/ddemidov/amgcl/files/385697/X.tar.gz)

I don't know if the problem is with the code or with my matrix. Maybe you have time to take a look at it.

Cheers,
Chris

PS: There was a minor bug in the mm.hpp file (see my commit).

**Comment by ddemidov** [comment]
Thanks for reporting this, I'll try to look into the problem.

**Comment by ddemidov** [comment]
Strange, but I don't  get a test failure from your example. What compiler and compiler flags do you use?

**Comment by ddemidov** [comment]
Ok, the problem seems to be that the input matrix contains 0 on the diagonal (X[18][18] == 0). The QR algorithms that is used in amgcl does not use pivoting, hence the problem. I don't think pivoting is required for matrices that are decomposed during amg aggregation phase, so I am not sure I want to switch to pivoted QR. I would consider a PR though :).

**Comment by dondieselkopf** [comment]
Thanks for looking into this. I have tested on a 32bit with gcc 4.8.5 and a 64bit with gcc 4.9.0. The test passes on the 64bit machine. But it may well be that the nan's are ignored. I would like to try to switch off the optimization. How can I do that? I can't see the O-flag...

**Comment by dondieselkopf** [comment]
Okay, so the matrix is a bit weird... I am not sure if I have the time to create a PR but I will take a look at it.

**Comment by ddemidov** [comment]
Re switching optimization off: this is not relevant anymore, bu you can do this by setting `CMAKE_BUILD_TYPE=Debug` (default in amgcl is `RelWithDebInfo`).

**Comment by dondieselkopf** [comment]
Actually I am not sure if this is the real cause of the problem. When switching off pivoting in Mathematica (QRDecomposition[X,Pivoting->False]), the result seems perfectly fine...  Altough I am not sure what Mathematica is really doing under the hood ...

**Comment by ddemidov** [comment]
Well, the first nan comes from [this line](https://github.com/ddemidov/amgcl/blob/master/amgcl/detail/qr.hpp#L70). `absV0` is norm of k-th diagonal element and is zero for k==18.

**Comment by dondieselkopf** [comment]
It seems that `normV` is also zero ...

**Comment by ddemidov** [comment]
I have to admit I am not an expert in QR decomposition, so may be there is something wrong  with the code. I can confirm the QR of the matrix works in python:
```py
In [1]: from scipy.io import mmread
In [2]: from scipy.linalg import qr
In [3]: X = mmread('X.mm')
In [4]: q,r = qr(X, pivoting=False)
In [5]: q.flatten().max()
Out[6]: (0.99974567612893361+3.0671934714591945e-06j)
```

**Comment by ddemidov** [comment]
I think `normV == 0` means k-th Householder vector is zero and there is nothing left to do in the k-th iteration. Adding the lines
```cpp
                if (normV == 0) {
                    diagR[k] = math::zero<value_type>();
                    betaR[k] = 0;
                    continue;
                }
```
before computation of `absV0` seems to work for your matrix (norm of QR-A has order of 1e-12), but I am not yet sure this is the right thing to do. Also, the values in Q and R are different from what scipy returns.

**Comment by ddemidov** [comment]
No, the results are wrong with this change: http://nbviewer.jupyter.org/gist/anonymous/fed742d70bf4a7c3db9f8c11adc82f48

**Comment by dondieselkopf** [comment]
Hm, thanks for the effort. I am much less of an expert on QR decompostition, so I think I will stick with Lapack for the time being.

**Comment by ddemidov** [comment]
Linpack should also be faster. I only need qr for small matrices in amgcl, so no effort was spent on optimization.

**Comment by ddemidov** [comment]
Chris, I've ported implementation of QR factorization from non-blocked LAPACK code. It is able to factorize your matrix, and also I think the code is a bit clearer.

**Comment by dondieselkopf** [comment]
Wow, that's amazing! Thanks for the effort. Will test it with a few other matrices asap. Hope you can make use of the code yourself. I will then change back from LAPACK to your implementation, which gets me rid of that dependency. Thanks again, Denis.

**Comment by ddemidov** [comment]
The latest commit improves performance of the QR decomposition by switching to column major storage order. The interface has slightly changed: The QR class now has additional template parameter that specifies storage order of the input matrix (either `amgcl::detail::col_major` or `amgcl::detail::row_major`). Also, the matrix `Q` is no longer created in `QR::compute()`. Instead, one should call `QR::compute_q()` method explicitly after `QR::compute()` is finished.

With this, the setup time for `spai1` relaxation has been reduced by a factor of two in some cases (which, sadly, still does not make `spai1` an affordable smoother):

**Before:**
```
./examples/solver_ref -n 128 -p precond.relax.type=spai1
coarsening:          smoothed_aggregation
relaxation:          spai1
Number of levels:    4
Operator complexity: 1.57
Grid complexity:     1.13

level     unknowns       nonzeros
---------------------------------
    0      2097152       14581760 (63.72%)
    1       263552        7918340 (34.60%)
    2         6349         382413 ( 1.67%)
    3           79           2969 ( 0.01%)

Iterations: 11
Error:      2.27667e-09

[Profile:         29.197 s] (100.00%)
[  assembling:     0.110 s] (  0.38%)
[  setup:         23.547 s] ( 80.65%)
[  solve:          5.537 s] ( 18.96%)
```

**After:**
```
./examples/solver -n 128 -p precond.relax.type=spai1
coarsening:          smoothed_aggregation
relaxation:          spai1
Number of levels:    4
Operator complexity: 1.57
Grid complexity:     1.13

level     unknowns       nonzeros
---------------------------------
    0      2097152       14581760 (63.72%)
    1       263552        7918340 (34.60%)
    2         6349         382413 ( 1.67%)
    3           79           2969 ( 0.01%)

Iterations: 11
Error:      2.27667e-09

[Profile:         17.161 s] (100.00%)
[  assembling:     0.112 s] (  0.65%)
[  setup:         12.118 s] ( 70.61%)
[  solve:          4.928 s] ( 28.71%)
```

**Comment by dondieselkopf** [comment]
Great! I would really like to test it but I am afraid I am running short of time before going on holiday. Will give it a try afterwards, which is around the beginning of September.

**Comment by ddemidov** [comment]
Can this be closed?

**Comment by dondieselkopf** [comment]
I didnt't find time to try your code yet. Will look at it this month. The issue can be closed, however. Thanks, again.
