### ISSUE TITLE
scoper_ticker

### ISSUE THREAD

**Issue by ArturSalamatin** [ddemidov/amgcl#268]
What is [`scoped_ticker`](https://github.com/ddemidov/amgcl/blob/42ee9da2057153b1aef734e8e462c846a33aa805/amgcl/profiler.hpp#L113C24-L113C25) designed for?
How could I use it my code? Do you have usage examples in the amgcl-library?

**Comment by ddemidov** [comment]
`scoped_tic` does a tic when it is constructed, and does a toc when it goes out of scope. So it measures the dureation of the code block it is created in. One of the [examples](https://github.com/search?q=repo%3Addemidov%2Famgcl%20scoped_tic&type=code): 

https://github.com/ddemidov/amgcl/blob/42ee9da2057153b1aef734e8e462c846a33aa805/examples/solver.cpp#L591-L594
