### ISSUE TITLE
Can amgcl support for a Schur solver which's matrix are mix block size?

### ISSUE THREAD

**Issue by EntropyAran** [ddemidov/amgcl#270]
Hi,

I'm using amgcl to solve a structural problem from Bundle Adjustment. It looks like this:

![output](https://github.com/ddemidov/amgcl/assets/9927879/6725b286-e590-46ad-9c0c-e623c5c177e7)

[A  B^T ] = [p1]
[B    C   ]  = [p2]

The A part consists of block matrixs in size of 3x3
And  6x6 in  C part ,  6x3 in part B.
3x1 in p1, 6x1 in p2.

Since the size of part A of the matrix is much larger than that of C, I want to use the Schur complementary method.
The tutorial in Stokes-like problem takes block matrixs in size of 3x3, and my code looks like:

```cpp
 typedef amgcl::static_matrix<double, 3, 3>
     dmatA_type; // matrix A
 typedef amgcl::static_matrix<double, 3, 1>
     dvecA_type; // Vector  p1
 typedef amgcl::static_matrix<float, 3, 3>
     smatA_type; //  matrix A in single precision

 typedef amgcl::static_matrix<double, 6, 6>
     dmatB_type; // matrix B
 typedef amgcl::static_matrix<double, 6, 1>
     dvecB_type; // Vector p2
 typedef amgcl::static_matrix<float, 6, 6>
     smatB_type; // matrix B in single precision

 typedef amgcl::backend::vexcl<double>
     SBackend; // the outer iterative solver backend
 typedef amgcl::backend::vexcl<smatB_type> PBackend; // the PSolver backend
 typedef amgcl::backend::vexcl<smatA_type> UBackend; // the USolver backend

 typedef amgcl::make_solver<
     amgcl::preconditioner::schur_pressure_correction<
         amgcl::make_block_solver<
             amgcl::amg<UBackend, amgcl::coarsening::aggregation,
                        amgcl::relaxation::ilu0>,
             amgcl::solver::preonly<UBackend>>,
         amgcl::make_solver<amgcl::relaxation::as_preconditioner<
                                PBackend, amgcl::relaxation::ilu0>,
                            amgcl::solver::preonly<PBackend>>>,
     amgcl::solver::cg<SBackend>>
     Solver;
```

My question is :
1、 Does the amgcl supprot this kind of mix_block_size problem?
2、how to define and init the RHS part?
3、Need I define the part of B in size of 6x3?

Thanks for all the great work on AMGCL!

**Comment by ddemidov** [comment]
Schur-complement does not require the matrix to be structured in any way, you just have to pass the mask for the pressure variables:

 https://github.com/ddemidov/amgcl/blob/42ee9da2057153b1aef734e8e462c846a33aa805/tutorial/4.Stokes/stokes_ucube.cpp#L84-L85
 
 In the example it just happens to be regular. The advantage of regularity is that you can use block-valued solver on the U-part of the matrix, but again, it is not a requirement.

**Comment by EntropyAran** [comment]
thank you for the fast reply!
