### ISSUE TITLE
Could Not find Boost: missing: program_options 

### ISSUE THREAD

**Issue by ShuoCseu** [ddemidov/amgcl#271]
When I executed this project as follows,
```
git clone https: /lgithub.com/ ddemidov / amgclcd ./ amgcl
cmake -Bbuild -DAMGCL_BUILD_TESTS=ON -DAMGCL_BUILD_EXAMPLES=ON .
cmake --build build
```
I have already installed Boost:
`sudo apt install libboost-all-dev`

 I encountered the following problems：
`Could NOT find Boost: missing: program_options (found/usr/[local/lib/CMake/ Boost-1.80.8/BoostConfig.cmake (found version "1.80.0"))`

How should I deal with this issue? Thank you very much.

**Comment by ShuoCseu** [comment]
<img width="618" alt="58ade48e92a76446a35ceaaf88de96d" src="https://github.com/ddemidov/amgcl/assets/127945568/7487299a-cd91-4476-b505-dada425f6503">

**Comment by ShuoCseu** [comment]
<img width="527" alt="147538d0e0c996e7628ab182871ac72" src="https://github.com/ddemidov/amgcl/assets/127945568/f837ffda-129f-4973-a0fb-904471cdce71">

**Comment by ddemidov** [comment]
I can not reproduce the issue, and I don't remember seeing anything similar. Could this be a problem with your system? There is an example of building amgcl on ubuntu as a dockerfile here: https://github.com/ddemidov/amgcl/tree/master/docker, and I don't see any major differences with what you do.

**Comment by ShuoCseu** [comment]
> I can not reproduce the issue, and I don't remember seeing anything similar. Could this be a problem with your system? There is an example of building amgcl on ubuntu as a dockerfile here: https://github.com/ddemidov/amgcl/tree/master/docker, and I don't see any major differences with what you do.

Yes it's because of my system. After rebuilding my system, I successfully run this program. Thanks so much.
