### ISSUE TITLE
Solving complex systems with static_matrix as value_type

### ISSUE THREAD

**Issue by msandre** [ddemidov/amgcl#28]
Hi,

I have encountered a few problems while attempting to solve complex systems of equations with a nested value_type, i.e., static_matrix<std::complex<double>,int N,int N>. The modifications I needed to perform in static_matrix.hpp are below:
```c++
// struct scalar_of< static_matrix<T, N, M> >
  typedef typename scalar_of<T>::type type;

// struct adjoint_impl< static_matrix<T, N, M> >
y(j,i) = adjoint(x(i,j));

// struct inner_product_impl< static_matrix<T, N, 1> >
sum += x(i) * adjoint(y(i));

// struct inner_product_impl< static_matrix<T, N, M> >
sum += x(k,i) * adjoint(y(k,j));

// struct norm_impl< static_matrix<T, N, M> >
static typename scalar_of<T>::type
get(const static_matrix<T, N, M> &x) {
      T s = math::zero<T>();
      for(int i = 0; i < N * M; ++i)
           s += x(i) * adjoint(x(i));
          return sqrt(std::abs(s));
}

// struct inverse_impl< static_matrix<T, N, N> >
T d = 1. / A(k,k);
```
Additionally, the compiler was attempting to perform division of an integer by complex in some other parts of the amgcl library due to expressions such as T d = 1 / A(k,k). I added the following work around to my local file.
```c++
namespace std
{
  inline complex<double>
  operator/(const int& x, const complex<double>& y)
  {
    return static_cast<double>(x) / y;
  }
}
```
I have not tested this solution extensively, but have not encountered further issues. Is it possible to make similar changes in amgcl?

**Comment by ddemidov** [comment]
Hi, I've tried to merge your changes with #29. I tried to make those a little more generic than you initially proposed though. Can you please test if this works for you? Alternatively, you can send me a block-complex matrix, and I'll test correctness of the solution myself.

**Comment by msandre** [comment]
Hi, I tested your solution and it works. Thanks for your help.

**Comment by ddemidov** [comment]
Thanks, merged!
