### ISSUE TITLE
using zero-copy backend

### ISSUE THREAD

**Issue by dahtah** [ddemidov/amgcl#30]
Dear Denis

Thanks for your work on amgcl. I'm getting a compile-time error when using the zero-copy backend, and I'm not sure where the problem is coming from. I simply took the Poisson demo straight from the docs, and changed: 
```
Solver solve( boost::tie(n, ptr, col, val) );
```
to 
```
Solver solve( amgcl::adapter::zero_copy(n, &ptr[0], &col[0], &val[0]) );
```
which gives me:

In file included from test_amgcl.cpp:7:
../ownCloud/stencils/inst/include/amgcl/adapter/zero_copy.hpp:67:9: error: 
      implicit instantiation of undefined template
      'boost::STATIC_ASSERTION_FAILURE<false>'
        BOOST_STATIC_ASSERT(sizeof(Ptr) == sizeof(ptr_type));
        ^
/usr/include/boost/static_assert.hpp:169:13: note: expanded from macro
      'BOOST_STATIC_ASSERT'
            sizeof(::boost::STATIC_ASSERTION_FAILURE< BOOST_STATIC_ASSER...
            ^
/usr/include/boost/smart_ptr/make_shared_object.hpp:819:17: note: in
      instantiation of function template specialization
      'amgcl::adapter::zero_copy_adapter<double>::zero_copy_adapter<int, int>'
      requested here
    ::new( pv ) T( a1, a2, a3, a4 );
                ^
../ownCloud/stencils/inst/include/amgcl/adapter/zero_copy.hpp:85:19: note: in
      instantiation of function template specialization
      'boost::make_shared<amgcl::adapter::zero_copy_adapter<double>, unsigned
      long, const int *, const int *, const double *>' requested here
    return boost::make_shared< zero_copy_adapter<Val> >(n, ptr, col, val);
                  ^
test_amgcl.cpp:85:32: note: in instantiation of function template specialization
      'amgcl::adapter::zero_copy<int, int, double>' requested here
  Solver solve(amgcl::adapter::zero_copy(n, ptr.data(), col.data(), val....
                               ^
/usr/include/boost/static_assert.hpp:87:26: note: template is declared here
template <bool x> struct STATIC_ASSERTION_FAILURE;
                         ^
In file included from test_amgcl.cpp:7:
../ownCloud/stencils/inst/include/amgcl/adapter/zero_copy.hpp:68:9: error: 
      implicit instantiation of undefined template
      'boost::STATIC_ASSERTION_FAILURE<false>'
        BOOST_STATIC_ASSERT(sizeof(Col) == sizeof(col_type));
        ^
/usr/include/boost/static_assert.hpp:169:13: note: expanded from macro
      'BOOST_STATIC_ASSERT'
            sizeof(::boost::STATIC_ASSERTION_FAILURE< BOOST_STATIC_ASSER...
            ^
/usr/include/boost/static_assert.hpp:87:26: note: template is declared here
template <bool x> struct STATIC_ASSERTION_FAILURE;

Is some extra casting required?

**Comment by ddemidov** [comment]
Hi,

`zero_copy` is not a *backend*, its an *adapter*, which means it handles conversion from your matrix structure into internal amgcl structures. `zero_copy` it tries to get rid of unnecessary copies by pointing internal amgcl structures directly to your data. This means that your data has to be binary compatible with internal amgcl structures. That is, your `ptr` and `col` arrays has to be 64bit integer types (signed or unsigned). In order to fix this, you could either change your representation of the sparse matrix, or you could stick with `boost::tuple` adapter.

**Comment by dahtah** [comment]
Got it, thanks. Setting all std::vector<int> to std::vector<long> in the Poisson demo solves the problem.
