### ISSUE TITLE
GMRES gives NaN at low maxiter

### ISSUE THREAD

**Issue by dondieselkopf** [ddemidov/amgcl#32]
I am seeing a slightly strange behaviour here. Maybe you could take a quick look at is. I have a complex system I want to solve:

[A.tar.gz](https://github.com/ddemidov/amgcl/files/572907/A.tar.gz)
[rhs.tar.gz](https://github.com/ddemidov/amgcl/files/572915/rhs.tar.gz)

When I use GMRES with _solver.maxiter_ set to 100, the result looks fine. However, when I use _solver.maxiter_ with 25 I get NaN. Other solvers do not show this behaviour.

To me this seems a bit odd... Thanks for looking at it.

Chris

**Comment by ddemidov** [comment]
I've added a complex solver to examples with e48b203. With that, I can not reproduce the error:
```
$ ./solver_complex -A issue-32/A.mm -f issue-32/rhs.vec -p solver.type=gmres -p solver.maxiter=25 -o x.mm
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    2
Operator complexity: 1.37
Grid complexity:     1.14

level     unknowns       nonzeros
---------------------------------
    0         8874          55406 (72.73%)
    1         1226          20774 (27.27%)

Iterations: 25
Error:      0.000254362

[Profile:       0.581 s] (100.00%)
[ self:         0.001 s] (  0.16%)
[  reading:     0.165 s] ( 28.39%)
[  setup:       0.144 s] ( 24.75%)
[  solve:       0.266 s] ( 45.77%)
[  write:       0.005 s] (  0.93%)

$ ./solver_complex -A issue-32/A.mm -f issue-32/rhs.vec -p solver.type=gmres -o x.mm
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    2
Operator complexity: 1.37
Grid complexity:     1.14

level     unknowns       nonzeros
---------------------------------
    0         8874          55406 (72.73%)
    1         1226          20774 (27.27%)

Iterations: 100
Error:      4.76915e-06

[Profile:       1.319 s] (100.00%)
[  reading:     0.102 s] (  7.77%)
[  setup:       0.138 s] ( 10.49%)
[  solve:       1.072 s] ( 81.27%)
[  write:       0.005 s] (  0.41%)
```
The result in `x.mm` looks normal in both cases:
```
$ head x.mm
%%MatrixMarket matrix array complex general
8874 1
0.501495 0.0312248
0.501486 0.0310876
0.501468 0.0308098
0.50144 0.030407
0.501415 0.0299163
0.50137 0.0292985
0.501295 0.02851
0.501185 0.0276329
```

I do have a problem with bicgstab (it breaks down with a `zero omega` message). Also, I had to add the matrixmarket header to the `rhs.vec` file:
```
%%MatrixMarket matrix array complex general
8874 1
0 0
0 0
0 0
```

Can you tell what exact components you used for the test?

**Comment by dondieselkopf** [comment]
Thanks for checking this. Your code works indeed. And I just realised that I was using a somewhat old version of amgcl. Seems like there used to be a problem - which you have fixed in a recent release. Unless you want to look into the bicgstab problem, we could close the ticket.

**Comment by ddemidov** [comment]
I think bicgstab may legitimately breakdown for some problems, may be depending on the rhs and the initial approximation. For example, you could try to fix it by using random initial solution. So I don't feel inclined to investigate this further. By the way, you could try to use the recently added `lgmres` instead of `gmres`, this may converge faster:
```
./solver_complex -A issue-32/A.mm -f issue-32/rhs.vec -o x.mm -p solver.type=lgmres
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    2
Operator complexity: 1.37
Grid complexity:     1.14

level     unknowns       nonzeros
---------------------------------
    0         8874          55406 (72.73%)
    1         1226          20774 (27.27%)

Iterations: 100
Error:      9.37175e-08

[Profile:       1.365 s] (100.00%)
[  reading:     0.116 s] (  8.52%)
[  setup:       0.138 s] ( 10.14%)
[  solve:       1.104 s] ( 80.89%)
[  write:       0.005 s] (  0.39%)
```

**Comment by dondieselkopf** [comment]
Wow, the `lgmres` is quite an improvement - thanks for the hint. Can you also use guess vectors with `lmgres` to speed up e.g. the iterative solution of a non-linear system?

**Comment by ddemidov** [comment]
> Can you also use guess vectors with lmgres to speed up e.g. the iterative solution of a non-linear system?

Not with the current API. Do you think that would be useful?

**Comment by dondieselkopf** [comment]
Well, in fact I wasn't aware of LMGRES until just now. And apparently that's one of the main advantages of the algorithm, right? So I personally don't know how much of an advantage this features really yields. I do solve time-dependent problems and I may be able to make good use of it. But if its worth the implementation effort, I dunno. I am also afraid that I cannot be of much help with it due to very limited spare time ...

**Comment by ddemidov** [comment]
LGMRES, as it implemented in AMGCL, will not purge the augmentation vectors between calls. So if you are creating the LGMRES solver once and use it repeatedly, it will carry the information about your problem and hopefully converge faster for subsequent calls.

**Comment by dondieselkopf** [comment]
Thanks for the hint. I may take a look at that!
