### ISSUE TITLE
Nested solvers via the runtime interface

### ISSUE THREAD

**Issue by jdumas** [ddemidov/amgcl#33]
Hi,

I see from the documentation that it is now possible to nest solvers in AmgCL. I was wondering if it is possible to define such nested solvers via the runtime interface? This would be great to allow quick prototyping without resorting to the python bindings.

**Comment by ddemidov** [comment]
`make_solver` is a valid preconditioner itself, so you can just nest solvers like this:
```cpp
typedef amgcl::backend::builtin<double> Backend;

typedef
    amgcl::make_solver<
        amgcl::make_solver<
            amgcl::runtime::amg<Backend>,
            amgcl::runtime::iterative_solver<Backend>
        >,
        amgcl::runtime::iterative_solver<Backend>
    > Solver;
```

The parameter structure in this case is
```
precond      # Outer preconditioner, which is 'make_solver'
    precond  # Preconditioner for the inner solver, which is 'amg'
    solver   # Inner iterative solver
solver       # Outer iterative solver
```

Here is an example of setting the parameters:
```cpp
boost::property_tree::ptree prm;

// Restrict tolerance of inner solver
prm.put("precond.solver.tol", 1e-1);

// Set relaxation for the nested preconditioner:
prm.put("precond.precond.relax.type", "ilu0");

Solver solve(boost::tie(n, ptr, col, val), prm);
```

**Comment by jdumas** [comment]
Actually what I wanted to do is to be able to create both a "normal" multi-grid solver, and a "nested" solver, by changing the runtime parameters given to my application. For example if I give the following json parameter tree:

```json
{
    "precond": {
        "type": "nested",
        "precond": { ... },
        "solver" : { ... },
    },
    "solver": { "type": "cg" }
}
```

Then it should create a nested solver directly. But if I input:

```json
{
    "precond": {
        "type": "amg",
        "coarsening": { ... },
    },
    "solver": { "type": "cg" }
}
```

Then it should create only one level of multigrid preconditioner. Right now I feel there is no "easy" way to achieve this.

**Comment by ddemidov** [comment]
Ok, I got your point now. 53372be implements `amgcl::runtime::preconditioner<Backend>` (and uses it in [examples/solver.cpp](https://github.com/ddemidov/amgcl/blob/53372bed5c18037c4e0a370126b020dacfac5825/examples/solver.cpp#L363-L367)). Valid choices are "amg", "relaxation" (single-level smoother as preconditioner), and "nested" (nested `make_solver` as preconditioner).

The nested `make_solver` uses `runtime::preconditioner` as preconditioner, so you can have arbitrary level of nesting.

Example:
```
$ ./solver -p precond.type=nested -p precond.solver.maxiter=2
bicgstab: 32768 unknowns
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    2
Operator complexity: 1.51
Grid complexity:     1.13

level     unknowns       nonzeros
---------------------------------
    0        32768         223232 (66.13%)
    1         4192         114356 (33.87%)

Iterations: 2
Error:      2.45019e-11

[Profile:          0.656 s] (100.00%)
[ self:            0.001 s] (  0.11%)
[  assembling:     0.003 s] (  0.52%)
[  setup:          0.528 s] ( 80.42%)
[  solve:          0.124 s] ( 18.96%)
```

**Comment by ddemidov** [comment]
I've renamed 'type' parameter to 'class' so that it does not clash with `precond.type` when single-level relaxation is used as preconditioner:
```
./solver -p precond.class=relaxation -p precond.type=ilu0
```

**Comment by jdumas** [comment]
That's pretty cool, thanks! I'll try it out asap.
