### ISSUE TITLE
Complex GMRES solver

### ISSUE THREAD

**Issue by dondieselkopf** [ddemidov/amgcl#34]
I may have found a small bug in the generic GMRES implementation. Please take a look at [[1]](http://www-users.cs.umn.edu/~saad/IterMethBook_2ndEd.pdf) in Section 6.5.9 on the complex implementation of GMRES. They state that the complex Givens rotation is defined slightly different from the real one, see equation 6.80. When I change it [here](https://github.com/ddemidov/amgcl/blob/master/amgcl/solver/gmres.hpp#L260) accordingly, I get much better convergence in the complex case. Can you confirm this? Do you think there will be a similar issue for LGMRES and FGMRES?

Chris

[1] Saad, Yousef. Iterative methods for sparse linear systems. Siam, 2003.

**Comment by ddemidov** [comment]
I think you are correct. Does #35 look good to you? I don't have any non-trivial complex ploblems, so I can not test this myself (by the way, do you know if there is a simple complex problem that could be easily generated?).

The implementations of LGMRES and FGMRES in amgcl use Arnoldi orthogonalization process instead of Givens rotations, so I don't think this should be an issue for those. Do you get good convergence with the solvers?

**Comment by dondieselkopf** [comment]
Yes, that's what I did, too. For my example at hand, this gave much better results. Thanks for committing this.

Regarding the example, I can't really think of a much different one than [this](https://github.com/ddemidov/amgcl/blob/master/tests/sample_problem.hpp). The system I work on currently has 300k unknowns. Guess this is not a suitable example.

But since you are asking about it, I am struggeling a bit with the convergence when using any of the solvers on this problem. The sytem is not singular, but slightly ill-conditioned with `min(diag(A))/max(diag(A))=1e-11`. I am not sure if this is the problem. The best results I obtain with the *GMRES solvers. Checking the solution is simple, since it has to lie in the range `[0,1]`. Usually I get something outside this range. Increasing `maxiter` further increases the error. With the above fix, however, the GMRES solver converges to something very close to `[0,1]`. I therefore assumed that there is a similar issue in the other two GMRES solvers. Do you mind taking a look at the problem?

**Comment by ddemidov** [comment]
Can you upload the matrix in MatrixMarket format somewhere?

**Comment by dondieselkopf** [comment]
The system is too large for a direct upload here. So I have put it in a repo:

https://github.com/dondieselkopf/data.git

Thanks for looking at it.

**Comment by ddemidov** [comment]
One thing that is different between GMRES, LGMRES, and FGMRES, is that GMRES uses left preconditioning, while LGMRES and FGMRES use right preconditioning. LGMRES allows to choose the preconditioning side though. And it does seem to converge to the correct solution in this case:
```
$ ./solver_complex -A ill_complex/A.mm -o ill_complex/x.mm -f ill_complex/rhs.mm -p solver.type=lgmres -p solver.pside=left
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    3
Operator complexity: 1.39
Grid complexity:     1.14

level     unknowns       nonzeros
---------------------------------
    0       353418        2183741 (71.95%)
    1        47527         826221 (27.22%)
    2         1738          24950 ( 0.82%)

Iterations: 100
Error:      0.0057606

[Profile:      12.454 s] (100.00%)
[  reading:     4.890 s] ( 39.27%)
[  setup:       0.327 s] (  2.62%)
[  solve:       6.882 s] ( 55.26%)
[  write:       0.346 s] (  2.78%)
```
```
$ ./ill_complex/check_x.py ill_complex/x.mm
|x| is in [0.000000e+00 - 1.189170e+00]
```
Here `check_x.py` is
```py
#!/usr/bin/env python
import sys
from scipy.io import mmread
x = mmread(sys.argv[1] if len(sys.argv) > 1 else 'x.mm')
print('|x| is in [{:e} - {:e}]'.format(min(abs(x.ravel())), max(abs(x.ravel()))))
```

**Comment by ddemidov** [comment]
It looks like the problem is not in the solvers, but in the preconditioner. 46f62c6 adds a dummy (identity matrix) preconditioner. With that, all three solvers yield reasonable solution:
```
./solver_complex -A ill_complex/A.mm -f ill_complex/rhs.mm -o ill_complex/x.mm -p solver.type=lgmres -p precond.class=dummy
identity matrix as preconditioner
  unknowns: 353418
  nonzeros: 2183741

Iterations: 100
Error:      2.28687e-07

[Profile:       9.027 s] (100.00%)
[  reading:     4.941 s] ( 54.74%)
[  setup:       0.079 s] (  0.87%)
[  solve:       3.669 s] ( 40.65%)
[  write:       0.331 s] (  3.67%)
```
```
./ill_complex/check_x.py ill_complex/x.mm 
|x| is in [0.000000e+00 - 1.000000e+00]
```

**Comment by ddemidov** [comment]
Best performance I could get is with `lgmres` solver, and `ilu0` smoother used as a single level right preconditioner:
```
./solver_complex -A ill_complex/A.mm -f ill_complex/rhs.mm -o ill_complex/x.mm -p solver.type=lgmres -p precond.class=relaxation -p precond.type=ilu0
Using ilu0 as preconditioner
  unknowns: 353418
  nonzeros: 2183741

Iterations: 12
Error:      9.88003e-09

[Profile:       5.979 s] (100.00%)
[ self:         0.007 s] (  0.11%)
[  reading:     4.995 s] ( 83.54%)
[  setup:       0.133 s] (  2.22%)
[  solve:       0.432 s] (  7.23%)
[  write:       0.413 s] (  6.90%)
```

```
./ill_complex/check_x.py ill_complex/x.mm 
|x| is in [0.000000e+00 - 1.016300e+00]
```

**Comment by dondieselkopf** [comment]
Indeed, this seems to work pretty well. Although I am a bit puzzled as to why. Can you briefly explain what is going on behind the scenes? In my code, I had put `amgcl::runtime::amg<Backend>` as the preconditioner to `amgcl::make_solver`. What does `amgcl::runtime::preconditioner` mean here? Do we not use multigrid precondition anymore?

**Comment by ddemidov** [comment]
`runtime::preconditioner` was introduced as a result of #33.
Basically, its a convenience class, that allows to choose between amg, single-level relaxation, nested solver, (and now dummy identity matrix) as preconditioner. The choice is controlled with runtime "class" parameter. See https://github.com/ddemidov/amgcl/blob/master/examples/solver_complex.cpp#L208-L212 for example.

So with `precond.class="relaxation"` a single level smoother is used as preconditioner. With `precond.type="ilu0"` the smoother used is incomplete LU with zero fill-in.

**Comment by ddemidov** [comment]
You can also choose the single-level preconditioner at compile time by replacing `amgcl::runtime::amg<Backend>` with `amgcl::runtime::relaxation::as_preconditioner<Backend>`

**Comment by dondieselkopf** [comment]
That  means that single-level relaxation performs better than AMG preconditioning on my matrix? This seems strange to me. I need to play around with the new possibilities a bit more to get a better feeling. What I already see is that LGMRES converges faster than GMRES, but yields a less accurate solution in terms of what I expect (between 0 and 1).

**Comment by ddemidov** [comment]
There are problems where multigrid is not a good match. But after your question I tested multigrid with `ilu0` used as relaxation. And indeed, it converges in fewer iterations than plain `ilu0`:
```
./solver_complex -A ill_complex/A.mm -f ill_complex/rhs.mm -o ill_complex/x.mm -p precond.relax.type=ilu0 -x 1 -p solver.type=lgmres
coarsening:          smoothed_aggregation
relaxation:          ilu0
Number of levels:    3
Operator complexity: 1.39
Grid complexity:     1.14

level     unknowns       nonzeros
---------------------------------
    0       353418        2183741 (71.95%)
    1        47527         826221 (27.22%)
    2         1738          24950 ( 0.82%)

Iterations: 5
Error:      7.76473e-09

[Profile:       6.145 s] (100.00%)
[ self:         0.009 s] (  0.15%)
[  reading:     4.960 s] ( 80.72%)
[  setup:       0.385 s] (  6.26%)
[  solve:       0.444 s] (  7.23%)
[  write:       0.346 s] (  5.64%)
```

```
./ill_complex/check_x.py ill_complex/x.mm 
|x| is in [2.338644e-16 - 1.000000e+00]
```

Although in this case the overall time is higher than with plain `ilu0`, because (1) setup is more expensive, and (2) single V-cycle is more expensive than single sweep of `ilu0`.

**Comment by dondieselkopf** [comment]
With the `ilu0` preconditioner the performance looks pretty good on my type of system. However, once in a while I still get a solution which is slightly out of range, although the solver has converged. It would be great if we could find the reason for that. I try to prepare another example with a particularly bad result.

**Comment by ddemidov** [comment]
What kind of system is this? A coupled system of PDEs or a single PDE?

**Comment by dondieselkopf** [comment]
It is a single Laplace equation from an electrostatics problem. The coeffiecient is complex and varies strongly with position. Some of the unknowns are only weakly coupled to the others. I supposed that the error in those unknowns only weakly affects the residual norm. Therefore the solver converges but the solution but a relatively large error remains in the solution.

**Comment by ddemidov** [comment]
Can you try a solution with `smoothed_aggr_emin` used as a coarsening? It is based on [1], and should work better in case of non-symmetric systems, and may be for systems with strongly varying coefficients as well. It does more iterations for the system you sent me, and I can not really see a difference in the solution, but may be it would yield better quality results overall?


```
./solver_complex -A ill_complex/A.mm -f ill_complex/rhs.mm \
    -p precond.relax.type=ilu0 -p solver.type=lgmres \
    -p precond.coarsening.type=smoothed_aggr_emin
coarsening:          smoothed_aggr_emin
relaxation:          ilu0
Number of levels:    3
Operator complexity: 1.39
Grid complexity:     1.14

level     unknowns       nonzeros
---------------------------------
    0       353418        2183741 (71.95%)
    1        47527         826221 (27.22%)
    2         1738          24950 ( 0.82%)

Iterations: 17
Error:      7.36666e-09

[Profile:       7.338 s] (100.00%)
[  reading:     4.962 s] ( 67.62%)
[  setup:       0.872 s] ( 11.89%)
[  solve:       1.502 s] ( 20.47%)
```

[1] Sala, Marzio, and Raymond S. Tuminaro. "A new Petrov-Galerkin smoothed aggregation preconditioner for nonsymmetric linear systems." SIAM Journal on Scientific Computing 31.1 (2008): 143-166. http://epubs.siam.org/doi/abs/10.1137/060659545

**Comment by dondieselkopf** [comment]
Thanks for the hint. I need to test it a bit more, but it doesn't seem to work much better. I am afraid I still have a somewhat deeper problem: Your check function is only testing the norm of the individual elements of the solution. Although I cannot prove it, I guess that the real part of my solution also has to be in the range `[0,1]`. I am doing some postprocessing with the solution and if the real part gets significantly off from this range, the overall solution seems somehow off. The solver only looks at the norm of the vector elements, which may be the reason for this. But I really need to look more closely into what I expect as a solution ...

**Comment by dondieselkopf** [comment]
I have looked further into my problem. My system has certain symmetries that need to show up in the solution, which I can use to check the solver. With GMRES; the symmetries apprear alright in my solution. Using LGRMES - altough it converges nicely and much more quickly - the symmetries are slightly destroyed. In fact, the behaviour looks just like the GMRES behaved before the recent fix in the Housholder algorithm. Do you think that there could be a similar bug in the complex Arnoldi iteration? After this week I may also have some time to check that...

**Comment by ddemidov** [comment]
I think it should be possible to switch to using Givens rotations instead of Householder transformations in lgmres/fgmres. I can try to do this, but I am not sure when exactly I'll have enough time to do this.

**Comment by ddemidov** [comment]
@dondieselkopf, could you please check if lgmres and fgmres from #38 work better for you?

**Comment by dondieselkopf** [comment]
Hi. Thanks for putting in the effort! Looks pretty good. Although I still have small inaccuracies in my result. However, this may now be due to the solver tolerance setting. I changed from ´1e-8´ to ´1e-9´ which got me a bit closer to what I was expecting. I am afraid I need some more time to test it...

**Comment by ddemidov** [comment]
Looks like you could also benefit from `long double` precision. The builtin backend should support that.

**Comment by dondieselkopf** [comment]
This is a pretty good idea, although the problem seems to lie in my unstable postprocessing. First, I would like to exclude accuracy problems coming from the solver. Is there a solver configuration which only uses a direct solver?

**Comment by ddemidov** [comment]
> Is there a solver configuration which only uses a direct solver?

If you are using amg preconditioner, then you can set the [`coarse_enough`](https://github.com/ddemidov/amgcl/blob/master/amgcl/amg.hpp#L109-L115) parameter so that its higher than your number of equations. Then the system will be immediately considered as suitable for direct solve. The direct solver uses sparse LU decomposition, and may become unfeasible after 10000 unknowns or so.

**Comment by dondieselkopf** [comment]
I guess 10k is not even enough for checking my algorithms. Another idea I have is to add the derivative which I calculate in postprocessing as another unknown to the system. The solver should then take care of the accuracy of this derivative.

**Comment by ddemidov** [comment]
Well, what I meant by unfeasible is that it takes much more time than necessary and is a bad idea to use in production code. It is still possible to do this:
```
$ ./solver_complex -A ill_complex/A.mm -f ill_complex/rhs.mm -p precond.coarse_enough=1000000 -p solver.type=lgmres
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    1
Operator complexity: 1.00
Grid complexity:     1.00

level     unknowns       nonzeros
---------------------------------
    0       353418        2183741 (100.00%)

Iterations: 1
Error:      2.22045e-14

[Profile:     576.959 s] (100.00%)
[  reading:     5.073 s] (  0.88%)
[  setup:     569.120 s] ( 98.64%)
[  solve:       2.764 s] (  0.48%)
```

**Comment by dondieselkopf** [comment]
Think I found the source for the inaccuracies. My system has Dirichlet BCs, which I explicitly write into the matrix as `A_ii = 1`. If I eliminate those DOFs, I get a symmetric matrix which converges much more slowly. Thus I assume that the problem lies with the Dirichlet BCs.

**Comment by ddemidov** [comment]
Dirichlet conditions should not be a problem themselves, but they could make the norm of RHS larger, thus making the exit condition more relaxed (exit condition is `norm(error) / norm(rhs) < tol`).

**Comment by dondieselkopf** [comment]
Yes, that's what I meant. However, it seems its not only the exit condition. The convergence rate seems somehow diminished. For the same number of iterations, I get larger deviations (compared to my expectation) when using the symmetric system (BCs eliminated) compared to the non-symmetric (BCs not elimanted).

**Comment by dondieselkopf** [comment]
I have tried to make the exit condition harder by reducing `norm(rhs)`. On the same matrix with explicit Dirichlet BCs I have mulitiplied each boundary equation with a small factor. This leads for example to `A_ii = 1e-5` and `rhs_i = 1e-5` (if `i`is a BC equation). It seems that the convergence gets worse the smaller this factor is. I have created 3 examples: Running the solver on [explicit_1e0](https://github.com/dondieselkopf/data/blob/master/explicit_1e0.tar.gz) which has a factor of `1` yields a pretty good result:
```
$ cd explicit_1e0 && ../solver_complex -A A.mm -f rhs.mm -o x.mm -p solver.type=lgmres -p precond.class=dummy && ../check_x.py && cd ..
identity matrix as preconditioner
  unknowns: 353418
  nonzeros: 2183741

Iterations: 100
Error:      2.01399e-07

[Profile:       7.974 s] (100.00%)
[  reading:     4.886 s] ( 61.28%)
[  setup:       0.062 s] (  0.78%)
[  solve:       2.709 s] ( 33.97%)
[  write:       0.309 s] (  3.88%)


|x| is in [0.000000e+00 - 1.000000e+00]
```
The error becomes larger on [explicit_1e-2](https://github.com/dondieselkopf/data/blob/master/explicit_1e-2.tar.gz) which has a factor of `1e-2`:
```
$ cd explicit_1e-2 && ../solver_complex -A A.mm -f rhs.mm -o x.mm -p solver.type=lgmres -p precond.class=dummy && ../check_x.py && cd ..
identity matrix as preconditioner
  unknowns: 353418
  nonzeros: 2183741

Iterations: 100
Error:      2.01403e-05

[Profile:       7.932 s] (100.00%)
[  reading:     4.932 s] ( 62.17%)
[  setup:       0.062 s] (  0.78%)
[  solve:       2.625 s] ( 33.10%)
[  write:       0.306 s] (  3.86%)


|x| is in [0.000000e+00 - 1.000000e+00]
```
Finally with a factor of `1e-5` on this example [explicit_1e-5](https://github.com/dondieselkopf/data/blob/master/explicit_1e-5.tar.gz) is even worse:
```
$ cd explicit_1e-5 && ../solver_complex -A A.mm -f rhs.mm -o x.mm -p solver.type=lgmres -p precond.class=dummy && ../check_x.py && cd ..
identity matrix as preconditioner
  unknowns: 353418
  nonzeros: 2183741

Iterations: 100
Error:      0.020166

[Profile:       7.873 s] (100.00%)
[ self:         0.008 s] (  0.10%)
[  reading:     4.919 s] ( 62.48%)
[  setup:       0.061 s] (  0.77%)
[  solve:       2.581 s] ( 32.78%)
[  write:       0.305 s] (  3.87%)


|x| is in [0.000000e+00 - 9.995930e-01]
```
If I fully eliminate the BCs, this gets even worse. I don't think it makes much sense. Do you see a simple reason for that? Maybe there is a setting which can be used to mitigate this behaviour?

**Comment by ddemidov** [comment]
I am sorry for keeping this hanging. I was not able to reliably solve your system with amgcl. Any solution that I get from an iterative method is very different from the one I get from the direct solve.

**Comment by dondieselkopf** [comment]
Thanks for checking. If this is the case, I will try to improve the condition by using a different discretization approach for my PDE.

**Comment by ddemidov** [comment]
Can this be closed?

**Comment by RoadToDream** [comment]
Sorry everyone, I know it's an old issue, but may I ask if the conclusion is that directly using Givens rotation is more stable than using Householder transformation in GMRES? I see there is a back-and-forth commit about Householder transformation (99d7826 and 1999384).
