### ISSUE TITLE
Gauss-Seidel implementation

### ISSUE THREAD

**Issue by jdumas** [ddemidov/amgcl#36]
Looking at the code for the Gauss-Seidel relaxation, l.87 of the method `apply` reads as:

    for(size_t i = n; i-- > 0;)   iteration_body(A, rhs, x, i);

Which looks a bit suspicious. I reckon that the iteration should start at n-1 (last row), and the index should be a signed integer (otherwise it will produce an infinite loop).

Am I missing something?

**Comment by ddemidov** [comment]
That is a common pattern (I believe) for downward iteration with unsigned counter. I is post - incremented in condition, so when the body is reached its already is equal to n-1. This way there is no underflow in the unsigned counter when zero is reached.

**Comment by jdumas** [comment]
Ah, yes, the test is `> 0`, not `>= 0`. My bad! Still, `iteration_body` should be called with argument `i-1`, or the index will be out of bound at the first iteration?

**Comment by jdumas** [comment]
Oh, I get it now! The counter decrementation is done in the second part of the for loop. And it tests for `> 0`, not `>= 0`. My bad then! That's a nice trick I have to say.
