### ISSUE TITLE
Citeable reference?

### ISSUE THREAD

**Issue by Andlon** [ddemidov/amgcl#41]
Dear Denis,

I've been using amgcl for a small (but fairly important) part of my master's thesis. I was already using Eigen for most of the other numerical work, so using your library with the Eigen backend turned out to be a good deal simpler than integrating with huge libraries like ML or Hypre, as I could cobble something workable together within a very short amount of time. It has certainly worked very well for me, and I greatly appreciate your work, as well as the fact that you've made it open source.

I would like to cite your work, somehow. I couldn't find anything in the docs or in the repo. Do you have a preference for how you would want potential users to cite your work on amgcl in academic papers?

**Comment by ddemidov** [comment]
Thanks for asking!

I don't yet have anything published on the library, so you could just reference the github repo. I guess something like this should work:

[?] Denis Demidov, AMGCL - a C++ library for solving large sparse linear systems with algebraic multigrid method, https://github.com/ddemidov/amgcl, as seen on 26.01.2017.

**Comment by Andlon** [comment]
I think this issue is ready for closing at this point. Although perhaps you could consider adding a note to the documentation for others wanting to cite your work on `amgcl`?

You may also want to know that I used `amgcl` in conjunction with my master's thesis, which I handed in in the middle of March. Some of my work is available in a [Github repo](https://github.com/Andlon/crest), which also links to the thesis itself. Thanks again for your work on this library! It turned out to be really useful for my own work.

**Comment by ddemidov** [comment]
Thank you for the information and congratulations on your master degree! I'll keep this open as a reminder to myself to update the documentation.

**Comment by ddemidov** [comment]
Some progress:
https://arxiv.org/abs/1710.03940

**Comment by ddemidov** [comment]
https://arxiv.org/abs/1811.05704
