### ISSUE TITLE
npost not used in amg.hpp

### ISSUE THREAD

**Issue by cmuenger** [ddemidov/amgcl#47]
Dear Denis,
I was looking through the code, because wanted to known, how I could use the AMG as standalone because I need some data about its convergence for my bachelor's thesis.  And then I noticed by chance that it should be npost instead of npre in the for-loop in line 514 of amg.hpp. If I'm not mistaken.
By the way great work. 
Regards Cedric

**Comment by ddemidov** [comment]
That is correct, thanks for spotting it!
