### ISSUE TITLE
bug in subdomain deflation

### ISSUE THREAD

**Issue by RiccardoRossi** [ddemidov/amgcl#49]
Hi @ddemidov,

i have been tracking bugs in my code, by compiling with
-std=c++11 -D_DEBUG -D_GLIBCXX_DEBUG

the checks detect a problem in subdomain_deflation when using Eptr within the MPI_Gatherv function

essentially the thing is that Eptr is empty everywhere except on the master_rank, so 
&Eptr[0] is not a valid access.

     std::vector<int> Eptr;
            if (comm.rank == master_rank) {
                Eptr.resize(dv_start[cgroup_end] - dv_start[cgroup_beg] + 1, 0);
            }
//MY SUGGESTION WOULD BE TO ALWAYS RESIZE Eptr to at least 1 (it will be set to zero)

            MPI_Gatherv(
                    &eptr[1], ndv, MPI_INT, &Eptr[0] + 1,
                    const_cast<int*>(&ssize[0]), const_cast<int*>(&sstart[0]),
                    MPI_INT, 0, slaves_comm
                    );

**Comment by RiccardoRossi** [comment]
equivalente error here, with Ecol and Eval

            // Exchange strips of E.
            std::vector<int>        Ecol(2);
            std::vector<value_type> Eval(2);
            if (comm.rank == master_rank) {
                Ecol.resize(Eptr.back());
                Eval.resize(Eptr.back());

                for(int p = cgroup_beg, i = 0, offset = dv_start[p]; p < cgroup_end; ++p, ++i) {
                    sstart[i] = Eptr[dv_start[p]     - offset];
                    ssize[i]  = Eptr[dv_start[p + 1] - offset] - sstart[i];
                }
            }

            MPI_Gatherv(
                    &ecol[0], ecol.size(), MPI_INT, &Ecol[0],
                    const_cast<int*>(&ssize[0]), const_cast<int*>(&sstart[0]),
                    MPI_INT, 0, slaves_comm
                    );

            MPI_Gatherv(
                    &eval[0], eval.size(), dtype, &Eval[0],
                    const_cast<int*>(&ssize[0]), const_cast<int*>(&sstart[0]),
                    dtype, 0, slaves_comm
                    );
            TOC("assemble E");

**Comment by RiccardoRossi** [comment]
another one (here cf[0] is the problem

**Comment by ddemidov** [comment]
Missed the second comment.
