### ISSUE TITLE
BiCGstab(L) with random initial approximation returns wrong results

### ISSUE THREAD

**Issue by ddemidov** [ddemidov/amgcl#52]
See KratosMultiphysics/Kratos#1086

**Comment by RiccardoRossi** [comment]
Hi Denis,

the result is perfectly reproducible if you run without openmp. I think this is a parallelization problem...

Riccardo

**Comment by ddemidov** [comment]
In fact, any non-zero initial approximation gives wrong results. It looks like the current implementation of BiCGStab(L) assumes initial x is always zero.
