### ISSUE TITLE
Modify the iterative solver parameters after solver set up

### ISSUE THREAD

**Issue by mo7ammedmostafa** [ddemidov/amgcl#64]
Hello 
I am trying to the AMGCL solver in phd thesis to solve the pressure poisson equation
In my solver algorithm, for every time step i do the following
1-construct the matrix
2-setup the preconditioner
3-solve the system with relative tol = 0.01
4-update the rhs 
5-solve the system with relative tol = 0.01 
6-update the rhs
7-solve the system with relative abstol = 1e-12

During the time step , the system matrix remain unchanged but the rhs changes and iterative solver parameters change
(1) Is it possible to change the iterative solver parameters after setup without having to destroy that setup and redo it again.
(2) Also would it possible to use the same precond for 2 or 3 more time steps even when the matrix system changes

I read the doc but I can't find a way to access the params after setup
I tried the following
```
boost::property_tree::ptree prm;
prm.put("solver.tol", 1e-2);
prm.put("precond.coarsening.relax", 0.75);
Solver solve(boost::tie(n3, ptr, col, val),prm);
boost::tie(iters, error) = solve(f, x);

solve.prm.solver.abstol = 1e-12; // change the abs tol
boost::tie(iters, error) = solve(f, x);
```

But the change was ignored

Thank you
Kamra

**Comment by ddemidov** [comment]
`amgcl::make_solver<>` packs together an iterative solver and a preconditioner for convenience. The solver is a lightweight object, and most time during setup is spent on the preconditioner. You could achieve what you need by constructing your own instances of preconditioner (persistent) and solver. Something like this should work:

```cpp
boost::property_tree::ptree p_prm;
prm.put("coarsening.relax", 0.75);
amgcl::runtime::amg<Backend> P(boost::tie(n3, ptr, col, val), p_prm);

boost::property_tree::ptree s_prm;
prm.put("tol", 1e-2);
auto S = std::make_shared<amgcl::runtime::iterative_solver<Backend>>(n3, s_prm);

boost::tie(iters, error) = (*S)(P.system_matrix(), P, f, x);

 // change the abs tol
prm.put("abstol", 1e-12);
// Rebuild solver, which is a relatively cheap operation:
S = std::make_shared<amgcl::runtime::iterative_solver<Backend>>(n3, s_prm);

boost::tie(iters, error) = (*S)(P.system_matrix(), P, f, x);
```
