### ISSUE TITLE
Question: How to retrieve the initial residual from the linear solvers?

### ISSUE THREAD

**Issue by klausbu** [ddemidov/amgcl#89]
I am thinking of implementing AMGCL in an application but I need to provide the application with the **initial residual** of the solve process and of course the final residual and number of iterations at the end of the process as input for the overall simulation progress monitoring.

How can I retrieve or calculate the initial residual?

A complete simulation requires 500 to 10.000 x5 linear systems solves to reach overall convergence and this progress is monitored.

**Comment by ddemidov** [comment]
The initial residual is `r0 = f - A x0`. If the initial approximation `x0 = 0`, then that becomes just the RHS. AMGCL does not report the initial residual back to the user, but you can compute the norm of the initial residual in the same way it is done in the amgcl solvers, for example here:

https://github.com/ddemidov/amgcl/blob/4a2fb5292dfb5faf8b787c74375453df40d0ee5d/amgcl/solver/cg.hpp#L145-L146

`norm(x)` is defined as `sqrt(inner_product(x,x))` here:

https://github.com/ddemidov/amgcl/blob/4a2fb5292dfb5faf8b787c74375453df40d0ee5d/amgcl/solver/cg.hpp#L225-L228

The total number of iterations and the final residual (relative to the initial one) are returned from the solver as a tuple, see here for an example:

https://github.com/ddemidov/amgcl/blob/4a2fb5292dfb5faf8b787c74375453df40d0ee5d/examples/vexcl.cpp#L58-L66

**Comment by klausbu** [comment]
I looked deeper into the requirements as it turned out that I need a deeper integration into the application workflow which requires parallel implementation of additional functionality. 

x0 isn't 0.0 but a vector taken from the previous timestep.

The procedure requires the following functionalities:

reduction (to compute the average value of x) - is there a function for that in AMGCL?
x_average = reduce(x)/n I could use thrust or make up an omp parallel routine but I'd like to stick to the backend if possible. 

Apparently it's not yet implemented in the current gcc compiler version.

spmv, axpby, norm and residual are the other functions required which are available.

**Comment by ddemidov** [comment]
The only reduction operation available as part of amgcl backend is [`backend::inner_product`](https://github.com/ddemidov/amgcl/blob/7a7d545cbbccaad223dbbfbdd5481890d4fa6707/amgcl/backend/interface.hpp#L183-L188) (Used both to get L2 norm of the residual and in Krylov subspace algorithms).

What exactly do you need `mean(x)` for? I think it would be a bad metric to follow the progress of the solvers, since what is really used as the exit condition is `norm2(residual) / norm2(rhs) < tol`. It should be easy to introduce `backend::sum()`, but it would feel weird, since it's not used anywhere in the library.

**Comment by klausbu** [comment]
I need to calculate the residual before AMGCL solves the linear systems of the current timestep. This is part of the simulation solution progress monitoring to see if the coupled system converges. As it's currently only running on one core, I need to implement it using omp.

Regarding the average(x), this seems to work:
    double xAvg = 0.0; // average x value
{
    int i;
    #pragma omp parallel for reduction (+:xAvg)
    for(i =0; i<n; i++) {xAvg += amgcl_x[i];}
    xAvg /= n;
}  
Now, how to conduct a matrix-vector multiplication similar to cusp::multiply(A, xBar, yBar); using the backend functionality? Where xBar is the vector  std::vector<double> xBar(n, xAvg);

**Comment by ddemidov** [comment]
> Now, how to conduct a matrix-vector multiplication similar to cusp::multiply(A, xBar, yBar); using the backend functionality? Where xBar is the vector std::vector xBar(n, xAvg);

If `cusp::multiply(A, xBar, yBar)` is equivalent to `yBar = A * xBar`, then in amgcl it is:
```cpp
backend::spmv(1, A, xBar, 0, yBar); // yBar = 0 * yBar + 1 * A * xBar
```
but if you need this to implement `r = f - A x`, then there is also
```cpp
backend::residual(f, A, x, r);
```

**Comment by ddemidov** [comment]
> This is part of the simulation solution progress monitoring to see if the coupled system converges.

Do you absolutely need it to be `mean(residual)`? Or you could get away with `norm2(residual)`? Either of those should decrease if the system converges, but I think the latter is more commonly used.

**Comment by klausbu** [comment]
I don't know the background but the application makes a big difference between the matrix solver level and the coupled system level and the situation before the linear systems of a particular timestep are solved and the end of the individual step. At the beginning, the focus is on the coupled system and at the end on the matrix solver.

When I try to use spmv, I get an error, that A is not defined in "this" scope and I have to admit, I am not good at dealing with namespaces which I think is the problem.

I am trying to include the function in my code as an intermediate step but this is the function where the CSR matrix is defined in form of 3 vectors.

     amgcl::backend::spmv(1, A, xBar, 0, yBar); // yBar = 0 * yBar + 1 * A * xBar

**Comment by ddemidov** [comment]
If you have `solver` (an instance of `amgcl::make_solver`), or `precond` (an instance of an amgcl preconditioner, for example, `amgcl::amg<>`) defined in the same scope, you could use `solver.system_matrix()` or `precond.system_matrix()` instead of A. This is better if you use non-default backend, because `system_matrix()` would return a matrix that is already transferred to the backend. So,
```cpp
 amgcl::backend::spmv(1, solver.system_matrix(), xBar, 0, yBar);
```

**Comment by karlrupp** [comment]
Note that `mean(x) = inner_product(x, all_ones) / x.size()` where `all_ones` is a vector of all ones. :-)

**Comment by klausbu** [comment]
I use the following setup but I can't access the matrix as you suggested, I get the following error:

Error: expected primary-expression before ».« token
     amgcl::backend::spmv(1, Solver.system_matrix(), xBar, 0, yBar); // yBar = 0 * yBar + 1 * A * xBar

And if I use
     amgcl::backend::spmv(1, solver.system_matrix(), xBar, 0, yBar); // yBar = 0 * yBar + 1 * A * xBar 

I get an error, "not defined in this scope"

```
// solver setup

typedef amgcl::make_solver<
    amgcl::amg<
        Backend,
        amgcl::runtime::coarsening::wrapper,
        amgcl::runtime::relaxation::wrapper
        >,
    amgcl::runtime::solver::wrapper<Backend>
    > Solver;

// solver parameter

    boost::property_tree::ptree prm;

    prm.put("solver.type", "cg");
    prm.put("solver.tol", tolerance_);
    prm.put("solver.maxiter", 100);
    prm.put("precond.coarsening.type", "smoothed_aggregation");
    prm.put("precond.relax.type", "ilu0");

// solve system

    Solver solve( std::tie(n, r, c, v), prm );
```

**Comment by ddemidov** [comment]
The following works for me:
```cpp
#include <iostream>
#include <vector>

#include <amgcl/adapter/crs_tuple.hpp>
#include <amgcl/backend/builtin.hpp>
#include <amgcl/amg.hpp>
#include <amgcl/make_solver.hpp>
#include <amgcl/coarsening/runtime.hpp>
#include <amgcl/relaxation/runtime.hpp>
#include <amgcl/solver/runtime.hpp>

int main() {
    int n = 2;
    std::vector<int>    ptr = {0, 1, 2};
    std::vector<int>    col = {0, 1};
    std::vector<double> val = {1, 1};
    std::vector<double> x = {1, 1};
    std::vector<double> y = {0, 0};

    typedef amgcl::backend::builtin<double> Backend;
    typedef
        amgcl::make_solver<
            amgcl::amg<
                Backend,
                amgcl::runtime::coarsening::wrapper,
                amgcl::runtime::relaxation::wrapper
                >,
            amgcl::runtime::solver::wrapper<Backend>
            >
        Solver;

    boost::property_tree::ptree prm;

    prm.put("solver.type", "cg");
    prm.put("solver.tol", 1e-6);
    prm.put("solver.maxiter", 100);
    prm.put("precond.coarsening.type", "smoothed_aggregation");
    prm.put("precond.relax.type", "ilu0");

    Solver solve( std::tie(n, ptr, col, val), prm );

    amgcl::backend::spmv(1, solve.system_matrix(), x, 0, y);

    std::cout << y[0] << " " << y[1] << std::endl;
}
```

**Comment by klausbu** [comment]
Thank you, there was an error in my order of things.

But maybe there is a simpler way of doing it. What this is about, is to calculate a factor to normalize the  initial residual to 1 maybe you're doing that in AMGCL somewhere else?

**Comment by ddemidov** [comment]
I am not sure what is it you need, but the tolerance in amgcl (the one you set as `solver.tol`) is already computed relative to the norm of the rhs.

**Comment by klausbu** [comment]
I think, the idea is to scale the residuals of all equations to 1.0 so they fit the same monitor "diagram", imagine you solve equations for U, p, kt and epsilon.

Step-by-step:

- calculate average of x  xBar
- create vector with average of x like v(m, xBar)
- calculate yBar = A*xBar stored in another vector yBar
- calculate y = A*x stored in another vector y
- calculate ymyBar = y - yBar stored in another vector ymyBar
- calculate bmyBar = b - yBar
- calculate factor = norm2(ymyBar) + norm2(bmyBar) + 1.0e-15    (+ 1.0e-15 to counter potential floating point exceptions)

- calculate r = b - A*x
- apply the factor initial_r0 = norm2(r)/factor;

**Comment by ddemidov** [comment]
Would Karl's idea work for you? It seems the overhead would be negligible anyway due to the overall algorithm complexity.

**Comment by ddemidov** [comment]
This should work:
```cpp
amgcl::backend::inner_product(x, all_ones);
```

**Comment by klausbu** [comment]
In the final step, when applying mean_x I get an error and t would be great to have this r stored as r_initial.

    amgcl::math::norm(r)/mean_x;

Error: no matching function for call of »abs(std::vector<int>&)«
         return std::abs(x);

**Comment by ddemidov** [comment]
Anything in `amgcl::math`, including `math::norm`, is for values (scalars, block values, or complex numbers). To get the norm of a vector you want to `sqrt(amgcl::backend::inner_product(r, r))`.

**Comment by klausbu** [comment]
After digging yet deeper into the source code and definitions, this is what I need to compute in the next step:

vec1, vec2, vec3, vec4 // available

vec4 = abs(vec1 - vec3) + abs(vec2 - vec3) // todo

vec4 = axpby(abs(axpby(vec1 - vec3)) + abs((axpby(vec2 - vec3))) // to be more precise 

Is there a function to convert a vector to contain only positive/absolute values?

**Comment by ddemidov** [comment]
> Is there a function to convert a vector to contain only positive/absolute values?

No, there is not. I think at this point you should just create your own function for the whole algorithm (overloaded for the amgcl backends you are planning to use). This should be trivial to implement.
