### ISSUE TITLE
Creating matrix elements on demand

### ISSUE THREAD

**Issue by NOhs** [ddemidov/amgcl#94]
The matrix generation for my problem is quite efficient. So I was wondering, if it is possible, for systems with less memory, to have a custom matrix class that does not store the sparse matrix, but in fact, generates entries on the fly to drastically reduce memory consumption. Can amgcl work with such a matrix?

**Comment by ddemidov** [comment]
It should be possible if you provide specialization for the matrix part of the backend interface:

https://github.com/ddemidov/amgcl/blob/3febe6853e4a3f07aabb31619a44ad3258d90e69/amgcl/backend/interface.hpp#L76-L180

Implementation of the  `matrix_builder` adapter may also be of interest: https://github.com/ddemidov/amgcl/blob/master/amgcl/adapter/crs_builder.hpp
