### ISSUE TITLE
'_copysign': is not a member of 'std'

### ISSUE THREAD

**Issue by dboaretti** [ddemidov/amgcl#98]
Dear Denis,

I have one issue compiling my code. I have updated the amgcl submodule and my compiler to make sure that I have everything up to date.
The issue comes from compiling the code with MSVC and the error that I see at the end is the following:

```
           "C:\Users\bdaniele\framework\build\temp.win-amd64-3.7\Release\ALL_BUILD.vcxproj" (default target) (1) ->
           "C:\Users\bdaniele\framework\build\temp.win-amd64-3.7\Release\src\python_interface\fracture_healing_cpp.vcxproj" (default target) (10) ->
           (ClCompile target) ->
             c:\users\bdaniele\framework\include\amgcl\amgcl\detail\qr.hpp(390): error C2039: '_copysign': is not a member of 'std' [C:\Users\bdaniele\framework\build\temp.win-amd64-3.7\Release\src\python_interface\fracture_healing_cpp.vcxproj]
```

So it seems that there is a problem related to copysign. In the source code at that line (qr.hpp, line 390) there is the call to std::copysign, but it seems that there is a conflict in the versions of copysign somehow. 
I don't know if this is enough, if not please do not hesitate to tell me what kind of info you need.

Thank you for your time.

**Comment by ddemidov** [comment]
Hello,

C++ standard states that starting with C++11, [`std::copysign` should be defined in `<cmath>` header](https://en.cppreference.com/w/cpp/numeric/math/copysign), and `<amgcl/detail/qr.hp>` [does include `<cmath>`](https://github.com/ddemidov/amgcl/blob/91348b025144b61a2d3b7417988373d0dc8c8d00/amgcl/detail/qr.hpp#L89).

So in this case I would blame the compiler. What version of MSVC do you use?

**Comment by ddemidov** [comment]
It should be easy to provide a workaround using `_MSC_VER` macro, but we would need to find out which versions of MSVC do not provide the function.

**Comment by ddemidov** [comment]
[This page](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/copysign-copysignf-copysignl-copysign-copysignf-copysignl?view=vs-2017) seems to suggest you need to include `<cfloat>` to get `_copysign`. Can you please check if including it in `<amgcl/detail/qr.hpp>` helps in your case?

**Comment by dboaretti** [comment]
I use MSVC 14.16.27023. 

I included ``cfloat`` in that file but I got exactly the same error.

**Comment by ddemidov** [comment]
Are you able to build amgcl tests and examples? Appveyor build server uses MSVC 14.0 and does not seem to have this problem:

https://ci.appveyor.com/project/ddemidov/amgcl/branch/master#L63

**Comment by ddemidov** [comment]
Can you check if 2c80b9d064ceca86e7b039c5692d1e65b2a8f612 helps?

**Comment by ddemidov** [comment]
So, what exactly was the problem (for the users having the same problem in the future)? Was it one of MSVC macros here?

https://github.com/ddemidov/amgcl/blob/91348b025144b61a2d3b7417988373d0dc8c8d00/CMakeLists.txt#L88-L91

**Comment by dboaretti** [comment]
From what I read on the web, the most probable macro that may affect the build is the `_SCL_SECURE_NO_WARNINGS`.  However, I don't have any of those macros defined in my code or in the cmake files, therefore the problem could be something else. I am sorry,I am not able to detect exactly the issue.

**Comment by ddemidov** [comment]
Should we keep the code as is, or do you think we should push 2c80b9d to the master branch?

**Comment by dboaretti** [comment]
I think we can push https://github.com/ddemidov/amgcl/commit/2c80b9d064ceca86e7b039c5692d1e65b2a8f612 to the master branch without problems.

**Comment by ddemidov** [comment]
Thanks for bringing this up!

**Comment by dboaretti** [comment]
Thank you so much for your help and your fast replies!!
